### ISSUE TITLE
ConnectionRefusedError in launcher

### ISSUE THREAD

**Issue by qq470647251** [microsoft/debugpy#459] opened 2020-11-03 10:43 UTC
.vscode\extensions\ms-python.python-2020.10.332292344\pythonFiles\lib\python\debugpy\launcher/../..\debugpy\launcher\__init__.py", line 34, in connect
    sock.connect((host, port))
ConnectionRefusedError: [WinError 10061]

https://github.com/microsoft/debugpy/issues/84#issue-585779852

[https://github.com/microsoft/debugpy/issues/84](url)

#84

**Comment by int19h** [comment] 2020-11-03 11:05
It might be the same error message, but it doesn't mean that it's the same bug as #84. Please provide debugpy logs so that we can diagnose this properly.

**Comment by qq470647251** [comment] 2020-11-05 20:29
when call  time.localtime() it's break 
but it's ok when use time.gmtime()

**Comment by int19h** [comment] 2020-11-05 22:22
Can you please provide:

1. A list of steps that reproduce the problem.

1. The *complete* code snippet that you're trying to debug, if possible.

1. debugpy logs - set `"logToFile": true` in your launch.json, and you'll find several files in `...\.vscode\extensions\ms-python.python-...` that all have names matching `debugpy*.log`.

**Comment by int19h** [comment] 2021-03-31 16:41
Closing since there's not enough information to investigate further.

**Closed by int19h** 2021-03-31 16:41 UTC
