### ISSUE TITLE
Getting this error: Assertion failed: (this->tracefunc.REFCNT() == old_refs + 1) #166079

### ISSUE THREAD

**Issue by cduran** [microsoft/debugpy#1124] opened 2022-11-14 14:55 UTC
## Environment data

- debugpy version: 1.6.3
- OS and version: macOS Monterey Intel Version 12.6.1 (21G217)
- Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
- Using VS Code or Visual Studio: VS Code: 1.73.1 (Universal)

## Actual behavior

Assertion failed: (this->tracefunc.REFCNT() == old_refs + 1), function set_tracefunc, file greenlet_thread_state.hpp, line 314.

## Expected  behavior

Ability to run the test from start to finish

## Steps to reproduce:

This happens also using python:
3.10.8
3.9.15

1. Have a project that works and uses with gevent
2. And then just star a debug session with "gevent": true in the launch.json

**Comment by int19h** [comment] 2022-11-14 22:16
Which version of gevent are you using?

**Comment by fabioz** [comment] 2022-11-16 18:01
Closing this one as a duplicate of: https://github.com/microsoft/debugpy/issues/1126 (apparently a newer version of greenlet is making the debugger misbehave -- the fix right now is using greenlet 1.1.3).

**Closed by fabioz** 2022-11-16 18:01 UTC
Labels: bug
