### ISSUE TITLE
Cannot launch debug session, error in vscode pythonFiles

### ISSUE THREAD

**Issue by tycode** [microsoft/debugpy#1010] opened 2022-08-10 18:17 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected behavior: starting a debug session (e.g. with F5) runs my Python module and allows me to set breakpoints, etc.

Actual behavior: starting a debug session shows a Python traceback from the VS Code Python extension (i.e. not from my code) and does not run my Python module.

The displayed traceback:
```
Traceback (most recent call last):
  File "c:\Users\rob\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 252, in _on_run
    self.process_net_command_json(self.py_db, json_contents)
  File "c:\Users\rob\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 193, in process_net_command_json
    cmd = on_request(py_db, request)
  File "c:\Users\rob\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 501, in on_launch_request
    return self._handle_launch_or_attach_request(py_db, request, start_reason='launch')
  File "c:\Users\rob\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 493, in _handle_launch_or_attach_request
    self._set_debug_options(py_db, request.arguments.kwargs, start_reason=start_reason)
  File "c:\Users\rob\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_process_net_command_json.py", line 443, in _set_debug_options
    if os.path.isdir(f):
  File "C:\Users\rob\AppData\Local\Programs\Python\Python310\lib\genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

I have tried a few different situations:
- Debugging works fine in extension versions 2022.4.1, 2022.6.3, 2022.8.1
- It doesn't work in extension versions 2022.10.0, 2022.10.1, 2022.12.0
- When I first encountered this (which was today) I was using Python 3.7.3. I since tried using Select Interpreter to switch to Python 3.10.0 but the issue still occurs so it would not appear to be related to using an old Python version.
- When I first encountered this, the traceback showed up within a MINGW64 shell in the integrated terminal. I thought this might have something to do with it, so changed my launch configuration to use `"console": "externalTerminal"`, but the issue still occurs, now appearing in a Command Prompt window titled VS Code Console so it would not appear to be related to using MINGW64.

My launch.json (it's as simple as can be)
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Python: Module",
			"type": "python",
			"request": "launch",
			"module": "launchbug",
			"console": "externalTerminal"
		}
	]
}
```

Inside the root folder of the workspace is a folder called `launchbug` containing a `__main__.py` containing my code.

## Steps to reproduce:

1. Create an empty folder `launchbug` and open the folder in VS Code
2. Create `.vscode/launch.json` as above
3. Create `launchbug/__main__.py` with the contents `print('Hello, world!')`
4. Press Ctrl+F5 and observe Python script runs correctly
5. Press F5 and observe error traceback (as above) instead of a debug session starting

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Telemetry is disabled
Experiments are disabled, only manually opted experiments are active.
LSP Notebooks experiment is disabled -- not in treatment group
LSP Notebooks interactive window support is disabled -- not in LSP Notebooks experiment
Python interpreter path: ~\AppData\Local\Programs\Python\Python310\python.exe
Starting Pylance language server.
DAP Server launched with command: C:\Users\rob\AppData\Local\Programs\Python\Python310\python.exe c:\Users\rob\.vscode\extensions\ms-python.python-2022.12.0\pythonFiles\lib\python\debugpy\adapter
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• pylintArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2022.12.0
VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19043
Modes:

**Comment by int19h** [comment] 2022-08-10 20:35
Sounds like a dupe of https://github.com/microsoft/debugpy/issues/987. We'll ship a new debugpy version with this fix soon, but until then, you can follow the steps in the linked issue to patch your local copy.

**Closed by int19h** 2022-08-10 20:35 UTC

**Comment by tycode** [comment] 2022-08-11 16:43
> Sounds like a dupe of #987. We'll ship a new debugpy version with this fix soon, but until then, you can follow the steps in the linked issue to patch your local copy.

Thanks! Didn't even realise this debugpy was a separate repo. I'll continue using 2022.8.1 until the fix is released, as this version is working fine for me.

**Comment by lambdakris** [comment] 2022-08-17 14:38
Is there an estimate of when this fix may get released?

**Comment by int19h** [comment] 2022-08-17 19:33
debugpy 1.6.3 has the fix. @karthiknadig, what's the plan for shipping that in vscode-python?

**Comment by karthiknadig** [comment] 2022-08-17 22:09
Should go out in a bug fix release either today or tomorrow.

**Comment by karthiknadig** [comment] 2022-08-18 02:29
This is now in release 2022.12.1
