### ISSUE TITLE
Must local python interpreter has the same third-package with remote python interpreter？

### ISSUE THREAD

**Issue by galaxyFloating** [microsoft/debugpy#400] opened 2020-09-03 09:13 UTC
## Environment data

- debugpy version: 1.0.0rc2
- OS and version: mac 10.12.4
- Python version (& distribution if applicable, e.g. Anaconda): local 2.7.10 ; remote 2.7.16
- Using VS Code or Visual Studio: using vs code 1.48.2, Node.js: 12.8.1

## Actual behavior

Begin remote debug using debugpy, local attach remote well, but when do import a library which only installed in remote python, it throw " Exception has occurred: KeyError ('flags',)."
When close debugpy(and debug code), it works well

## Steps to reproduce:
1. in remote, python code.py, it wait in line  "debugpy.wait_for_client()"
2. in local, begin debug by attaching to remote

**Comment by int19h** [comment] 2020-09-03 17:35
The only requirement is to have debugpy installed on the remote.

The exception type, `KeyError`, is typically not something that you'd get due to a missing library (that should be an `ImportError`). Can you show the code that produces it? Or at least the traceback for the exception.

**Comment by int19h** [comment] 2020-09-22 23:56
Does the error also happen if you launch with Ctrl+F5 (Start without Debugging) instead of F5?

Also, try adding this to your launch.json:
```json5
"pythonPath": "./Python/bin/python"
```
does this resolve the issue?

**Comment by fabioz** [comment] 2020-10-22 13:27
Closing as there was no further input an this issue (feel free to reopen if you still can reproduce it and provide further information).

**Closed by fabioz** 2020-10-22 13:27 UTC
Labels: bug
