### ISSUE TITLE
Latest version crashing on input call.

### ISSUE THREAD

**Issue by d3rpp** [microsoft/debugpy#373] opened 2020-08-17 23:14 UTC
## Environment data

-   VS Code version: 1.48
-   Extension version (available under the Extensions sidebar): 2020.8.101
-   OS and version: Pop!OS (GNOME version: 3.36.3, Windowing System: X11)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.3
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): dark +
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Microsoft

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

The above made it worse

## Expected behaviour

the function takes the input from the question variable and converts it into an integer.
then returns it

## Actual behaviour

Program gets to line with input call and freezes

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Run the following code
```py
# clear(False) -> Clears the terminal using the clear and cls for everything but windows and windows respectively. 
# proven to work  without issue

def getIntegerInput(question:str) -> int:
    while True:
        try:
            clear(False)

            tmp = int(input(question))
            if tmp == "":
                return 0
            return tmp
        except ValueError:
            print("Sorry, but that is not a number. please use the digits (0 - 9)")
            continue
print(getIntegerInput("Give me a number: "))
```

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
N/A, there is nothing there. it freezes.
however, when I force quit the process it says

timeout after 1000ms
```

</p>
</details>

**Comment by int19h** [comment] 2020-08-18 17:28
Duplicate of #370

**Closed by int19h** 2020-08-18 17:28 UTC
