### ISSUE TITLE
Intellisense/autocomplete inside debug console

### ISSUE THREAD

**Issue by javierabosch** [microsoft/debugpy#585] opened 2021-04-08 18:42 UTC
## Environment data

- debugpy version: 1.2.1 
- OS and version: Linux 
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.8  conda 4.9.2
- Using VS Code or Visual Studio: vscode 1.55 

## Actual behavior

After starting debugging inside vscode, and stopping at a breakpoint, when I try to type an object with dot notation, I do not get any autocomplete or intellisense of its methods or functions available to the object. 

## Expected  behavior

I expect (hope) that the Pylance autocomplete/intellisense features are carried forward to the debug console. so that, for e.g. I can see methods available to me on an instance of a pandas Dataframe or some custom class instance. 

df.max
df.apply
df.shape

**Comment by fabioz** [comment] 2021-04-15 14:07
We do actually support code-completion in the debug console using runtime information.

i.e.:

![image](https://user-images.githubusercontent.com/117621/114881396-58e81180-9dd9-11eb-8ea5-a5c4db8e88f0.png)

So, please add information on your actual use-case so that it can be investigated.

**Comment by fabioz** [comment] 2021-04-21 12:35
I'm closing since no more information was added. 

Please reopen if you're able to provide some sample code to reproduce your issue.

**Closed by fabioz** 2021-04-21 12:35 UTC
