### ISSUE TITLE
Python debugger is unable to accept user input

### ISSUE THREAD

**Issue by SaadiSave** [microsoft/debugpy#372] opened 2020-08-18 03:43 UTC
## Environment data

-   VS Code version: 1.48.0
-   Extension version (available under the Extensions sidebar): 2020.8.101144
-   OS and version: Ubuntu 20.04 LTS
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.2
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Pylance (and Microsoft/Jedi)(tried all)

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

when user input is prompted using
<code>a = int(input())</code>
On typing 3, the debugger should accept the input and show that it is stored as global variable a = 3

## Actual behaviour

The debugger crashes when 3 is typed in and enter is pressed

## Steps to reproduce:

<code>a = int(input())</code>

When debugger prompts, type in 3 (or any integer) and press enter

## Logs
launch.json
<code>
{   
    "version": "0.2.0",  
    "configurations": [  
        {  
            "name": "Python: Current File",  
            "type": "python",  
            "request": "launch",  
            "program": "${file}",  
            "console": "integratedTerminal"  
        }  
    ]  
}  
</code>
<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
None
```

</p>
</details>

**Comment by fabioz** [comment] 2020-08-18 16:52
Duplicate of: https://github.com/microsoft/debugpy/issues/370

**Closed by fabioz** 2020-08-18 16:52 UTC
