### ISSUE TITLE
Debugger does not stop on breakpoints in certain file

### ISSUE THREAD

**Issue by tbrodbeck** [microsoft/debugpy#679] opened 2021-07-24 07:34 UTC
## Environment data

- debugpy version: 1.3.0
- OS and version: 11.4
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.6 from homebrew python@3.9
- Using VS Code or Visual Studio: 1.58.2

## Actual behavior

A breakpoint in a python file containing a class that is imported by my python application is not used to stop the debugger - even though the code is executed.

## Expected  behavior

All breakpoints of code that is run should be stopped at by the debugger.

## Steps to reproduce (for me):
1. Start Debugging

## Appendix

<details>

<summary>launch.json
</summary>

<p>

```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Python: Current File",
      "type": "python",
      "request": "launch",
      "program": "bin/experiment",
      "console": "integratedTerminal",
      "args": [
        "xgb",
        "line",
        "--mode=debug",
        "--logLevel=10"
      ],
      "logToFile": true
    }
  ]
}
```

</p>
</details>

The Debug log files are uploaded here: https://www.transferxl.com/details/08GTH6j17zDy5

**Comment by fabioz** [comment] 2021-07-24 11:26
@tbrodbeck just looking at the logs I couldn't really find anything that stands off as a bug...

I can see that you're using tensorflow and that you added a breakpoint at "/Users/t/dev/mastersThesis/models/eXtremeGradientBoosting.py" (line 22) and I can see that it stopped at an unhandled exception at that same file in line 25. I can also see that this file is considered being traced (so, things appear to be ok).

In short, just the logs aren't really enough info to diagnose the issue... So, let's see if it's possible to track it down.

I think the first step would be trying to run without the debugger builtin modules (in plain python trace mode)... if you set an environment variable such as:

`PYDEVD_USE_CYTHON=0`

and rerun, does it break properly?

If that still fails, do you think it's possible to provide a way for me to reproduce the issue here?

**Comment by tbrodbeck** [comment] 2021-07-24 14:49
Hi. I just checked the logs and you are right. The thing is, that the file is actually called _EXtremeGradientBoosting.py_ with a capital E. 
So I renamed the file to _eXtremeGradientBoosting.py_ and suddenly it is working. So I guess the issue is that breakpoints in capitalized files are not recognized.

**Comment by tbrodbeck** [comment] 2021-07-24 15:12
The thing is - I just tried to reproduce the issue and I could not. When I create a clone of my code repository and execute that it works.

**Comment by fabioz** [comment] 2021-07-24 17:36
Ha, this had escaped me... the logs definitely show that the file traced is:

`File traced: /Users/t/dev/mastersThesis/models/EXtremeGradientBoosting.py`

whereas the breakpoint is added in:

`/Users/t/dev/mastersThesis/models/eXtremeGradientBoosting.py`

on Windows that'd hit the breakpoint, but on Linux the casing must match.

So, the strange thing here is that `VSCode` decided to add the breakpoint as `eXtremeGradientBoosting.py` -- the usual culprit where I've seen that is on windows when the file changes case but the `.pyc` still keeps the old case, but in this case it seems that `VSCode` itself had a wrong representation of the file.

My suggestion is: 
1. Remove all the `.pyc` files around (as those contain a cache of the filename).
2. Restart VSCode (so that it hopefully sees things with the proper case).

If after that it still doesn't work, please report back.

**Comment by tbrodbeck** [comment] 2021-07-24 20:40
Hi @fabioz thanks for your reply. :)

I did `find . | grep __pycache__ | xargs rm -rf` and delete all .pyc files.

Then I restarted but the issue still persists!

**Comment by fabioz** [comment] 2021-07-25 11:03
Can you show a screenshot of how `VSCode` is seeing the casing of that file in the explorer /  screenshot of the breakpoints /  screenshot of running `ls -la` in that same directory?

If you remove all the breakpoints / restart VSCode / add the breakpoint again, does it work? (i.e.: maybe the issue is a cache of the breakpoints with the wrong case in VSCode?)

**Comment by tbrodbeck** [comment] 2021-07-25 16:40
> If you remove all the breakpoints / restart VSCode / add the breakpoint again, does it work? (i.e.: maybe the issue is a cache of the breakpoints with the wrong case in VSCode?)

I tried to remove the breakpoint, restart then add it again. Does not help unfortunately.

> Can you show a screenshot of how `VSCode` is seeing the casing of that file in the explorer / screenshot of the breakpoints / screenshot of running `ls -la` in that same directory?

Here is a screen capture - in the debug tab it is indeed lower case and this happens when I click the breakpoint:

https://user-images.githubusercontent.com/24418160/126906581-08e2cb59-c62a-4665-95c1-6ef2fd5fb206.mov

This is the output you requested:
```
➜  models git:(master) ls -la
total 72
drwxr-xr-x  12 t  staff   384 Jul 25 17:32 .
drwxr-xr-x  21 t  staff   672 Jul 25 17:14 ..
-rw-r--r--   1 t  staff   927 Jul 15 00:31 AutoregressiveIntegratedMovingAverage.py
-rw-r--r--@  1 t  staff  1893 Jul 25 15:35 EXtremeGradientBoosting.py
-rw-r--r--   1 t  staff   146 Jul 23 09:25 LagModel.py
-rw-r--r--   1 t  staff   511 Jul 22 23:13 LinearRegression.py
-rw-r--r--   1 t  staff  2054 Jul 25 17:32 LongShortTermMemory.py
-rw-r--r--   1 t  staff   936 Jul 25 16:27 Model.py
-rw-r--r--   1 t  staff   286 Jul 25 17:30 Previous.py
-rw-r--r--   1 t  staff   277 Jul 23 09:24 Regressor.py
-rw-r--r--   1 t  staff   156 Jul 24 16:56 __init__.py
drwxr-xr-x  10 t  staff   320 Jul 25 17:32 __pycache__
```

**Comment by fabioz** [comment] 2021-07-29 17:50
Did you restart with the breakpoint file open? 
It seems it opens the file with the proper path, so, my guess is that it had the file opened with the wrong path from a previous run (i.e.: still the same cache issue but from the open editor, not from the saved breakpoint)...

If that's not the case, and you can record the following:
1. Close all editors
2. Remove all breakpoints
3. Reopen VSCode
4. Open the `EXtremeGradientBoosting.py`
5. Add a breakpoint to `EXtremeGradientBoosting.py`
6. Run the debugger and check if it hit the breakpoint

That'd probably be a bug to be reported to VSCode itself (although the cache bug which is persisting a file with the wrong case could probably be reported too, but is probably not as high priority...)

**Comment by tbrodbeck** [comment] 2021-07-30 04:29
I am not sure how, but for some reason the debugging is now working. I really cannot tell you what fixed it 🙈

**Comment by fabioz** [comment] 2021-07-30 17:02
Ok, I'm going to close this issue (the whole issue happened because VSCode itself was passing a breakpoint with the wrong case on Linux, thus, even if reproducible, it'd be an issue in VSCode itself, not on debugpy).

**Closed by fabioz** 2021-07-30 17:02 UTC
