### ISSUE TITLE
breakpoint in file that does not exist

### ISSUE THREAD

**Issue by Mussil** [microsoft/debugpy#1109] opened 2022-10-30 08:05 UTC
## Environment data

- debugpy version: 1.6.3
- OS and version: Ubuntu 18.04.6
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.13
- Using VS Code or Visual Studio: VS Code

## Actual behavior

I try to attach to process from one container which run VS Code, to a process locate in different container (with the about information),
I see that the process attached, thanks to python output, but can not locate break point to stop into, 
" breakpoint in file that does not exist"
I checked with the logs, and no error appear except 
```"verified": false,
                             "id": 6,
                             "message": "Breakpoint in file that does not exist.",
..
```
I tried to change the remoteRoot in the launch.json (in the VS Code container) to access the right root of the source code, with no change. 
(https://github.com/microsoft/debugpy/issues/318)

This is how I activated the debugpy on the container:
` python3.8 -m debugpy --listen :5678 --log-to /logs --pid 8,`
and this error appear, which might be related:
**stderr: b'205\t../sysdeps/unix/sysv/linux/futex-internal.h: No such file or directory.\n'**

In addition, I followed this tutorial to allow gdb inside container:
https://taufanlubis.wordpress.com/2020/06/07/docker-tutorial-how-to-install-gdb-gnu-debugger-in-docker-container/

## Expected  behavior

Able to locate breakpoint, and stop on them.

**Comment by int19h** [comment] 2022-11-01 05:45
Can you share the entire log?

**Comment by fabioz** [comment] 2022-11-11 11:53
I'm closing since no available feedback was given, but feel free to reopen if you can provide the logs (see: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs for details on how to collect the logs).

As a note, if you're using a remote machine the problem is probably that you don't have `pathMappings` specified to map breakpoints from the path in your original machine to your remote machine.

**Closed by fabioz** 2022-11-11 11:53 UTC
Labels: bug, waiting for response
