### ISSUE TITLE
Breakpoints on QtCore.QRunnable are not working

### ISSUE THREAD

**Issue by wlbe4** [microsoft/debugpy#527] opened 2021-01-13 20:29 UTC
## Environment data

-   VS Code version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0

-   Extension version (available under the Extensions sidebar): 2020.12.42445261
-   OS and version: Windows 10 (Windows_NT x64 10.0.19041)
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: PyQt5 (Version 5.15.1)
-   Relevant/affected Python-related VS Code extensions and their versions: Pylance (2021.1.0), Jupiter (2020.12.414227025)
-   Value of the `python.languageServer` setting: 2021.1.0

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Hit a breakpoint on the run function of Worker class (derived from QtCore.QRunnable)

## Actual behaviour

Breakpoint does not hit.
Apparently, this bug happen in all recent releases and it was working fine on version 2020.11.358366026.
Since then all new versions doesn't hit the breakpoint on the "run" function.

## Steps to reproduce:

Use the bellow code:
```
from PyQt5 import QtCore

class Worker(QtCore.QRunnable):
    def __init__(self):
        super(Worker, self).__init__()

    def run(self):
        print('Running Worker')

class Tasks(QtCore.QObject):
    def __init__(self):
        super(Tasks, self).__init__()
        self.pool = QtCore.QThreadPool.globalInstance()
        self.pool.setMaxThreadCount(2)

    def start(self):
        for task in range(3):
            worker = Worker()
            self.pool.start(worker)
        self.pool.waitForDone()

if __name__ == '__main__':
    tasks = Tasks()
    tasks.start()
```
1. Set a breakpoint on the call to print in "run" function above
2. Start debug (hit F5)

**Comment by karthiknadig** [comment] 2021-01-14 04:45
Duplicate of #526

**Closed by karthiknadig** 2021-01-14 04:45 UTC
