### ISSUE TITLE
Debug console duplicate output, eg. print and doing complication to entry own comand vs sugestions

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#329] opened 2020-07-08 17:55 UTC
## Environment data

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 6.1.7601

**Using PyLance**

## Actual behavior
1. This is my console result

```
print("test")
None
test
test
print(sys.version_info)
NameError: name 'sys' is not defined
import szs
ModuleNotFoundError: No module named 'szs'

import sys
sys.version_info
sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
print(sys.version_info)
None
sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)

import debugpy; print(debugpy.__version__)
1.0.0b12
1.0.0b12
```

## Expected  behavior
2. Single print and output, enter for commands not sugestions (shift + enter = sugestion? )

## Steps to reproduce:
3. Put comands like in actual behavior as in p.1

**Comment by int19h** [comment] 2020-07-08 18:21
Dupe of #133

**Closed** 2020-07-08 18:21 UTC
