### ISSUE TITLE
Unable to set new variables or update exiting variables in debug console

### ISSUE THREAD

**Issue by Weijiang-Xiong** [microsoft/debugpy#1642] opened 2024-07-29 13:33 UTC
Hello this is the problem exactly as mentioned here https://github.com/microsoft/debugpy/issues/1636

I'm also opening an issue under this repo because I don't really know what may be the cause, as the python debugger extension is based on debugpy. 

The problem is, when I pause my program on a line, try to define a new variable or update an existing variable from the debug console (like a=1), I can not see any updates from the variable panel on the left. 

I can not find a simple way to reproduce it, but I think something is wrong after I load some npz files. I'm sorry that I can't include more details as these codes are work-related (maybe they will be open-sourced soon). When the program is paused at line 22, I can set variables normally and see the updates, but right after loading those npz files, I can only set 1 new variable, and from that on the debug console doesn't work. 

<img width="1234" alt="image" src="https://github.com/user-attachments/assets/8dfe6e58-60f0-4c85-a976-1b6b99db4855">

**Comment by rchiodo** [comment] 2024-08-05 16:06
Closing as dupe of #1636

**Closed by rchiodo** 2024-08-05 16:06 UTC
