### ISSUE TITLE
Debugger don't stop at the selected points when GEVENT_SUPPORT=true

### ISSUE THREAD

**Issue by romi477** [microsoft/debugpy#749] opened 2021-10-08 22:28 UTC
## Environment data

Version: 1.61.0
Commit: ee8c7def80afc00dd6e593ef12f37756d8f504ea
Extension version Python: v2021.10.1317843341
Extension version Pylance: v2021.10.0
Date: 2021-10-07T18:11:02.929Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-87-generic

## Actual behavior

Debugger don't stop on the points when GEVENT_SUPPORT=true

My web framework (Odoo) based on Werkzeug wsgi server runs with "workers". It requires GEVENT_SUPPORT=true option 
that vscode hints me. But in this "GEVENT" mode my debugger don't stop at the selected points.

In GEVENT_SUPPORT=false and workers_count=1 everything is OK, debugger stops without any problem.

**Comment by judej** [comment] 2021-10-20 22:26
Thanks for the report, gevent 1.1.2 is 2016. The version that is working without issues is 20.9.0. Are you able to upgrade to that? We are seeing issues with older versions.

**Comment by fabioz** [comment] 2021-12-02 11:41
I can't really reproduce this. 

In a simple example with something as:

```
import gevent

def foo():
    print('Running in foo')
    gevent.sleep(0)
    print('Explicit context switch to foo again')

def bar():
    print('Explicit context to bar')
    gevent.sleep(0)
    print('Implicit context switch back to bar')

lst = [
    gevent.spawn(foo),
    gevent.spawn(bar),
]

gevent.joinall(lst)
```

Adding breakpoints in `bar` and `foo` do stop properly for me even with `gevent==1.1.2`, so, it may be something else... what's the `greenlet` version you have there?

**Comment by fabioz** [comment] 2022-01-28 12:53
I'm closing this since there wasn't additional feedback (besides, there aren't any other reports from gevent users and I couldn't reproduce this).

**Closed by fabioz** 2022-01-28 12:53 UTC
Labels: waiting for response

**Comment by Pexers** [comment] 2023-11-09 17:30
+1
Having the exact same issue when trying to debug Odoo with `GEVENT_SUPPORT=True` env variable. 

Not setting this variable **fixes the debugger**, but the below warning message gets spammed so hard that it almost kills the VSCode terminal!
```sh
It seems that the gevent monkey-patching is being used.
Please set an environment variable with:
GEVENT_SUPPORT=True
```
