### ISSUE TITLE
matplotlib is not responding

### ISSUE THREAD

**Issue by WXZhao7** [microsoft/debugpy#648] opened 2021-06-21 07:22 UTC
## Environment data

-   VS Code version: Code 1.57.1 (507ce72a4466fbb27b715c3722558bb15afa9f48, 2021-06-17T13:26:56.255Z)
-   Extension version : v2021.6.944021595
-   OS and version: Ubuntu 20.04 focal
-   Python version: 3.8.10.final.0
-   Type of virtual environment used: conda 4.10.1
-   Relevant/affected Python packages and their versions: matplotlib                3.4.2            py38h578d9bd_0    conda-forge
-   Relevant/affected Python-related VS Code extensions and their versions: ms-python.python v2021.6.944021595
-   Value of the `python.languageServer` setting: pyLance

## Expected behaviour

![image](https://user-images.githubusercontent.com/56864878/122722288-198be480-d2a4-11eb-89b2-8da9e9db80bb.png)

## Actual behaviour

![image](https://user-images.githubusercontent.com/56864878/122722232-09740500-d2a4-11eb-9065-52689a8f3f85.png)

## Steps to reproduce:
**pyplot.show()**
```python
from matplotlib import pyplot as plt

fig = plt.figure()
ax = fig.subplots(2, 1)
fig.show()
pass
```
**my extension setting and python interpreter**
![image](https://user-images.githubusercontent.com/56864878/122722542-6cfe3280-d2a4-11eb-8f56-791d90952cef.png)

</p>
</details>

**Comment by fabioz** [comment] 2021-06-21 18:03
This is a duplicate of: https://github.com/microsoft/debugpy/issues/603 (this is already fixed in repository but it's still not in a final version).

You can use the `main` branch from this repo to have it working locally until it makes it into a final release.
See: https://github.com/microsoft/debugpy/issues/603#issuecomment-856650706 for instructions.

**Closed by fabioz** 2021-06-21 18:03 UTC
