### ISSUE TITLE
Debugpy jumps out of frame when user set just my code false

### ISSUE THREAD

**Issue by humblemat810** [microsoft/debugpy#1598] opened 2024-06-12 08:42 UTC
For every step, the debugger force jump to the mycode frame, even if the user has disabled just my code. so to follow code flow in other's code, user need to go to step frame and click to deepest frame for EVERY step over, into and out of. This is EXTREMELY serious problem.

Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data 

- debugpy version: 1.8.1 (run `import debugpy; print(debugpy.__version__)` if uncertain)
- OS and version: windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.10.14
- Using VS Code or Visual Studio: VS CODE
- 

## Actual behavior

When developing a backend via jupyter notebook debug, i need to see whats happen in the code, and every line i run, it jumps out of the frame and I need to go to the stack frame to double click on the grey stack to see what happen.
the debugger goes into others people code, after half second or so, it surfaces to the nearest "mycode" frame.

## Expected  behavior

the screen frame should follow the debugger no matter how.

## Steps to reproduce:
open a jupyter notebook, set a debug point to somewhere the jupyter notebook will call
jupyter notebook call that function with debug cell

The same behaviour also happen when using the vscode test feature (the flask icon, not the flask library)

The same behaviour also happen when using debug cell feature in 

Example below when importing a pure python library namedtuple and 
1. step into it. 
2. click to see the frame in namedtuple.__init__()
3. step over
4. it bounce me out of the namedtuple frame !!!! [bug here, should just continue let screen stick to the code]
5. click the namedtuple on stackframe
6. step over
7.  repeating 4 to 6 and bugs can occur again and again
![image](https://github.com/microsoft/debugpy/assets/67593116/3b68918b-c324-49ae-a54f-2e9223f96517)

every time i click into the frame, it bounce out to my code frame.

**Comment by Tremirre** [comment] 2024-06-12 13:01
experiencing the same issue

**Comment by rchiodo** [comment] 2024-06-12 16:47
Thanks for the issue. This is a dupe of https://github.com/microsoft/vscode/issues/214433 which was also discussed here in debugpy:
https://github.com/microsoft/debugpy/issues/1596

**Closed by rchiodo** 2024-06-12 16:47 UTC
