### ISSUE TITLE
Debugger gets stuck with python code

### ISSUE THREAD

**Issue by spin711** [microsoft/debugpy#274] opened 2020-04-20 20:11 UTC
Issue Type: <b>Bug</b>

While debugging a python script, I cannot continue stepping through the code since MSC debugger is not responding anymore, after a certain number of steps.
Also the debug console is impacted, meaning I do not get any requested content of a variable once the above happens.

At the biginning I thought the number of steps until it gets stuck is constant. Meanwhile, I observe that the number of steps I can perform within the same script, is depending also on the starting position in the code as well as well as the number / type of variables in the watch.

I first issued here: https://github.com/microsoft/vscode/issues/95545, but was now guided to issue the bug directly under the python extension.

As advised, I updated to MSC version 1.4.2, but the error still persists. 

So hopefully, someone can help and fix it. Thanks!

VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.3
python|ms-|2020.2.64397
team|ms-|1.161.0

</details>
e written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by int19h** [comment] 2020-06-02 20:02
Thank you! Since this is definitely the version with the fix for the other issue that caused similar symptoms, this must be something else. Can you please add:
```json5
"logToFile": true
```
to your launch.json config, and try to repro it again, then share the logs it'll create? They are placed in the folder where the extension is installed, and have names matching `debugpy*.log`.

**Comment by rickstaa** [comment] 2020-06-07 14:48
@int19h I again tried to debug a python script with the `logToFile` bool enabled. The zip containing the log files can be found here:

[debug_logs.zip](https://github.com/microsoft/debugpy/files/4742262/debug_logs.zip)

While I was debugging, I also noticed the freeze only happens when I try to interact with the variables using the debug console. Secondly, the debugger always gives a `timeout after 1000ms error` when I shut it down during a freeze.

**Comment by int19h** [comment] 2020-06-08 22:58
Looking at the larger log, I'm seeing three expression evaluations being submitted in rapid succession for these expressions:
```
self._compute_reward(obs, done)
test = 1
print(test)
```
Could the first one just be very long-running? It would block basically everything else in the debugger if so. The debug server log seems to indicate that it was still working on that when it got the request to stop debugging.

(Unfortunately, VSCode Debug Console UX for long-running evals is confusing - it shows the prompt for the next expression as soon as it submits the previous one to the debugger; it does *not* for evaluation to complete.)

**Comment by int19h** [comment] 2020-06-16 22:53
If the library you're using requires multiple threads running concurrently to operate - e.g. if any of those `rospy` calls submit some data for processing by a background thread, and then do a blocking wait for said background thread to signal completion - then you might be running into the same problem as #157.

**Comment by rickstaa** [comment] 2020-06-24 08:19
@int19h Thanks for point me to that issue. I will look into it.

**Comment by fabioz** [comment] 2020-07-24 18:04
As it seems that the issue is during the evaluate, so, I think the changes done in: https://github.com/microsoft/debugpy/issues/157 may enable to shed more info in this issue... there still isn't a release with that version, but if you'd like to check it with the master, it'd be nice to know if it does actually improve the situation in your use case.

To use the master do the following:

Clone this repo:

```
git clone https://github.com/microsoft/debugpy.git
cd debugpy
pwd
```

Then, in your launch config add:

`"debugAdapterPath": "<pwd path>/src/debugpy/adapter"` 

and debug your app... if things turn out as I expect, it should print a message to the `Debug Console` with more information. It may also be interesting to set an environment variable such as `"PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT":"true"` in the launch environment so that a thread dump is also provided when a slow evaluation is detected.

**Comment by rickstaa** [comment] 2020-08-06 07:20
@fabioz  Thanks for your response. I will check your it when I am working again on the project discussed in this issue (in about 2 weeks).

**Comment by rickstaa** [comment] 2020-08-20 10:48
@fabloz I was able to perform the steps you proposed and with the new version of `debugpy`, the debugger now crashes instead of freezing. I created a very simple python setup for you in order to validate whether the problem is fixed:

**is_scalar.py module**
```python
import torch
import numpy as np


def is_scalar(obj):
    """Recursive function that checks whether a input

    Args:
        obj (object): Object for which you want to check if it is a scalar.

    Returns:
        boole: Boolean specifying whether the object is a scalar.
    """

    # Check if obj is scalar
    if type(obj) in [int, float]:
        return True
    elif type(obj) == np.ndarray:
        if obj.__len__() > 1:
            return is_scalar(obj)
        else:
            return False
    elif type(obj) == torch.Tensor:
        if obj.__len__() > 1:
            return is_scalar(obj)
        else:
            return False
    elif type(obj) == str:
        return obj.isnumeric()
    else:
        return False
```

**test_debugger.py script**
```python
import numpy as np

from is_scalar import is_scalar

print(is_scalar(1), "True")
print(is_scalar([1]), "False")
print(is_scalar(np.array(2)), "True")  # I'm here
pass
```

# Steps to reproduce (Also see gif)
1. Put both the `test_debugger.py` and `is_scalar.py` script in the same folder.
2. Run the `test_debugger` script while placing a breakpoint on the pass statement.
3. Create a new np array in the debugger console `test_array = np.array(2)`.
4. Try to inspect this new `test_array` and see the debugger hanging in the old debugpy version.
5. In the new pulled version of `debugpy` the debugger crashes while giving the following error:

```bash
IndexError: too many indices for array
```

# Gif

![debugpy_error](https://user-images.githubusercontent.com/17570430/90761150-487fa580-e2e3-11ea-991f-345be5b02306.gif)

**Comment by fabioz** [comment] 2020-08-20 15:45
@rickstaa this is a different issue. I've created https://github.com/microsoft/debugpy/issues/378 to tackle it.

**Comment by int19h** [comment] 2020-09-23 00:21
Closing this one, since there are other issues tracking the remaining problems.

**Closed by int19h** 2020-09-23 00:21 UTC
Labels: bug
