### ISSUE TITLE
ValueError: 'qt' must be one of: ['auto', 'none', 'pyside', 'pyside2', 'pyqt4', 'pyqt5'], I need pyqt6

### ISSUE THREAD

**Issue by houpdelta** [microsoft/debugpy#1414] opened 2023-10-27 17:22 UTC
## Actual behavior

E+00000.109: /handling #1 request "launch" from Adapter/
             Handler 'launch_request' (file 'c:\\Users\\Laurent\\.vscode\\extensions\\ms-python.python-2023.18.0\\pythonFiles\\lib\\python\\debugpy\\launcher/../..\\debugpy\\launcher\\handlers.py', line 14)
             couldn't handle #1 request "launch" from Adapter:
             Invalid message: "qt" must be one of: ['none', 'auto', 'pyside', 'pyside2', 'pyqt4', 'pyqt5']

## Expected  behavior

How to work with pyqt6 ?

## Steps to reproduce:
1.Use pyqt6

**Comment by int19h** [comment] 2023-10-30 18:03
Dupe of https://github.com/microsoft/debugpy/issues/1112

**Closed by int19h** 2023-10-30 18:03 UTC
