### ISSUE TITLE
VS Code debugger doesn't overwrite parameter values when breakpoints present are present

### ISSUE THREAD

**Issue by dan-goodrick** [microsoft/debugpy#477] opened 2020-11-20 19:14 UTC
## Environment data

Python: 3.7.3
VS Code:  1.51.0
Python Extension: v2020.11.371526539
MACOS: 10.15.7 (19H2)

## Behaviour

When I run the debugger if I have a breakpoint at both a return statement inside a function and at the reassignment of the variables the function returns, the new value of the parameters doesn't get assigned.  This only happens in the debugger.  If I run the code with python `python tracker.py`, the return values update.  

Update: The parameter values after the return statement do not get reassigned

Update: I had breakpoints at the function return (inside the function) and at the assignment.  Moving the latter breakpoint resolves the issue.  

## Steps to reproduce:

1.  Place a breakpoint at the return statement inside the function
2. Place a breakpoint where the function returns to.
3. Run debugger (f5)
4. Inspect the values before the return statement (also printed the values in the debug console)
5. Step through the return.  
6. The values returned are different than the values sent back from the function

```
    def update(self, bb):
         ...
          #the values are fine here
*        return update_obj, new_obj, stale_obj

     update_obj, new_obj, stale_obj = trk.update(bb)
     # change bb a bit and call the function again
*    update_obj, new_obj, stale_obj = trk.update(bb)
     #the values are wrong here but moving the second breakpoint down fixes the issue
```

Expected Values:
```update_obj, new_obj, stale_obj
([], [[...], [...], [...]], [0])
special variables
function variables
0:[]
1:[[10, 20, 80, 100], [80, 110, 90, 110], [80, 100, 10, 40]]
2:[0]
len():3
```
Values returned from the function
```
update_obj, new_obj, stale_obj
([], [[...]], [])
special variables
function variables
0:[]
1:[[35, 65, 35, 65]]
2:[]
len():3```

**Comment by int19h** [comment] 2020-11-23 18:28
I think the second breakpoint might be hit after the function returns, but before the destructuring assignment happens. If you hit the breakpoint, and then step until it gets to the next line, do the values update?

**Comment by fabioz** [comment] 2020-11-26 18:42
@dan-goodrick Can you provide a minimal working sample where this issue can be reproduced?

**Comment by fabioz** [comment] 2020-12-10 12:39
Closing since additional feedback wasn't provided. Please reopen if you're able to provide the additional information requested.

**Closed by fabioz** 2020-12-10 12:39 UTC
