### ISSUE TITLE
Debug output truncates when running from Windows but not outside of debug

### ISSUE THREAD

**Issue by brentashley** [microsoft/debugpy#299] opened 2020-06-17 17:42 UTC
Similar to https://github.com/microsoft/ptvsd/issues/975

## Environment data

-   VS Code version: 1.46.0
-   Extension version (available under the Extensions sidebar): v2020.6.88468
-   OS and version: Windows 10 Pro 2004
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: debugpy/wheel
-   Relevant/affected Python-related VS Code extensions and their versions: 
-   Jedi or Language Server? (i.e. what is `"python.jediEnabled"` set to; more info microsoft/vscode-python#3977): not found
-   Value of the `python.languageServer` setting: Jedi

## Expected behaviour

Display all output on console.

## Actual behaviour

Output truncated.

## Steps to reproduce:

__test.py__: print 20k output as 200 lines of 99char+lf, with byte count (at EOL) displayed at start of line

    s = ''
    for i in range(1,201):
        s += f"{str(i*100).zfill(10)}{'x' * 89}\n"
    print(s)

## Logs

<details>

<summary>
1. run from debugger with F5 (incomplete output)
</summary>

     cd 'c:\Users\brent.ashley\work'; &  'C:\Users\brent.ashley\AppData\Local\Programs\Python\Python38-32\python.exe'  'c:\Users\brent.ashley\.vscode\extensions\ms-python.python-2020.6.88468\pythonFiles\lib\python\debugpy\launcher' '61385' '--'  'c:\Users\brent.ashley\work\test.py'

    0000000100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  
    ....more lines...
    0000010000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
</details>

<details>
<summary>
2. run without debugger (complete output):
</summary>

    C:\users\brent.ashley\AppData\Local\Programs\Python\Python38-32\python.exe test.py

    0000000100xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  
    ....more lines...
    0000020000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 

</details>

## Extra Note:

When I run VSCode from Unbuntu-1804 on WSL1 on the same machine against the same source files, I do not get this behavior. When that runs in the debugger, it uses the "debugpy/no-wheels" launcher instead of the "debugpy/wheels" code used when VSCode launched in Windows.

**Comment by int19h** [comment] 2020-06-17 19:32
What are your settings for "console" and "redirectOutput" in launch.json?

**Comment by brentashley** [comment] 2020-06-17 20:18
This behaviour happens with no launch.json file in the environment.

The console is the "Python Debug Console" which is a powershell instance.

**Comment by brentashley** [comment] 2020-06-17 20:20
When I run the script with Python manually, I am doing that at the same terminal instance of "Python Debug Console" that was launched by [F5]

**Comment by int19h** [comment] 2020-06-25 18:20
@fabioz, I did the preliminary investigation, and this seems to be pydevd stdio redirection bug. The problem is that on Python 3, `buffer.write()` can be partial - and it is on large values! - so `IORedirector` needs to look at the return value, and spin in a loop as needed to make sure it propagates the whole string. 

(Note that on Python 2, `write()` can never be partial, and always returns `None`.)

**Comment by fabioz** [comment] 2020-10-09 17:59
I'll start to take a look at this.

**Comment by fabioz** [comment] 2020-10-09 18:40
I haven't been able to investigate much, but in this case it doesn't seem like the IORedirector is installed at all, and even running without debugging (i.e.: still using debugpy, but not pydevd) the output gets truncated (i.e.: in the case below the last line should be 30000 -- note that python says it wrote all those contents in the return of the `write` and there's no redirection setup).

![image](https://user-images.githubusercontent.com/117621/95619405-f9353600-0a44-11eb-84ed-84350931c46c.png)

In fact, as it's running in the `integratedTerminal` in that case, there really should be no redirection whatsoever by the debugger (which makes this issue pretty strange... it can potentially be something setting up the subprocess launch, but further investigation is needed).

**Comment by fabioz** [comment] 2020-10-09 19:05
Some more findings: 

Although writing the `str` reports it wrote everything, writing the `bytes` to the buffer does indeed say that it wrote only a part of the string. 

i.e.:

![image](https://user-images.githubusercontent.com/117621/95622024-110eb900-0a49-11eb-8c12-77ebbc7b8845.png)

So, it may be that we're triggering some issue on CPython itself here...

**Comment by fabioz** [comment] 2020-10-15 13:33
OK, I've investigated more and this is really an issue in CPython itself.

I created https://bugs.python.org/issue42044 to track it.

The workaround is setting the environment as:

```
"env": {
    "PYTHONUNBUFFERED": "0"
}
```

@int19h @karthiknadig for debugpy itself I don't think there's much more to be done, so, I'm closing this issue. In VSCode itself, when dealing with a real terminal (and not with the console output), I think it could launch python by default as buffered instead of unbuffered (I think that the unbuffered mode is probably only needed when running with output to the internal console).

**Closed by fabioz** 2020-10-15 13:33 UTC
Labels: bug

**Comment by Gordonguy** [comment] 2021-05-19 20:29
This workaround worked for a while then stopped working.  Now print(os.environ['PYTHONUNBUFFERED']) always returns 1 instead of 0.  Setting it in .env has no effect.  It might have stopped working when IPython was installed, but not sure.

Issue only happens with the "console": "internalConsole" debug configuration in launch.json

Issue does not happen with "console": "integratedTerminal" debug configuration.  Also does not happen in VS Code's interactive window (IPython).

**Comment by fabioz** [comment] 2021-06-04 18:46
I was taking a look at the code related to this. From what I can see, if you're running in the terminal and you don't have `redirectOutput` set, and you set `PYTHONUNBUFFERED=0`, things should work. 

The only case where `PYTHONUNBUFFERED` is forced to `1` is if you're using the internal console or are redirecting output (the related code is: https://github.com/microsoft/debugpy/blob/v1.3.0/src/debugpy/launcher/handlers.py#L114).

Unfortunately, in this case there's no way around it because if python is buffered in this case the output isn't shown at all (unless you explicitly flush or the buffer actually becomes full, which is not the same behavior when you have an actual terminal).

So, unfortunately, there's not much to do in the `debugpy` side. The real issue must be fixed on CPython.
