### ISSUE TITLE
VS Code stays as if still being debugged in embedded Python

### ISSUE THREAD

**Issue by dalmago** [microsoft/debugpy#337] opened 2020-07-17 16:40 UTC
## Environment data

- debugpy version: 1.0.0b12
- OS and version: Windows 10 x64
- Python version: 3.6.8 x64
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When running embedded Python, VS Code stays as if it was at a breakpoint even though the Python code already finished running (the execution is back at the C code). VS Code shows the yellow arrow, yellow line highlight and the debugging controls pop up (Continue, Step Over, Step Into...). Of course none of the commands have any action, because the Python code is no longer being executed.
The same didn't happen when using ptvsd==4.3.2

## Expected  behavior

When the execution goes back to the C code, VS Code should stays as if the code was running, not paused.

## Steps to reproduce:
1. Remote attach the debugger in an embedded application
2. Have a breakpoint at the end of the Python code
3. When the breakpoint is reached, press Continue (the code will keep running but VS Code stays as if it was paused)

**Comment by fabioz** [comment] 2020-07-23 13:48
Can you give some more information?

- can give more details on how are you embedding Python in this case? 

- when you say that it finishes the python code, did your process also exit or just the python code?

- can you provide a screenshot showing VSCode when that happens?

- can you provide the logging for this? (you can set a `DEBUGPY_LOG_DIR` environment variable pointing to a directory -- note that it may create multiple log files, please provide all of those)

**Comment by int19h** [comment] 2020-07-23 17:14
In the attach case, we don't really know when Python code has stopped running, since the host can just start executing more code in the same Python interpreter instance. So the toolbar is supposed to remain there, in general; the bug is that it remains in pause mode specifically.

What I suspect is happening here is that the host tears down the interpreter in such a way that precludes pydevd from sending a response to the "continue" request, or from gracefully closing the socket from its end. Thus the adapter and the client are still waiting for response, and there's no indication that it won't come. The adapter won't even be able to tell that the socket is gone, until it tries sending something else - but it won't try until it receives that "continue" response.

**Comment by fabioz** [comment] 2020-07-24 12:00
In an example here when I run Python (without embedding) and do a remote attach it seems to exit properly...

From what I remember, `pydevd` creates some daemon threads and one non-daemon thread (`CheckAliveThread`). When the non-daemon thread sees that all daemon threads exit it should send the exit, so, I'm still unsure on what's happening in this case (waiting for the logs to give more info).

**Comment by dalmago** [comment] 2020-07-24 21:24
> * can give more details on how are you embedding Python in this case?

I have C++ code using the Python interpreter through the C API. I will try to elaborate some sample code.

> * when you say that it finishes the python code, did your process also exit or just the python code?

Just the Python code. When the whole process exits, the debugger finishes normally.

> * can you provide the logging for this? (you can set a `DEBUGPY_LOG_DIR` environment variable pointing to a directory -- note that it may create multiple log files, please provide all of those)

Will do.

> * can you provide a screenshot showing VSCode when that happens?
![snapshot](https://user-images.githubusercontent.com/4973496/88435244-312ec480-cdd8-11ea-8987-b5f53a3ac4af.jpg)

> * [...] the toolbar is supposed to remain there, in general; the bug is that it remains in pause mode specifically.

Yes, exactly. The toolbar being there is ok, since the Python code could execute again.

**Comment by dalmago** [comment] 2020-07-24 22:52
I just wrote [this really simple CPP application](https://gist.github.com/dalmago/a9cca0071b9456658ab715daa89cb2af) that loads and runs [this Python file](https://gist.github.com/dalmago/85461b066982814fd235a2a8b628fe75).
The implementation could be improved in some ways, but this is really close to my real application. The path to the Python Interpreter is hardcoded in the CPP file.

I can post the .exe and .vcxproj files if needed.

I also noticed the following warning when the debugger attaches:
`C:\python36\lib\json\encoder.py:224: ResourceWarning: unclosed <socket.socket fd=928, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 60216)>
  _repr=float.__repr__, _inf=INFINITY, _neginf=-INFINITY):`

**Comment by dalmago** [comment] 2020-07-28 11:58
Here are the logs I promised

[debugpy_log.zip](https://github.com/microsoft/debugpy/files/4988125/debugpy_log.zip)

**Comment by fabioz** [comment] 2021-01-14 16:19
I can't really reproduce this. I've tried many things but I never got to the point where the IDE says it's paused when the threads are actually running.

I took a look at the logs provided and in `debugpy.adapter-16544.log` I can see the message:

```
             Client[1] <-- {
                 "seq": 33,
                 "type": "event",
                 "event": "continued",
                 "body": {
                     "threadId": 1,
                     "allThreadsContinued": true
                 }
             }
```

Before the message related to the `The IDE will seem to be paused` print.

So, the debugger seems to be properly sending the event saying that the threads are running even there (in which case I think that either this particular log wasn't really from a case with a problem or the issue was in the VSCode side...).

@dalmago can you still reproduce this with the latest VSCode/debugpy version?

Note: the project I'm using (with a .bat to compile it -- with some hard-coded paths) is at: [sample.zip](https://github.com/microsoft/debugpy/files/5815618/sample.zip)

**Comment by fabioz** [comment] 2021-01-21 17:16
Closing since there was no answer. Please reopen if you're interested in investigating it.

**Closed by fabioz** 2021-01-21 17:16 UTC
Labels: bug

**Comment by dalmago** [comment] 2021-02-03 21:01
There is a timing element to reproduce the problem. I still could not write a code that shows the bug persistently.

Here is a gif showing what happens. I am running exactly the same code you attached above, except by the hard-coded paths, the cpp time delay (reduced to 5) and a print statement in the Python code.

![example](https://user-images.githubusercontent.com/4973496/106808352-0a83fd00-6649-11eb-91b0-65c7711d80f5.gif)

Logs:
[logs.zip](https://github.com/microsoft/debugpy/files/5921409/logs.zip)

**Comment by dalmago** [comment] 2021-02-03 21:08
On this log it is clear the 5 seconds delay where nothing happens. Should the`Server[1] -->  ... "event": "continued"` have been logged before the 5 seconds delay?
```
D+00007.000: Client[1] --> {
                 "seq": 25,
                 "type": "request",
                 "command": "continue",
                 "arguments": {
                     "threadId": 1
                 }
             }

D+00007.000: /handling #25 request "continue" from Client[1]/
             Server[1] <-- {
                 "seq": 30,
                 "type": "request",
                 "command": "continue",
                 "arguments": {
                     "threadId": "*"
                 }
             }

D+00012.031: Server[1] --> {
                 "pydevd_cmd_id": 158,
                 "seq": 100,
                 "type": "event",
                 "event": "continued",
                 "body": {
                     "threadId": 1,
                     "allThreadsContinued": true
                 }
             }

D+00012.047: Server[1] --> {
                 "pydevd_cmd_id": 502,
                 "seq": 102,
                 "type": "response",
                 "request_seq": 30,
                 "success": true,
                 "command": "continue",
                 "body": {
                     "allThreadsContinued": true
                 }
             }

D+00012.047: /handling #25 request "continue" from Client[1]/
             Client[1] <-- {
                 "seq": 49,
                 "type": "response",
                 "request_seq": 25,
                 "success": true,
                 "command": "continue",
                 "body": {
                     "allThreadsContinued": true
                 }
             }
```
