### ISSUE TITLE
Modules with two leading slashes can't be mapped properly in VS Code debugger

### ISSUE THREAD

**Issue by OEP** [microsoft/debugpy#1061] opened 2022-09-22 03:58 UTC
Hi, this is a follow-up to a discussion: https://github.com/microsoft/vscode-python/discussions/19835

## Environment data

- debugpy version: 1.6.3
- OS and version: CentOS 7.9, macOS 11.6.2 (Big Sur)
- Python version : Tested on 3.9 (macOS), 3.7 and 3.6 (CentOS)
- Using VS Code or Visual Studio: VS Code

## Actual behavior

In VS Code, breakpoint is hit, but path-mapping does not work with an error in the editor pane.

> The editor could not be opened because the file was not found.

Creating the file tries to `mkdir /vscode-path` and fails.

In a more complex example that I couldn't find a MWE for, the Call Stack pane in VS Code says:

```
[UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
```

## Expected  behavior

Breakpoint is hit and the path-mapping works.

## Steps to reproduce:

Create a file like the following:

```
$ cat /tmp/vscode-path/vscode_blah.py 
import sys
import pprint
pprint.pprint(sys.path)

import debugpy
debugpy.listen(5678)
print("WAIT")
debugpy.wait_for_client()

print("HEY")
```

Create a standard "remote attach" debug configuration.

```
{
        "host": "localhost",
        "name": "Remote Attach",
        "port": 5678,
        "request": "attach",
        "type": "python"
}
```

In the VS Code editor, set a breakpoint on the final `print()`.

Try to import it via a PYTHONPATH with a leading double slash.

```
$ PYTHONPATH=//tmp/vscode-path python3 -c "import vscode_blah"
```

Attach via the debugger.

**Comment by fabioz** [comment] 2022-09-22 14:50
Actually, `debugpy` itself does everything properly here, it's VSCode itself that doesn't support it.

i.e.: the stack frame message is correct:

`{"type": "response", "request_seq": 19, "success": true, "command": "stackTrace", "body": {"stackFrames": [{"id": 2, "name": "<module>", "line": 15, "column": 1, "source": {"path": "//tmp/vscode-path/vscode_blah.py", "sourceReference": 1}}, {"id": 3, "name": "<module>", "line": 1, "column": 1, "source": {"path": "<string>", "sourceReference": 2}}], "totalFrames": 2}, "seq": 48, "pydevd_cmd_id": 502}`

So I'm closing this here because it can't be fixed by `debugpy` as the issue is in the VSCode client side.

@OEP can you report this to https://github.com/microsoft/vscode/issues? 

Screenshot showing error:

![image](https://user-images.githubusercontent.com/117621/191779684-51ab8c6f-82ea-49b1-937b-121aaffa9a6f.png)

**Closed by fabioz** 2022-09-22 14:50 UTC
