### ISSUE TITLE
Can't combine Debugpy and FLASK_ENV=Development

### ISSUE THREAD

**Issue by cfis** [microsoft/debugpy#808] opened 2021-12-21 00:02 UTC
When working on #807 I noticed another issue (same setup as in #807).

This is simple flask app with this starting code:

```
import debugpy
debugpy.listen(('127.0.0.1', 5678))
logging.getLogger('werkzeug').setLevel(logging.WARN)
app = flask.Flask("tilt-avatars-api")
```

Next, the environmental variable FLASK_ENV is set to development.

When the /ready endpoint is called by a Kubernetes liveness probe:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 354, in __call__
    self._flush_bg_loading_exception()
  File "/usr/local/lib/python3.9/site-packages/flask/cli.py", line 342, in _flush_bg_loading_exception
    raise exc_info
TypeError: exceptions must derive from BaseException
10.85.0.1 - - [20/Dec/2021 23:58:48] "GET /ready HTTP/1.1" 500 -`

If debugpy is not setup (as in don't call listen) it works fine. If FLASK_ENV is not set to development it works fine. So there seems to be some sort of interaction between debugpy and Flask.

**Comment by int19h** [comment] 2022-01-06 22:45
Flask has its own built-in debugger, which IIRC is enabled by default in the dev environment. If you try to use two debuggers at once, they're going to fight over `sys.settrace` hook with basically unpredictable results - I suspect this is what's happening here. 

This can be controlled by setting `FLASK_DEBUG` to 0 - can you try that and see if it helps?

**Comment by cfis** [comment] 2022-01-06 22:51
Ah - thanks for the tip.

**Comment by fabioz** [comment] 2022-01-27 18:33
Closing as apparently setting `FLASK_DEBUG=0` is the fix (feel free to comment if this isn't it or if you think something else should be done here).

**Closed by fabioz** 2022-01-27 18:33 UTC

**Comment by jaredculp** [comment] 2022-03-06 21:42
Is there a way to have flask debug's live reload work with debugpy?

**Comment by jaredculp** [comment] 2022-03-09 02:25
@int19h I am trying to attach to a docker container running my flask app. Repo here: https://github.com/jaredculp/docker-flask-debugpy

If I set `FLASK_DEBUG=1` I get live reload, but debugpy can't attach. If I set `FLASK_DEBUG=0`, I can attach a debugger but I lose live reload.

**Comment by int19h** [comment] 2022-03-09 02:31
You need to set `FLASK_ENV` instead per the config above.

**Comment by jaredculp** [comment] 2022-03-09 02:41
It is set to `development`: https://github.com/jaredculp/docker-flask-debugpy/blob/master/Dockerfile#L4

**Comment by int19h** [comment] 2022-03-09 02:52
The problem is that you're also setting `FLASK_DEBUG=0`, which immediately disables auto-reload. Try using `--no-debugger` as a command line argument to` flask run` instead:

https://flask.palletsprojects.com/en/2.0.x/debugging/#external-debuggers

**Comment by jaredculp** [comment] 2022-03-09 02:57
That works combined with using a volume! Thanks!
