### ISSUE TITLE
stuck on input in integratedTerminal

### ISSUE THREAD

**Issue by mroliva** [microsoft/debugpy#365] opened 2020-08-14 00:57 UTC
brand new peppermintOS (debian based) install.
vs code, python3-pip etc, python extension.
select interpreter as python 3.6.9 (default on my distro)
select linter as pylint

created a directory on homedir named python.
made that directory a workspace.
```
new file test.py
print('a')
name=input('abc: ')
print(name)
```
click run > run without debugging.
type anything on input on terminal and hit enter.
my code doesn't go past that. the second print(name) never happens.

althought if i use the green arrow on top-right, run python file in terminal, it works ok, except by the fact that the cursor stays on the editor instead of switching to the terminal, so you have to click on run then click on terminal everytime you need to run this way.

today earlier i were trying something until i forgot and made an unbreakable while loop.
computer got too slow and i held the power button to shut it down.
when it got back, i kept my tests and everything was working pristine, and then after one regular "run without debug", the input didn't work anymore. honestly i didn't notice if something updated at sometime, but i don't think so.
tried every-single-thing.
purged the vscode on apt, deleted all .vscode i could find, deleted the /usr/share/code with everything inside, reinstalled more than 5 times and it was still stopping on input.
decided to go further as this old laptop is for this only and reinstalled the whole OS, erasing the disk.
go back to line 1 of this text.

**Comment by karthiknadig** [comment] 2020-08-17 16:34
@mroliva @zlcnup Try adding `"redirectOutput": true` to your launch.json debug configuration, see https://github.com/microsoft/debugpy/issues/296#issuecomment-660285084. This was changed recently to allow better control of IO redirection.

**Comment by fabioz** [comment] 2020-08-17 20:20
Closing as a duplicate of https://github.com/microsoft/debugpy/issues/370

**Closed by fabioz** 2020-08-17 20:20 UTC
