### ISSUE TITLE
listen creates a new process - and this may not be python.exe

### ISSUE THREAD

**Issue by daltairwalter** [microsoft/debugpy#301] opened 2020-06-18 16:13 UTC
In embedded applications, the application may be relaunched repeatedly in an endless loop if it tries to call listen during it's startup procedure.  This happens because listen is for some reason trying to launch the python interpreter and thinks that this can be found at sys.executable.

**Comment by int19h** [comment] 2020-06-18 16:57
Duplicate of https://github.com/microsoft/debugpy/issues/262

**Closed by int19h** 2020-06-18 16:57 UTC
