### ISSUE TITLE
Attach to local process not fully working for Python 3.10

### ISSUE THREAD

**Issue by tonyroberts** [microsoft/debugpy#1035] opened 2022-08-26 16:19 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Attaching to a local running Python 3.10 process should work when the project interpreter is also set to Python 3.10.

Attempting to do so doesn't appear to do anything and there are no errors in the output, and no errors in the Python process that should be attached to.

Using Python 3.9 as the project interpreter this does work correctly and attaching to a Python 3.10 process works that way.

## Steps to reproduce:

Use this launch configuration:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "justMyCode": true
        }
    ]
}
```

Run a Python script using a Python 3.10 environment. This is the one I've been using to test:

```
import time
import os

while True:
    print(f"PID: {os.getpid()}")
    time.sleep(10)
```

Set Python 3.10 as your project interpreter and try to attach to this Python process.

Switch the project interpreter to Python 3.9 and it will work (even though the Python process to be debugged is still using Python 3.10), but it should also work with Python 3.10 as the project interpreter.

This works:
![image](https://user-images.githubusercontent.com/3200395/186949142-aa7f6d55-892b-45b6-b972-f4d7df34da7e.png)

This doesn't:
![image](https://user-images.githubusercontent.com/3200395/186949054-fcdf37b7-28b9-4949-b469-8a5dda0e72a3.png)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
> wmic process get Name,ProcessId,CommandLine /FORMAT:list
DAP Server launched with command: C:\Users\tony\miniconda3\envs\py310\python.exe c:\Users\tony\.vscode\extensions\ms-python.python-2022.12.1\pythonFiles\lib\python\debugpy\adapter
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.12.1
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900T CPU @ 2.10GHz (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.26GB free)|
|Process Argv|--crash-reporter-id 866c0aa5-cce0-4e50-9e6a-ffe06fabf53a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by fabioz** [comment] 2022-09-01 12:24
@karthiknadig I think this problem isn't in the attach on the `debugpy` side, rather, Python 3.10 on conda has a requirement of having the environment activated prior to running python because the python executable has a dependency on the zlib.dll (which is not right next to it).

-- at least if I run it directly in my machine I get an exception as:

![image](https://user-images.githubusercontent.com/117621/187911073-87caa11a-c6c2-4898-917f-e9838b6e3306.png)

So, the fix for this is that `PATH` must be set properly by `vscode-python` when calling `python` 3.10 so that the attach works (as it is `vscode-python` doesn't even seem to start the attach script and I believe this is due to that).

**Comment by fabioz** [comment] 2022-09-01 12:28
Note: I believe that this may be the cause for reports such as https://github.com/microsoft/vscode/issues/159657 too (if the `PATH` isn't controlled properly prior to launching things go haywire).

**Comment by tonyroberts** [comment] 2022-09-01 14:39
> @karthiknadig I think this problem isn't in the attach on the `debugpy` side, rather, Python 3.10 on conda has a requirement of having the environment activated prior to running python because the python executable has a dependency on the zlib.dll (which is not right next to it).

This makes sense, and explains why it works when the project interpreter is a different Python environment. Debugging Python 3.10 with debugpy works fine, just trying to launch it using Python 3.10 from VS Code is the problem it seems.

**Comment by karthiknadig** [comment] 2022-09-01 17:44
This is actually an issue with conda itself. See here https://github.com/conda/conda/issues/11072 I had raised this with conda. Looks like it might have resurfaced.

A workaround is to navigate to your project in an external terminal, activate the conda environment that terminal, and launch VS Code from that terminal.

**Comment by fabioz** [comment] 2022-09-01 17:51
Humm, for my case it could be that it's just an old env I have lying around. I'll try to create a new conda env with Python 3.10 and see if that works for me.

**Comment by fabioz** [comment] 2022-09-01 18:15
Upgrading that old conda environment to use the latest version does fix it for me (so, closing issue).

**Closed by fabioz** 2022-09-01 18:15 UTC
