### ISSUE TITLE
Assertion failed: (this->tracefunc.REFCNT() == old_refs + 1), function set_tracefunc, file greenlet_thread_state.hpp, line 314.

### ISSUE THREAD

**Issue by cduran** [microsoft/debugpy#1127] opened 2022-11-16 13:36 UTC
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Actual behavior
Assertion failed: (this->tracefunc.REFCNT() == old_refs + 1), function set_tracefunc, file greenlet_thread_state.hpp, line 314.

Expected behavior
Ability to run the test from start to finish

## Steps to reproduce:

Steps to reproduce:
This happens also using python:
3.10.8
3.9.15

Have a project that works and uses with gevent
And then just star a debug session with "gevent": true in the launch.json

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• autopep8Args: "<placeholder>"
• provider: "black"
• blackArgs: "<placeholder>"

```

</p>
</details>

Extension version: 2022.18.2
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 15, 10|
|Memory (System)|32.00GB (3.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fabioz** [comment] 2022-11-16 18:02
Closing this one as a duplicate of: https://github.com/microsoft/debugpy/issues/1126 (apparently a newer version of greenlet is making the debugger misbehave -- the fix right now is using greenlet 1.1.3).

**Closed by fabioz** 2022-11-16 18:02 UTC
