### ISSUE TITLE
Python Debugger not showing NumPy array values after update - NOT resolved

### ISSUE THREAD

**Issue by jav-ed** [microsoft/debugpy#1770] opened 2024-01-24 11:08 UTC
[https://github.com/microsoft/vscode-python-debugger/issues/135](https://github.com/microsoft/vscode-python-debugger/issues/135) was closed. However, the issue still remains, see:

![0](https://github.com/microsoft/debugpy/assets/47569896/bae86126-5d06-4d7a-b8c5-8c4f68a11212)
![1](https://github.com/microsoft/debugpy/assets/47569896/a140c5b2-3104-416a-9181-7d1819515373)

- VSCode Version:
Version: 1.85.2
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:19.222Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 5.14.21-150500.55.39-default

**Comment by rchiodo** [comment] 2024-12-11 17:10
This should have been fixed. It's a dupe of this:
https://github.com/microsoft/debugpy/issues/1408

**Closed by rchiodo** 2024-12-11 17:10 UTC
Labels: needs repro
