### ISSUE TITLE
debugpy breaks running pip with subprocess

### ISSUE THREAD

**Issue by alexyao2015** [microsoft/debugpy#864] opened 2022-03-04 22:00 UTC
## Environment data

- debugpy version: 1.5.1
- OS and version: mcr.microsoft.com/vscode/devcontainers/python:0-3.9
- Python version (& distribution if applicable, e.g. Anaconda): 3.9
- Using VS Code or Visual Studio: VS Code

## Actual behavior
```
root ➜ /workspaces/home-assistant (fix-unavailable ✗) $  cd /workspaces/home-assistant ; /usr/bin/env /usr/local/bin/python /root/.
vscode-server/extensions/ms-python.python-2022.2.1924087327/pythonFiles/lib/python/debugpy/launcher 45371 -- /workspaces/home-assis
tant/install-test.py 
b"ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/tmpv4lm4zk5/output.json'\n\nWARNING: You are using pip version 20.2.4; however, version 22.0.3 is available.\nYou should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n"
b"Collecting git+https://gitlab.com/alexyao2015/python-yeelight@master#yeelight==0.7.9\n  Cloning https://gitlab.com/alexyao2015/python-yeelight (to revision master) to /tmp/pip-req-build-d9xsdiyt\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n"
```
## Expected  behavior
```
root ➜ /workspaces/home-assistant (fix-unavailable ✗) $ python install-test.py
b"WARNING: You are using pip version 20.2.4; however, version 22.0.3 is available.\nYou should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n"
b"Collecting git+https://gitlab.com/alexyao2015/python-yeelight@master#yeelight==0.7.9\n  Cloning https://gitlab.com/alexyao2015/python-yeelight (to revision master) to /tmp/pip-req-build-knpobukl\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Installing backend dependencies: started\n  Installing backend dependencies: finished with status 'done'\n    Preparing wheel metadata: started\n    Preparing wheel metadata: finished with status 'done'\nRequirement already satisfied: ifaddr in /usr/local/lib/python3.9/site-packages (from yeelight==0.7.8) (0.1.7)\nRequirement already satisfied: future in /usr/local/lib/python3.9/site-packages (from yeelight==0.7.8) (0.18.2)\nBuilding wheels for collected packages: yeelight\n  Building wheel for yeelight (PEP 517): started\n  Building wheel for yeelight (PEP 517): finished with status 'done'\n  Created wheel for yeelight: filename=yeelight-0.7.8-py3-none-any.whl size=35748 sha256=45adbf84ba5110d9e7f8f179b8c8e89fc9e4ed97b48674b190f6308b007e71ff\n  Stored in directory: /tmp/pip-ephem-wheel-cache-ib_84gum/wheels/82/a3/02/f04bc80bb600ad2c6ea8cbb1101d311f41e7a38ae6e262ea4e\nSuccessfully built yeelight\nInstalling collected packages: yeelight\nSuccessfully installed yeelight-0.7.8\n"
```
## Steps to reproduce:
1. Start devcontainer
2. Debug sample code and observe error.
3. Directly run code in shell and observe success.

This same behavior also occurs with `pydevd`, so I'm not sure if this is a general debugger issue or if something is wrong with pip's implementation.

Sample code:

```python
from subprocess import PIPE, Popen
import sys
import os

# this only occurs when using git installed packages
# package = "yeelight" works just fine
package = "git+https://gitlab.com/alexyao2015/python-yeelight@master#yeelight==0.7.9"
args = [sys.executable, "-m", "pip", "install", package]

with Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE) as process:
    stdout, stderr = process.communicate()
    print(stderr)
    print(stdout)
```

Related: https://github.com/home-assistant/core/issues/64950

**Comment by int19h** [comment] 2022-03-18 01:53
This is a dupe of https://github.com/microsoft/debugpy/issues/154 - `pip` subprocess is run as a module, and that module flag is then improperly translated to the helper `in_process.py` subprocess script used internally.

**Closed by int19h** 2022-03-18 01:53 UTC
