### ISSUE TITLE
Can't stop when attaching to debug

### ISSUE THREAD

**Issue by Chichilele** [microsoft/debugpy#666] opened 2021-07-19 12:48 UTC
## Environment data

- debugpy version: 1.3.0
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.9.5 
- Using VS Code or Visual Studio: VS Code 1.57.1

## Actual behavior

Attaching to a flask app running in a docker-compose deployment works fine. However, most actions (disconnect, pause, restart) don't work. Even disconnecting doesn't close the debugging mode in VS code and any other action. 

## Expected  behavior

Enable pause, restart and properly close the debug view when on stop button.

## Steps to reproduce:
1. Attach to a debug session
2. Try pausing restarting or stopping.

Please let me know if this would be better directly in VS Code repo

**Comment by judej** [comment] 2021-08-02 19:23
Thanks for the report. Could you please upgrade to debugpy version: 1.4.1 and see if the problem still reproduces? Thanks.

**Comment by int19h** [comment] 2021-09-03 20:16
In multiprocess scenarios, you can issue those commands on specific processes in the Threads window. Does it make any difference if you send them to the root process?

**Comment by rodrifmed** [comment] 2021-09-03 20:31
Hi @int19h, In my case  I'm using gunicorn with multiple workers, the only way that I find to call the listener was on the gunicorn startup, so far is working really fine, debugpy can find all workers under the main worker. After you click disconnect for example, the process and sub processes disappear, but the debug buttons stay there.

On debug console window, the processes still there.

From outuput window: Log(window)

```
[renderer1] [error] cannot find session: Error: cannot find session
	at b.getSession (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:37097)
	at b.$acceptDebugSessionTerminated (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:34016)
	at h._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12819)
	at h._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:12503)
	at h._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:11159)
	at h._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9943)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8039
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15825)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:30060
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)
	at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15825)
	at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21091)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17969
	at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1712)
	at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13186)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12534
	at Socket.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:13218)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)

```

**Comment by int19h** [comment] 2021-09-03 21:26
Looks like a dupe of https://github.com/microsoft/vscode/issues/130941

**Closed by int19h** 2021-09-03 21:26 UTC
Labels: waiting for response
