### ISSUE TITLE
Can not run file in path that contains  "!!" 

### ISSUE THREAD

**Issue by gohandi** [microsoft/debugpy#660] opened 2021-07-09 14:46 UTC
## Environment data

-   VS Code version: 1.57.1
-   Extension version: v2021.6.944021595
-   OS and version: Windows 10 2020H2 19042.1083
-   Python version: 3.9.6
-   Type of virtual environment used: N/A
## Expected behaviour

Run without debuging lunch py file
```
userName@pcName MINGW64 /d/projekty-rr/python-bombom
$  cd d:\\projekty-rr\\python-bombom ; /usr/bin/env C:\\Python39\\python.exe c:\\Users\\userName\\.vscode\\extensions\\ms-python.python-2021.6.944021595\\pythonFiles\\lib\\pyt
hon\\debugpy\\launcher 65287 -- d:\\projekty-rr\\python-bombom\\src\\main.py 
hello ello
```

## Actual behaviour

File fails to run due to "[Errno 2] No such file or directory"
```
userName@pcName MINGW64 /d/!!.projekty-rr/python-bombom
$  /usr/bin/env C:\\Python39\\python.exe c:\\Users\\userName\\.vscode\\extensions\\ms-python.python-2021.6.944021595\\pythonFiles\\lib\\python\\debugpy\\launcher 65273 -- d:\\
!!.projekty-rr\\python-bombom\\src\\main.py
 /usr/bin/env C:\\Python39\\python.exe c:\\Users\\userName\\.vscode\\extensions\\ms-python.python-2021.6.944021595\\pythonFiles\\lib\\python\\debugpy\\launcher 65273 -- d:\\exit.projekty-rr\\python-bombom\\src\\main.py
C:\Python39\python.exe: can't open file 'd:\exit.projekty-rr\python-bombom\src\main.py': [Errno 2] No such file or directory
```

## Steps to reproduce:

1. Create path that contains "!!" i.e. C:\\\!\!.projects\python-project\src
2. Create py file under created path ie. main.py
3. Create default launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```
4. run without debuging created file in vsc

## Details

Lunching script pass path `d:\\exit.projekty-rr\\python-bombom\\src\\main.py` instead `d:\\!!.projekty-rr\\python-bombom\\src\\main.py`  to `python.exe`

**Comment by fabioz** [comment] 2021-07-16 14:26
I can't reproduce this (running with a folder with `!!` does work properly on Windows for me).

My guess is is that it's something related to your shell configuration. Can you give some more details on how exactly is your shell configured? I think somewhere your shell is translating the `!!` to `exit`.

Also, your calls seems to mention `MINGW64` and `/usr/bin/env`... can you give more details on that? Are you in a unix environment running on Windows?

**Comment by fabioz** [comment] 2021-07-29 18:45
Closing as no further feedback was given. Please reopen if/when you're able to provide more info.

**Closed by fabioz** 2021-07-29 18:45 UTC

**Comment by gohandi** [comment] 2021-08-03 13:11
Sorry for late replay.
Indeed this was problem with configuration MINGW64. I found that is `!!` is part of bash expand history feature. It is translated on the fly to last executed command. In my case it was "exit".
It can be turned of using: `set +o histexpand` and turn on back by: `set -o histexpand`
Useful links:
[In bash, how do I escape an exclamation mark?](https://superuser.com/questions/133780/in-bash-how-do-i-escape-an-exclamation-mark)
[Bash Manual: 9.3.1 Event Designators](https://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Event-Designators)
Thanks for help!
