### ISSUE TITLE
inject_dll_x86.exe reported as malware by McAfee

### ISSUE THREAD

**Issue by benganellison** [microsoft/debugpy#451] opened 2020-10-29 10:52 UTC
McAfee is reporting malware 

~/.vscode/extensions/ms-python.python-2020.10.332292344/pythonFiles/lib/python/debugpy/wheels/debugpy/_vendored/pydevd/pydevd_attach_to_process/inject_dll_x86.exe

related issues previously closed
https://github.com/microsoft/vscode-python/issues/10677

## Environment data

-   VS Code version: Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
-   Extension version (available under the Extensions sidebar): v2020.10.332292344
-   OS and version: MacOS, 10.15.7
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.5
-   McAfee version: 10.6.5
-   McAfee Engine version 6010.8670
-   McAfee DAT version 9766.000
-   McAfee Extra DAT version 2020.0611.0657.06
-   McAfee DAT Creation Date: 2020-10-06

## Expected behaviour

Should not be caught as a malware

## Actual behaviour

is beeing reported as malware, and my it deparment is on me telling me i can not use it anymore :/

feels like a regression to me, but i don't know

**Comment by karthiknadig** [comment] 2020-10-29 17:47
Duplicate of #450 . See instructions here to check if your version is not corrupted. https://github.com/microsoft/debugpy/issues/450#issuecomment-718274174

**Closed by karthiknadig** 2020-10-29 17:47 UTC

**Comment by benganellison** [comment] 2020-11-01 19:32
i can not check if it was corrupted or not. 
1st: the instructions to check is for windows
2nd: mcafee removed the file.

**Comment by karthiknadig** [comment] 2020-11-02 17:34
@benganellison See this response from @int19h https://github.com/microsoft/debugpy/issues/450#issuecomment-719795942 . Your issue and this are the same, MacAfee's signature database was probably out of date.
