### ISSUE TITLE
Django runserver hangs if run via debugpy and with autoreloading

### ISSUE THREAD

**Issue by carlfischerjba** [microsoft/debugpy#343] opened 2020-07-23 15:38 UTC
## Environment data

- debugpy version: 1.0.0b12
- OS and version: Debian 10.4 (Docker base image `python:3.6`)
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.6.11
- Using VS Code or Visual Studio: VSCode

## Actual behavior

Running Django `runserver` via `debugpy` hangs: `python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000`. No output at all.

## Expected  behavior

The Django server should start up and run while still allowing the debugger to connect.

## Steps to reproduce:
I've done this inside a Docker container for convenience.

1. Create Dockerfile.
  ```
  FROM python:3.6
  RUN mkdir /app
  WORKDIR /app
  RUN pip install django==2.2 debugpy
  RUN django-admin startproject myproject
  WORKDIR /app/myproject
  ```

2. Build the image.
  `docker build -t debugpy-django .`

3. Confirm Django server starts without debugpy
  `docker run --rm -it -p 1234:8000 -p 5678:5678 debugpy-django python manage.py runserver 0.0.0.0:8000`

4. See that Django server does **not** start when using debugpy
  `docker run --rm -it -p 1234:8000 -p 5678:5678 debugpy-django python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000`

5. Confirm that Django server starts when using debugpy and autoreloading is disabled.
  `docker run --rm -it -p 1234:8000 -p 5678:5678 debugpy-django python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --noreload`

Note that in step 3 if I attach to the process via VSCode with the following `launch.json`, the Django server either gets "unstuck" or it restarts in a way that lets it run as expected. However, the process should run without having to attach the debugger.
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "python",
            "request": "attach",
            "name": "Attach to Python",
            "host": "myhost",
            "port": 5678
        }
    ]
}
```

**Comment by carlfischerjba** [comment] 2020-07-23 15:46
[The VSCode docs](https://code.visualstudio.com/docs/python/debugging#_debugging-specific-app-types) have a note stating:
> Note that automatic reloading of Django apps is not possible while debugging.

This suggests that it's a known limitation. But:
- This is in the VSCode docs, not in the `debugpy` docs.
- The phrasing suggests that either automatic reloading or debugging won't work, but not that the app itself will hang.
- I thought a similar issue had been fixed in `ptvsd` and that prior to that there was [a workaround](https://ytec.nl/blog/debugging-django-vscode-without-using-noreload/).

FWIW I'm trying to set up a `docker-compose.yml` file for development that will let developers attach a debugger as needed but won't cause any visible changes to those who don't use VSCode. I can get around this by having a separate compose file for debugging but was trying to keep things simple.

**Comment by int19h** [comment] 2020-07-23 17:07
This is a duplicate of https://github.com/microsoft/debugpy/issues/81.

For your particular case, take a look at the VSCode Docker extension - they have some special magic for debugging that lets you *launch* things directly in the container, without having to jump through the hoops with attach.

**Closed by int19h** 2020-07-23 17:07 UTC

**Comment by carlfischerjba** [comment] 2020-07-24 09:20
Thanks. I hadn't spotted the more generic issue. I'll follow that one with interest.

So far, I've not tried to launch the process to debug directly from VSCode because it's part of a bigger stack where the Django server is already running. It would require stopping the existing Django container and restarting it from VSCode. I've found it simpler to just use a separate docker-compose file.

**Comment by int19h** [comment] 2023-04-25 18:03
The above should work in VSCode provided that you're using `"subProcess":true` in your debug config. If it is a different DAP client, it depends on whether and how it supports the relevant bits of the DAP spec (or custom debugpy messages that we used before those bits were added). VS, in particular, does not support subprocess debugging right now.

**Comment by xafizoff** [comment] 2023-04-25 18:29
Thank you, just updated DAP client and it works now.
