### ISSUE TITLE
Debugpy unable to start Flask server

### ISSUE THREAD

**Issue by TopeltR** [microsoft/debugpy#1296] opened 2023-05-17 12:38 UTC
## Environment data

- debugpy version: 1.6.7
- OS and version: macOS Ventura 13.2.1 
- Python version (& distribution if applicable, e.g. Anaconda): 3.10.11
- Using VS Code or Visual Studio: VS Code
- Flask version: 2.3.2

## Actual behaviour
When using a startup command to run a Flask server with debugpy and code reloading like this:
`FLASK_DEBUG=true FLASK_ENV=development python3 -m debugpy --listen 0.0.0.0:5678 -m flask run`

debugpy raises a RuntimeException:
<details>
  <summary>Details</summary>

  ```bash
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with watchdog (fsevents)
Traceback (most recent call last):
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3489, in <module>
    main()
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2510, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2528, in _exec
    globals = pydevd_runpy._run_module_as_main(module_name, alter_argv=False)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/server/cli.py", line 430, in main
    run()
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/server/cli.py", line 302, in run_module
    start_debugging(argv_0)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/server/cli.py", line 256, in start_debugging
    debugpy.listen(options.address)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/server/api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "/home/topeltr/Documents/Github/example-application/venv/lib/python3.10/site-packages/debugpy/server/api.py", line 262, in listen
    raise RuntimeError(str(endpoints["error"]))
RuntimeError: Can't listen for client connections: [Errno 48] Address already in use
  ```
</details>

I looked a bit more into the problem and it seems that a change in [Werkzeug](https://github.com/pallets/werkzeug/pull/2591) causes this. `sys.orig_argv` passes the entire command to the reloader i.e. `python3 -m debugpy --listen 0.0.0.0:5678 -m flask run` - which leads to a second instance of debugpy being started without shutting down the previous one causing the traceback from debugpy side. I already raised an issue on the Werkzeug side and they signalled that it should be handled on the debugpy side. 

## Expected  behaviour

No RuntimeError emitted and Debugpy can start a Flask server with code reloading.

## Steps to reproduce:
1. Use versions mentioned in the environments section
2. Run minimal Flask app ([example here](https://gist.github.com/TopeltR/0aa30cc7b7c8fb2ce4614b3bc17a80e3))

**Comment by jaredannis** [comment] 2023-06-28 18:00
i am having same issue, in my docker compose:

command: python -m debugpy --listen 0.0.0.0:5666 -m flask run --host=0.0.0.0

gets error:

RuntimeError: Can't listen for client connections: [Errno 98] Address already in use

setting flask to --no-reload lets the app load, but i am losing functionality

i am able to get it to work if explicitly set these versions:
werkzeug==2.2.2
flask==2.2.2
debugpy==1.6.3

**Comment by srh-sloan** [comment] 2023-11-16 11:54
We are also experiencing exactly this problem. Is there any update on when it will be fixed please?

**Comment by sebastienpires** [comment] 2023-12-04 18:10
Same issue here - we start losing the ability to debug if we upgrade any Python3.10 application to Werkzeug 2.3.0.

**Comment by int19h** [comment] 2023-12-04 19:22
Note that you can disable the Flask reloader by using `--no-reload` without disabling other Flask debugging features.

**Comment by yezhengli-Mr9** [comment] 2024-01-01 22:28
Are you following https://code.visualstudio.com/docs/containers/docker-compose for `python` with `docker-compose`? Not able to debug in vscode same way as pycharm in https://github.com/j2eeexpert2015/flask_docker/issues/1 although feel I need to debug in vscode https://github.com/j2eeexpert2015/springbootdebug/issues/1 due to the fact I need to run `docker-compose up` under `sudo su`.

For https://code.visualstudio.com/docs/containers/docker-compose and utilizing sample code https://github.com/j2eeexpert2015/flask_docker, I finish following steps:

1. On the Debug tab, choose the Configuration dropdown, choose New Configuration, choose Python, and select the Remote Attach configuration template. Result in following `launch.json`: 
```python
 {
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Remote Attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ],
            "justMyCode": true
        }
    ]
}
```
2.  Add into `docker-compose.yaml` `Dhttps://github.com/j2eeexpert2015/flask_docker/blob/587dc48e1a563226e5fd1ac63e82243590649f5c/docker-compose.yml#L4-L8 as following 
```diff
version: "2"
services:
  app:
    build: ./app
++  command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading --noreload"]
    links:
      - db
    ports:
      - "5000:5000"
++    - 5678:5678

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
``` 
3. Add `RUN pip install debugpy` to `DockerFile` just in case https://github.com/j2eeexpert2015/flask_docker/blob/587dc48e1a563226e5fd1ac63e82243590649f5c/app/Dockerfile#L10-L11
```diff
  COPY app.py /app
++RUN pip install debugpy 
  CMD python app.py
```
4. Add breakpoint in same as [video tutorial](https://www.youtube.com/watch?v=0B5GDP81gzE)
![image](https://github.com/microsoft/debugpy/assets/16505983/d3896438-d30f-4e9e-864a-ca2ca442a65f)
 

5. Right-click on the docker-compose.debug.yml file (example shown below) and choose Compose Up/Restart.

6. hit F5 with the Python: Remote Attach launch configuration selected.

**Comment by yezhengli-Mr9** [comment] 2024-01-01 22:59
Submit issue https://github.com/microsoft/debugpy/issues/1491

**Comment by stevefoga** [comment] 2024-02-13 20:41
Did anybody ever find a workaround for this?

**Comment by Keith-CPlus** [comment] 2024-02-23 07:33
Any other workaround for this? Other than bumping down werkzeug and flask versions?

**Comment by lukaspiatkowski** [comment] 2024-03-21 16:00
I've got a workaround, but you have to use debugpy API instead of the CLI. Just find the place in your code before you call `run(... , use_reloader=True)` on your flask app and add:
```
if (
    # The WERKZEUG_RUN_MAIN is set to true when running the subprocess for
    # reloading, we want to start debugpy only once during the first
    # invocation and never during reloads.
    os.environ.get("WERKZEUG_RUN_MAIN") != "true"
):
    import debugpy

    debugpy.listen(("0.0.0.0", 5678))
    debugpy.wait_for_client()
```
This will start debugpy only for the first original invocation of your app and not for the subsequent reload invocations. The `WERKZEUG_RUN_MAIN` env variable is set by Werkezeug itself and is used to identify if this is the reloadable subprocess.

**Comment by Keith-CPlus** [comment] 2024-03-26 03:46
> I've got a workaround, but you have to use debugpy API instead of the CLI. Just find the place in your code before you call `run(... , use_reloader=True)` on your flask app and add:
> 
> ```
> if (
>     # The WERKZEUG_RUN_MAIN is set to true when running the subprocess for
>     # reloading, we want to start debugpy only once during the first
>     # invocation and never during reloads.
>     os.environ.get("WERKZEUG_RUN_MAIN") != "true"
> ):
>     import debugpy
> 
>     debugpy.listen(("0.0.0.0", 5678))
>     debugpy.wait_for_client()
> ```
> 
> This will start debugpy only for the first original invocation of your app and not for the subsequent reload invocations. The `WERKZEUG_RUN_MAIN` env variable is set by Werkezeug itself and is used to identify if this is the reloadable subprocess.

This workaround works, but I seemed to be getting `SystemExit: 3`, although it doesn't affect functionality.
<img width="1247" alt="Screenshot 2024-03-26 at 11 45 10 AM" src="https://github.com/microsoft/debugpy/assets/101538034/efeba608-ae9a-4144-8f64-5bedf9cb7803">

**Comment by MaximeOlivie** [comment] 2024-04-29 14:28
Same here. Very annoying. No new workaround from someone?

**Comment by madolmo** [comment] 2024-05-05 20:50
Same problem. Just upgrading from Werkzeug 2.2.2 to 2.3.8 debugpy doesen't work anymore.

**Comment by sevenearths** [comment] 2024-05-14 09:11
Same here. I have a project waiting for this update :(

**Comment by oelhammouchi** [comment] 2024-08-26 19:08
I've tried to provide a fix in #1657 since I need this functionality for a dockerised Flask project. So far it seems to work just fine. The tests are also positive with the exception of `test_attach_pid_client`. I'm using Debian and according to #311 it should be working on Linux, but it doesn't for me. I get the same test errors on the original code though so it's not due to the change.

**Comment by rchiodo** [comment] 2024-08-27 17:57
This seems to work for me with the latest bits of debugpy and werkzeug. I do get an exception when reloading, but debugpy does attach to the new instance:

```
 * Detected change in 'C:\\Users\\rchiodo\\source\\testing\\flask_tutorial\\hello.py', reloading
Exception in thread Thread-6 (serve_forever):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\rchiodo\source\testing\flask_tutorial\.venv\Lib\site-packages\werkzeug\serving.py", line 817, in serve_forever
    super().serve_forever(poll_interval=poll_interval)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 233, in serve_forever
    ready = selector.select(poll_interval)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] An operation was attempted on something that is not a socket
 * Restarting with stat
127.0.0.1 - - [27/Aug/2024 10:53:21] "GET / HTTP/1.1" 200 -
```

I have werkzeug 3.0.4 and debugpy 1.8.5

**Comment by oelhammouchi** [comment] 2024-08-27 19:19
> This seems to work for me with the latest bits of debugpy and werkzeug. I do get an exception when reloading, but debugpy does attach to the new instance:
> 
> ```
>  * Detected change in 'C:\\Users\\rchiodo\\source\\testing\\flask_tutorial\\hello.py', reloading
> Exception in thread Thread-6 (serve_forever):
> Traceback (most recent call last):
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1045, in _bootstrap_inner
>     self.run()
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 982, in run
>     self._target(*self._args, **self._kwargs)
>   File "c:\Users\rchiodo\source\testing\flask_tutorial\.venv\Lib\site-packages\werkzeug\serving.py", line 817, in serve_forever
>     super().serve_forever(poll_interval=poll_interval)
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\socketserver.py", line 233, in serve_forever
>     ready = selector.select(poll_interval)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\selectors.py", line 323, in select
>     r, w, _ = self._select(self._readers, self._writers, [], timeout)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\selectors.py", line 314, in _select
>     r, w, x = select.select(r, w, w, timeout)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> OSError: [WinError 10038] An operation was attempted on something that is not a socket
>  * Restarting with stat
> 127.0.0.1 - - [27/Aug/2024 10:53:21] "GET / HTTP/1.1" 200 -
> ```
> 
> I have werkzeug 3.0.4 and debugpy 1.8.5

On Debian, I get this fatal error:

```
Traceback (most recent call last):
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3489, in <module>
    main()
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 3482, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2510, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd.py", line 2528, in _exec
    globals = pydevd_runpy._run_module_as_main(module_name, alter_argv=False)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 238, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/__main__.py", line 71, in <module>
    cli.main()
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/server/cli.py", line 486, in main
    run()
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/server/cli.py", line 354, in run_module
    start_debugging(argv_0)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/server/cli.py", line 308, in start_debugging
    debugpy.listen(options.address)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/public_api.py", line 31, in wrapper
    return wrapped(*args, **kwargs)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/server/api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "/home/othman/repos/debugpy/.venv/lib/python3.10/site-packages/debugpy/server/api.py", line 262, in listen
    raise RuntimeError(str(endpoints["error"]))
RuntimeError: Can't listen for client connections: [Errno 98] Address already in use
```

**Comment by rchiodo** [comment] 2024-08-27 19:33
Okay must be a linux only issue. I'll try on WSL (don't have a linux machine handy).

**Comment by rchiodo** [comment] 2024-08-27 19:38
Hmm, works fine on WSL too. I don't even get the error I had on windows.

**Closed** 2024-08-27 20:02 UTC
Labels: bug

**Comment by rchiodo** [comment] 2024-08-27 20:04
I tried the fix in https://github.com/microsoft/debugpy/pull/1657 and although I can't seem to reproduce the original error, the fix doesn't seem to break anything, so I merged it. Hopefully this fixes the problem for everybody.

**Comment by int19h** [comment] 2024-08-28 01:33
There's a lot of platform-specific weirdness around sockets, so it's not surprising that behavior differs. Note though that even when it works, it means that you have two different debugpy adapter processes, one of which is trying to manage both the parent and the child, while the other one (the one that causes the error on Linux and quietly overwrites the socket on Windows) is only managing the child. I'm not quite sure what the overall effects of that would be, but it's likely to break eventually.

**Comment by sebastienpires** [comment] 2024-08-28 09:59
I can confirm that the #1657 fix has resolved the issue I was facing on multiple applications running Python 3.11. 

I've pulled the commit into my requirements files and upgraded Flask to 3.0.3 and Werkzeug to 3.0.4.

The debugger now starts without any issue and I'm able to use hot-reloading.

Thanks @oelhammouchi  and @rchiodo
