### ISSUE TITLE
Auto-reconnect for remote debuggers

### ISSUE THREAD

**Issue by robertaistleitner** [microsoft/debugpy#796] opened 2021-11-25 11:51 UTC
When using a remote debugger like Python it would be awesome to have an auto-reconnect feature with a configurable timeout.

Using the debugger is pretty uncomfortable to use if you have some kind of code auto-reloading feature in place which in causes the debugger connection to get lost for a short period of time because of reloading/restarting.

According to https://github.com/microsoft/vscode/issues/137852#issuecomment-978992936 this can be implemented here.

**Comment by int19h** [comment] 2021-11-30 22:29
If your auto-reloader is itself written in Python, then using subprocess debugging should take care of that - indeed, that's exactly how it works for Django and Flask.

If the auto-reloader is not in Python, I believe this is a dupe of https://github.com/microsoft/debugpy/issues/577

**Closed by int19h** 2021-11-30 22:29 UTC
