### ISSUE TITLE
[BUG] macOS 15 can not debug

### ISSUE THREAD

**Issue by Sube-py** [microsoft/debugpy#1681] opened 2024-09-19 06:24 UTC
### Issue Description
After upgrading the system，when I debug, vscode enters the debug command before the terminal starts up，I guess that caused the debug to fail.
like this:
![image](https://github.com/user-attachments/assets/011be5fc-8d6e-4ca3-8d82-babc0d959e00)
and then:
![image](https://github.com/user-attachments/assets/df2f69a8-c6a8-4113-b9f2-63d4128c6719)

### Launch.json
```json
{
            "name": "Python: FastAPI",
            "type": "debugpy",
            "request": "launch",
            "module": "uvicorn",
            "args": [
                "server:app",
                "--reload",
                "--port",
                "8888"
            ],
            "jinja": true,
            "justMyCode": false,
            "cwd": "${workspaceFolder}",
}
```

### VsCode Version
1.93.1
38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40
arm64
### Debugpy version
lastest
### System Info

      System Version: macOS 15.0 (24A335)
      Kernel Version: Darwin 24.0.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled

**Comment by Dotinkasra** [comment] 2024-09-22 10:11
I have this same problem.

### VsCode Version
```
Version: 1.93.1 (Universal)
Electron: 30.4.0
ElectronBuildId: 10073054
Chromium: 124.0.6367.243
Node.js: 20.15.1
V8: 12.4.254.20-electron.0
OS: Darwin arm64 24.0.0
```

### Launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal"
        }
    ]
}
```

### Log File
[debugpy.adapter-91589.log](https://github.com/user-attachments/files/17089110/debugpy.adapter-91589.log)
[debugger.vscode_26d6b749-7dd2-4276-a925-7734471828a1.log](https://github.com/user-attachments/files/17089147/debugger.vscode_26d6b749-7dd2-4276-a925-7734471828a1.log)

**Comment by nleroy917** [comment] 2024-09-23 16:28
Having issues here too but with Flask

**Comment by iliagerman** [comment] 2024-09-24 03:23
I have the same issue on mac and python

**Comment by sirkozuch** [comment] 2024-09-24 14:26
Same issue here. And indeed, as @Sube-py mentioned, the issue seems to be that the command is passed too early. 

In fact, when I copy the said command and paste it again once the terminal starts up, debugging with `integratedTerminal` option works.

![Screenshot 2024-09-24 at 16 22 12](https://github.com/user-attachments/assets/da8e948c-a5f5-452f-895b-83ce4e4cb3ed)

**Comment by nleroy917** [comment] 2024-09-24 14:54
> In fact, when I copy the said command and paste it again once the terminal starts up, debugging with integratedTerminal option works.

Gotta be quick, but this works -- thanks for the tip

**Comment by rchiodo** [comment] 2024-09-24 20:10
This should be a dupe of #1677

**Closed by rchiodo** 2024-09-24 20:10 UTC
Labels: needs repro

**Comment by Sube-py** [comment] 2024-10-08 03:07
It's finally fixed😄
```txt
1.94.0
```
