### ISSUE TITLE
Displaying the type (class) of variables in the "Variables" panel during debugging, as implemented in PyCharm

### ISSUE THREAD

**Issue by dbulgakov7** [microsoft/debugpy#931] opened 2022-05-11 08:38 UTC
Is it possible for Python to display variable type (class) in the "Run and Debug" -> "Variables" panel?
For simple types, it is not difficult to understand the type (class) of a variable, but for complex types it can be a problem. Moreover, in VS Code, information about a variable type does not always display information in Special Variables -> class

I attach screenshots of how the information about variables in PyCharm and VS Code looks like. What I want to see in the PyCharm screenshot is underlined with red lines.

### PyCharm 2022.1 (Community Edition)

![165974624-1543f339-3868-4fca-92ab-faddce155acf](https://user-images.githubusercontent.com/73781118/167806370-6a409121-3812-4d33-89bd-ef15f5b17acf.png)

### Visual Studio Code 1.67.1 + Python Extension v2022.6.1

![165974677-cb911b1e-e2ce-4005-835e-3b88928c811d](https://user-images.githubusercontent.com/73781118/167806426-ab9f12b5-9abe-4607-9668-e0ef149c4cd2.png)

**Comment by int19h** [comment] 2022-05-25 18:01
This is a VSCode limitation, so far as I know. debugpy itself reports the type of all variables and expressions, and it's up to the client to display it.

**Comment by int19h** [comment] 2022-05-25 18:14
Dupe of https://github.com/microsoft/vscode/issues/146748

**Closed by int19h** 2022-05-25 18:14 UTC

**Comment by dbulgakov7** [comment] 2022-05-26 08:12
> This is a VSCode limitation, so far as I know. debugpy itself reports the type of all variables and expressions, and it's up to the client to display it. VSCode shows a tooltip on hover for that, instead of a separate column in the list.

Yes, I see it now.

![type_of_variable](https://user-images.githubusercontent.com/73781118/170446858-c3cd9df0-7772-4b3d-9014-10fc1a2ca926.png)
