### ISSUE TITLE
Setting for how much/little a debug value is truncated.

### ISSUE THREAD

**Issue by theoryshaw** [microsoft/debugpy#1137] opened 2022-11-29 03:28 UTC
Would be nice to have a setting, where you could control how much or how little vscode truncates debug values. 

If truncation was turned off you could see the whole value, for example. 
 `results: (Vector((1.6292068494294654e-07, -1.0, 0.0)), Vector((1.6292068494294654e-07, -1.0, 0.0)))`

verses how it is currently automatically truncates the value below...
![](https://community.osarch.org/uploads/editor/0s/nt2tb63872bx.png "")

**Comment by rchiodo** [comment] 2022-11-29 19:13
This is actually a dupe of https://github.com/microsoft/debugpy/issues/1084

**Closed by rchiodo** 2022-11-29 19:13 UTC
