### ISSUE TITLE
Doesn't cope with UTF-8 paths.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [microsoft/debugpy#1645] opened 2024-08-04 18:45 UTC
I've had issues in some paths that contain non-ASCII characters. Because the logs during debug would always mention IO decodement errata, I created an evaluation directory at the path:

> ```txt
> /home/RokeJulianLockhart/Documents/  [-]	`{title: "test_title",	id: "test_data"}`{.JSON5}.dir
> ```

...containing a multitude of characters in its file name to ascertain whether that was the cause. It certainly appears to be:

<blockQuote>

```log
RokeJulianLockhart@sayw4i:~/Documents/  [-]     `{title: "test_title",  id: "test_data"}`{.JSON5}.dir$  /usr/bin/env /usr/bin/python3 /home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024080201-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher 33439 -- /home/RokeJulianLockhart/Documents/\ \ \[-\]\    \`\{title\:\ \"test_title\"\,\  id\:\ \"test_data\"\}\`\{.JSON5\}.dir/\`\{title:\ \"test_title\",id:\ \"test_data\"\}\`\{.JSON5\}.dir/core.py 
Traceback (most recent call last):
  File "/usr/lib64/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024080201-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024080201-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024080201-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024080201-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/RokeJulianLockhart/.vscode-insiders/extensions/ms-python.debugpy-2024.11.2024080201-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 289, in _get_code_from_file
    with io_open_code(decoded_path) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/RokeJulianLockhart/Documents/  [-]\t`{title: "test_title",\tid: "test_data"}`{.JSON5}.dir/`{title: "test_title",id: "test_data"}`{.JSON5}.dir/core.py'
RokeJulianLockhart@sayw4i:~/Documents/  [-]     `{title: "test_title",  id: "test_data"}`{.JSON5}.dir$
```

</blockQuote>

The directory contained 1 file named "`core.py`".

**Comment by rchiodo** [comment] 2024-09-25 17:14
Is this the directory you created?

```
~/Documents/  [-]     `{title: "test_title",  id: "test_data"}`{.JSON5}.dir
```
And that got translated to this somehow?

```
/home/RokeJulianLockhart/Documents/  [-]\t`{title: "test_title",\tid: "test_data"}`{.JSON5}.dir/
```

It looks like it dropped some of the spaces?

**Comment by rchiodo** [comment] 2024-09-25 17:52
Closing as a dupe of https://github.com/microsoft/debugpy/issues/1671

**Closed by rchiodo** 2024-09-25 17:52 UTC

**Comment by RokeJulianLockhart** [comment] 2024-09-25 20:18
> https://github.com/microsoft/debugpy/issues/1645#issuecomment-2374778163

@rchiodo, apologies for the duplicate. I assume that I forgot that I had already filed this one.

**Comment by RokeJulianLockhart** [comment] 2024-09-25 20:18
> https://github.com/microsoft/debugpy/issues/1645#issuecomment-2374778163

@rchiodo, apologies for the duplicate. I assume that I forgot that I had already filed this one.

> https://github.com/microsoft/debugpy/issues/1645#event-14403344498

Perhaps it would be better to close this as invalid.
