### ISSUE TITLE
pydev debugger: critical: unable to get real case for file

### ISSUE THREAD

**Issue by mytk2012** [microsoft/debugpy#667] opened 2021-07-16 16:20 UTC
pydev debugger: critical: unable to get real case for file. Details:
filename: d:\
drive: D:\
parts: ['']
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.6.944021595\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find:  in D:\

**Comment by fabioz** [comment] 2021-07-19 15:38
Can you provide the logging for this?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

**Comment by fabioz** [comment] 2021-07-21 18:37
As a note, this may be a duplicate of https://github.com/microsoft/debugpy/issues/620 (a new `debugpy`release with a fix was just done in: https://github.com/microsoft/debugpy/releases/tag/v1.4.0, so, it's possible that this is fixed at the next `vscode-python` release -- if logging info is provided it should be clearer whether this is the case).

**Closed as completed** 2021-10-13 21:54 UTC
Labels: waiting for response

**Comment by bersbersbers** [comment] 2022-02-24 12:47
I am currently seeing this exact issue in VS Code 1.64.2 and 1.65.0-insider (3112460dc48ce7e557ea9feeaae04b912164b48b), using Python v2022.0.1814523869. I think it's using version 1.5.1 (from C:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_version.py)
```
pydev debugger: critical: unable to get real case for file. Details:
filename: d:\
drive: D:\
parts: ['']
(please create a ticket in the tracker to address this).
```

I basically open a new VS Code window (no folder, no workspace), I open "d:\Test.py" and run it using the configuration in https://github.com/microsoft/debugpy/issues/667#issuecomment-882650079.

`debugpy.pydevd.*.log`:
<details>

``` 
Using GEVENT_SUPPORT: False
pydevd __file__: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py
pydevd: Use libraries filter: False

IDE_PROJECT_ROOTS []

Collecting default library roots.
LIBRARY_ROOTS ['C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310', 'C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\Lib', 'C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages', 'C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\lib', 'C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages', 'C:\\Users\\bers\\AppData\\Roaming\\Python\\Python310\\site-packages']

Connecting to 127.0.0.1:61063
Connected.
Process PydevdAuthorizeRequest: {
    "arguments": {},
    "command": "pydevdAuthorize",
    "seq": 1,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 1, "success": true, "command": "pydevdAuthorize", "body": {"clientAccessToken": "d7d640b8c8deb98d30d58f01b89ec9283b9c681b133b770f38a1ee27628f999d"}, "seq": 2, "pydevd_cmd_id": 502}

Process PydevdSystemInfoRequest: {
    "arguments": {},
    "command": "pydevdSystemInfo",
    "seq": 2,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 2, "success": true, "command": "pydevdSystemInfo", "body": {"python": {"version": "3.10.2final0", "implementation": {"name": "cpython", "version": "3.10.2final0", "description": "CPython"}}, "platform": {"name": "win32"}, "process": {"pid": 13400, "ppid": 24164, "executable": "C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\python.exe", "bitness": 64}, "pydevd": {"usingCython": false, "usingFrameEval": false}}, "seq": 4, "pydevd_cmd_id": 502}

Process EvaluateRequest: {
    "arguments": {
        "expression": "\nif 'debugpy' not in sys.modules:\n    sys.path.insert(0, 'c:\\\\Users\\\\bers\\\\.vscode\\\\extensions\\\\ms-python.python-2022.0.1814523869\\\\pythonFiles\\\\lib\\\\python')\n    try:\n        import debugpy\n    finally:\n        del sys.path[0]\n",
        "format": {}
    },
    "command": "evaluate",
    "seq": 3,
    "type": "request"
}

processing internal command: InternalThreadCommands(<function internal_evaluate_expression_json at 0x0000020A6450D990>, (<_pydevd_bundle._debug_adapter.pydevd_schema.EvaluateRequest object at 0x0000020A6456B4C0>, '*'), {})
sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 3, "success": true, "command": "evaluate", "body": {"result": "", "variablesReference": 0, "presentationHint": {}}, "seq": 6, "pydevd_cmd_id": 502}

Process PydevdAuthorizeRequest: {
    "arguments": {},
    "command": "pydevdAuthorize",
    "seq": 4,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 4, "success": true, "command": "pydevdAuthorize", "body": {"clientAccessToken": "d7d640b8c8deb98d30d58f01b89ec9283b9c681b133b770f38a1ee27628f999d"}, "seq": 8, "pydevd_cmd_id": 502}

Process InitializeRequest: {
    "arguments": {
        "adapterID": "python",
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "columnsStartAt1": true,
        "linesStartAt1": true,
        "locale": "en-us",
        "pathFormat": "path",
        "supportsInvalidatedEvent": true,
        "supportsMemoryReferences": true,
        "supportsProgressReporting": true,
        "supportsRunInTerminalRequest": true,
        "supportsVariablePaging": true,
        "supportsVariableType": true
    },
    "command": "initialize",
    "seq": 5,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 5, "success": true, "command": "initialize", "seq": 10, "body": {"supportsConfigurationDoneRequest": true, "supportsFunctionBreakpoints": true, "supportsConditionalBreakpoints": true, "supportsHitConditionalBreakpoints": true, "supportsEvaluateForHovers": true, "exceptionBreakpointFilters": [{"filter": "raised", "label": "Raised Exceptions", "default": false}, {"filter": "uncaught", "label": "Uncaught Exceptions", "default": true}, {"filter": "userUnhandled", "label": "User Uncaught Exceptions", "default": false}], "supportsStepBack": false, "supportsSetVariable": true, "supportsRestartFrame": false, "supportsGotoTargetsRequest": true, "supportsStepInTargetsRequest": true, "supportsCompletionsRequest": true, "completionTriggerCharacters": [], "supportsModulesRequest": true, "additionalModuleColumns": [], "supportedChecksumAlgorithms": [], "supportsRestartRequest": false, "supportsExceptionOptions": true, "supportsValueFormattingOptions": true, "supportsExceptionInfoRequest": true, "supportTerminateDebuggee": true, "supportsDelayedStackTraceLoading": true, "supportsLoadedSourcesRequest": false, "supportsLogPoints": true, "supportsTerminateThreadsRequest": false, "supportsSetExpression": true, "supportsTerminateRequest": true, "supportsDataBreakpoints": false, "supportsReadMemoryRequest": false, "supportsDisassembleRequest": false, "supportsClipboardContext": true, "supportsDebuggerProperties": true, "pydevd": {"processId": 13400}}, "pydevd_cmd_id": 502}

Process LaunchRequest: {
    "arguments": {
        "__configurationTarget": 1,
        "__sessionId": "e602157b-6d2d-4212-bdf1-17c29cc790bc",
        "console": "integratedTerminal",
        "cwd": "d:\\",
        "debugAdapterPython": "C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\python.exe",
        "debugLauncherPython": "C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\python.exe",
        "debugOptions": [
            "ShowReturnValue",
            "FixFilePathCase"
        ],
        "env": {
            "PYTHONIOENCODING": "UTF-8",
            "PYTHONUNBUFFERED": "1"
        },
        "envFile": "c:\\Users\\bers\\.vscode\\extensions\\ms-python.python-2022.0.1814523869\\out\\client/.env",
        "internalConsoleOptions": "neverOpen",
        "justMyCode": true,
        "logToFile": true,
        "name": "Python: Current File (Integrated Terminal)",
        "processName": "d:\\Test.py",
        "program": "d:\\Test.py",
        "python": [
            "C:\\Users\\bers\\AppData\\Local\\Programs\\Python\\Python310\\python.exe"
        ],
        "pythonArgs": [],
        "request": "launch",
        "showReturnValue": true,
        "stopOnEntry": false,
        "type": "python",
        "workspaceFolder": "d:\\"
    },
    "command": "launch",
    "seq": 6,
    "type": "request"
}

sending cmd (http_json) -->    CMD_PROCESS_EVENT {"type": "event", "event": "process", "body": {"name": "d:\\Test.py", "systemProcessId": 13400, "isLocalProcess": true, "startMethod": "launch"}, "seq": 12, "pydevd_cmd_id": 204}

pydevd: Use libraries filter: True

Show return values: True
pydev debugger: critical: unable to get real case for file. Details:
filename: d:\
drive: D:\
parts: ['']
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 192, in _resolve_listing
    raise FileNotFoundError('Unable to find: %s in %s' % (
FileNotFoundError: Unable to find:  in D:\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 192, in _resolve_listing
    raise FileNotFoundError('Unable to find: %s in %s' % (
FileNotFoundError: Unable to find:  in D:\
pydev debugger: critical: unable to get real case for file. Details:
filename: D:\
drive: D:\
parts: ['']
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 192, in _resolve_listing
    raise FileNotFoundError('Unable to find: %s in %s' % (
FileNotFoundError: Unable to find:  in D:\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 192, in _resolve_listing
    raise FileNotFoundError('Unable to find: %s in %s' % (
FileNotFoundError: Unable to find:  in D:\
pydev debugger: critical: unable to get real case for file. Details:
filename: d:\
drive: D:\
parts: ['']
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 192, in _resolve_listing
    raise FileNotFoundError('Unable to find: %s in %s' % (
FileNotFoundError: Unable to find:  in D:\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 192, in _resolve_listing
    raise FileNotFoundError('Unable to find: %s in %s' % (
FileNotFoundError: Unable to find:  in D:\
sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 6, "success": true, "command": "launch", "seq": 14, "pydevd_cmd_id": 502}

Process SetDebuggerPropertyRequest: {
    "arguments": {
        "ideOS": "WINDOWS",
        "multiThreadsSingleNotification": true,
        "skipPrintBreakpointException": [
            "NameError"
        ],
        "skipSuspendOnBreakpointException": [
            "BaseException"
        ]
    },
    "command": "setDebuggerProperty",
    "seq": 7,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 7, "success": true, "command": "setDebuggerProperty", "seq": 16, "body": {}, "pydevd_cmd_id": 502}

Process SetFunctionBreakpointsRequest: {
    "arguments": {
        "breakpoints": []
    },
    "command": "setFunctionBreakpoints",
    "seq": 8,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 8, "success": true, "command": "setFunctionBreakpoints", "body": {"breakpoints": []}, "seq": 18, "pydevd_cmd_id": 502}

Process SetExceptionBreakpointsRequest: {
    "arguments": {
        "filters": [
            "uncaught"
        ]
    },
    "command": "setExceptionBreakpoints",
    "seq": 9,
    "type": "request"
}

Exceptions to hook on terminate: {'BaseException': <_pydevd_bundle.pydevd_breakpoints.ExceptionBreakpoint object at 0x0000020A645A3BB0>}.
sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 9, "success": true, "command": "setExceptionBreakpoints", "seq": 20, "pydevd_cmd_id": 502}

Process ConfigurationDoneRequest: {
    "arguments": {},
    "command": "configurationDone",
    "seq": 10,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 10, "success": true, "command": "configurationDone", "seq": 22, "pydevd_cmd_id": 502}

sending cmd (http_json) -->    CMD_THREAD_CREATE {"type": "event", "event": "thread", "body": {"reason": "started", "threadId": 1}, "seq": 24, "pydevd_cmd_id": 103}

Process ThreadsRequest: {
    "command": "threads",
    "seq": 11,
    "type": "request"
}

sending cmd (http_json) -->           CMD_RETURN {"type": "response", "request_seq": 11, "success": true, "command": "threads", "body": {"threads": [{"id": 1, "name": "MainThread"}]}, "seq": 26, "pydevd_cmd_id": 502}

Successfully Loaded helper lib to set tracing to all threads.
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py - set_tracing_for_untraced_contexts
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py - _locked_settrace
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py - settrace
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\ntpath.py
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py - _settrace
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py - connect
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py - debug
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\__init__.py - connect
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\common\compat.py - kwonly_f
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py - start_debugging
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py - run_file
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py - main
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\__main__.py - <module>
Set tracing of frame: C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\runpy.py - _run_code
Set tracing of frame: C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\runpy.py - _run_module_as_main
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py - settrace
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py - _settrace
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py - connect
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\api.py - debug
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\__init__.py - connect
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\common\compat.py - kwonly_f
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py - start_debugging
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py - run_file
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py - main
SKIP set tracing of frame: c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\__main__.py - <module>
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\genericpath.py
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\string.py
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\site.py
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\sysconfig.py
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\runpy.py
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\pkgutil.py
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\os.py
File traced: d:\Test.py
File not traced (not in project - force_check_project_scope): C:\Users\bers\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\thread.py
sending cmd (http_json) -->      CMD_THREAD_KILL {"type": "event", "event": "thread", "body": {"reason": "exited", "threadId": 1}, "seq": 28, "pydevd_cmd_id": 104}

No threads alive, finishing debug session
PyDB.dispose_and_kill_all_pydevd_threads (called from: File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1709, in process_internal_commands)
PyDB.dispose_and_kill_all_pydevd_threads (called from: File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 254, in _on_run)
PyDB.dispose_and_kill_all_pydevd_threads (first call)
PyDB.dispose_and_kill_all_pydevd_threads (already disposed - wait)
PyDB.dispose_and_kill_all_pydevd_threads no commands being processed.
PyDB.dispose_and_kill_all_pydevd_threads waiting for pydb daemon threads to finish
PyDB.dispose_and_kill_all_pydevd_threads killing thread: <WriterThread(pydevd.Writer, started daemon 1956)>
sending cmd (http_json) -->             CMD_EXIT {"type": "event", "event": "terminated", "seq": 30, "body": {}, "pydevd_cmd_id": 129}

pydevd.Writer received kill signal
PyDB.dispose_and_kill_all_pydevd_threads killing thread: <ReaderThread(pydevd.Reader, started daemon 26060)>
pydevd.Reader received kill signal
PyDB.dispose_and_kill_all_pydevd_threads killing thread: <PyDBCommandThread(pydevd.CommandThread, started daemon 12912)>
pydevd.CommandThread received kill signal
PyDB.dispose_and_kill_all_pydevd_threads killing thread: <CheckAliveThread(pydevd.CheckAliveThread, started 8952)>
pydevd.CheckAliveThread received kill signal
PyDB.dispose_and_kill_all_pydevd_threads killing thread: <_TimeoutThread(Thread-4, started daemon 26472)>
Thread-4 received kill signal
WriterThread: CMD_EXIT received
WriterThread: exit
ReaderThread: empty contents received (len(line) == 0).
PyDB.dispose_and_kill_all_pydevd_threads (called from: File "c:\Users\bers\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_comm.py", line 315, in _terminate_on_socket_close)
PyDB.dispose_and_kill_all_pydevd_threads (already disposed - wait)
PyDB.dispose_and_kill_all_pydevd_threads: finished
PyDB.dispose_and_kill_all_pydevd_threads: finished
ReaderThread: exit
The following pydb threads may not have finished correctly: pydevd.CommandThread
PyDB.dispose_and_kill_all_pydevd_threads: finished
pydevd.stoptrace()
```

</details>

**Comment by fabioz** [comment] 2022-02-24 18:49
@bersbersbers your issue was actually fixed in https://github.com/microsoft/debugpy/commit/83b18ef703a2cdc4241247d9e9700d5a75892f12
