### ISSUE TITLE
Error: Server[1] disconnected unexpectedly when typing anything in the Python debug console while debugging

### ISSUE THREAD

**Issue by Alexander-Wilms** [microsoft/debugpy#891] opened 2022-04-06 16:01 UTC
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: I can use the debug console to run python commands
Actual: The debugger crashes as soon as I type anything into the debug console

## Steps to reproduce:

1. Set breakpoint
2. Debug Python File
3.  Execution stops at breakpoint
4. Type anything into the debug console

Help > Toggle Developer Tools > Console shows the following

```
  ERR Server[1] disconnected unexpectedly: Error: Server[1] disconnected unexpectedly
    at s.handleErrorResponse (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1024:44858)
    at vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1024:44287
    at async Object.provideCompletionItems (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2241:5237)
    at async vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:690:15785
    at async Promise.all (index 0)
    at async m (vscode-file://vscode-app/c:/Users/Username/AppData/Local/Programs/Microsoft%…%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:690:15657)
    at async Promise.all (index 0)
```

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.1
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>User Settings</summary>

<p>

```

defaultLS: {"defaultLSType":"Pylance"}

downloadLanguageServer: true

envFile: "<placeholder>"

venvPath: "<placeholder>"

venvFolders: "<placeholder>"

condaPath: "<placeholder>"

pipenvPath: "<placeholder>"

poetryPath: "<placeholder>"

languageServer: "Pylance"

linting
• enabled: true
• cwd: "<placeholder>"
• Flake8Args: "<placeholder>"
• flake8Enabled: false
• flake8Path: "<placeholder>"
• lintOnSave: true
• banditArgs: "<placeholder>"
• banditEnabled: false
• banditPath: "<placeholder>"
• mypyArgs: "<placeholder>"
• mypyEnabled: false
• mypyPath: "<placeholder>"
• pycodestyleArgs: "<placeholder>"
• pycodestyleEnabled: false
• pycodestylePath: "<placeholder>"
• prospectorArgs: "<placeholder>"
• prospectorEnabled: false
• prospectorPath: "<placeholder>"
• pydocstyleArgs: "<placeholder>"
• pydocstyleEnabled: false
• pydocstylePath: "<placeholder>"
• pylamaArgs: "<placeholder>"
• pylamaEnabled: false
• pylamaPath: "<placeholder>"
• pylintArgs: "<placeholder>"
• pylintPath: "<placeholder>"

sortImports
• args: "<placeholder>"
• path: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"
• provider: "autopep8"
• blackArgs: "<placeholder>"
• blackPath: "<placeholder>"
• yapfArgs: "<placeholder>"
• yapfPath: "<placeholder>"

testing
• cwd: "<placeholder>"
• debugPort: 3000
• nosetestArgs: "<placeholder>"
• nosetestsEnabled: undefined
• nosetestPath: "<placeholder>"
• promptToConfigure: true
• pytestArgs: "<placeholder>"
• pytestEnabled: false
• pytestPath: "<placeholder>"
• unittestArgs: "<placeholder>"
• unittestEnabled: false
• autoTestDiscoverOnSaveEnabled: true

terminal
• activateEnvironment: true
• executeInFileDir: "<placeholder>"
• launchArgs: "<placeholder>"

experiments
• enabled: true
• optInto: []
• optOutFrom: []

tensorBoard
• logDirectory: "<placeholder>"

```

</p>
</details>

Extension version: 2022.4.0
VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.67GB free)|
|Process Argv|C:\\Users\\WilmsFA\\Tools\\Eigene\\silworx_sst_import\\silworx_sst_import.py --crash-reporter-id 1d44524e-2551-4c95-b981-53e1119f2c52|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by fabioz** [comment] 2022-04-15 12:07
@Alexander-Wilms can you provide the logs when that happens?

i.e.: 

* Run the command `Extensions: Open Extensions Folder`
* Locate the Python extension directory, typically of the form `ms-python.python-2022.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting `"logToFile": true`, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by fabioz** [comment] 2022-04-19 10:31
@xgnata This stands out in the logs:

```
Traceback (most recent call last):
  File "c:\Users\gnata\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 948, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "c:\Users\gnata\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_frame.py", line 164, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "c:\Users\gnata\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2023, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "c:\Users\gnata\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 2046, in _do_wait_suspend
    self._activate_gui_if_needed()
  File "c:\Users\gnata\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1571, in _activate_gui_if_needed
    activate_function()
  File "c:\Users\gnata\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd.py", line 1555, in <lambda>
    self.mpl_modules_for_patching = {"matplotlib": lambda: activate_matplotlib(do_enable_gui),
  File "c:\Users\gnata\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 98, in activate_matplotlib
    sys.stdout.write("Backend %s is interactive backend. Turning interactive mode on.\n" % backend)
AttributeError: 'NoneType' object has no attribute 'write'
```

It seems you don't have `sys.stdout`...  do you know why this happens in your app?

**Comment by xgnata** [comment] 2022-04-19 12:16
That's wried...
When I try to debug this script, with a brreakpoint on the print line; it *works* :
#import matplotlib.pyplot as plt

a = 1
for i in range(10):
    print(i)

but if I uncomment the import matplotlib.pyplot as plt line then it crashes as reported.
I have no idea what's going on with matplotlib but I cannot reproduce the bug if I don't import matplotlib.
Any idea how to debug that stuff??

**Comment by fabioz** [comment] 2022-04-25 10:09
The issue here is that `sys.stdout` is `None` (I'll change that so that this message is not sent through `sys.stdout`).

Anyways, do you know why that happens in your app? i.e.: Why are you setting `sys.stdout` to be `None`?

If you change that line (`sys.stdout.write("Backend %s is interactive backend. Turning interactive mode on.\n" % backend)`) to a `pass`, does it work?

**Comment by xgnata** [comment] 2022-04-25 10:37
I don't set sys.stdout to None.
My reduced test case is which triggers the bug is one very short python script : 
import matplotlib
a = 1
for i in range(10):
    print(i)

If I change sys.stdout.write("Backend %s is interactive backend. Turning interactive mode on.\n" % backend)) to a pass then it works.
I have no idea where/why sys.stdout is set to None.

**Comment by valignatev** [comment] 2022-06-20 13:02
I'm getting a similar Server[number] disconnected unexpectedly when debugging django management command that's running in a docker container. The debugger starts out fine, but when I call Model.objects.iterator it first waits a bit and then disconnects. The same disconnect is happening if I type anything in the debugging console.

**Comment by xgnata** [comment] 2022-06-26 15:28
The issue I run into is matplotlib related. 
Maybe I should open a specific issue as the fix is simple:
Test if sys.stdout is None before calling sys.stdout.write("Backend %s is interactive backend. Turning interactive mode on.\n" % backend))
(or try/except as it is more pythonic).

**Comment by xgnata** [comment] 2022-08-11 12:14
Should I create a bug report dedicated to the issue in matplotlibtools.py?
It is easy to patch on each new version of the VS extension but it is a bit anoying.

**Comment by int19h** [comment] 2022-09-27 17:36
We'll just treat this issue as the tracking one to update that code to check for `sys.stdout`.

**Comment by xgnata** [comment] 2022-09-27 18:47
Thanks.

Le mar. 27 sept. 2022 à 19:36, Pavel Minaev ***@***.***> a
écrit :

**Comment by xgnata** [comment] 2022-10-26 16:27
The issue with matplotlib is still there (It a rather big one when I try to advertise for python+vscode).

**Comment by xgnata** [comment] 2023-01-09 11:00
Even with the pre release version of the extension, import matplotlib.pyplot as plt still crashes the debuger.

**Comment by Alexander-Wilms** [comment] 2023-01-09 11:18
I haven't been encountering this issue lately.

**Comment by xgnata** [comment] 2023-01-10 09:30
Really? Which version of the extension do you use?
I do see the issue on a fresh install.

**Comment by xgnata** [comment] 2023-01-11 07:00
ok I cannot reproduce the bug with v2022.20.1 on ubuntu 22.10.
However, the bug still exists with  v2022.20.1 on my windows laptop because, for an unknown reason, sys.stdout does not exist.
Anyway, the code is buggy. It should not crash in matplotlibtools.py when sys.stdout  does not exist.

**Comment by int19h** [comment] 2023-01-11 21:26
Yes, we shouldn't be assuming that `sys.stdout` is available, since it's well-defined (if ill-advised) to set it to `None`.

**Comment by xgnata** [comment] 2023-01-13 10:28
So far I couldn't figure out why sys.stdout is None in this context...
The point is that I'm using pythonw.exe as the "default interpreter path" in the python extension.
It turns out that the bug with matplotlib+debugger is gone when I switch to python.exe (**without the w**) !

**Comment by xgnata** [comment] 2023-01-16 09:27
Well...of course the bug is not gone...it's just that pythonw does not  instantiate a terminal. This results somehow in std.stdout being None in this context.

**Comment by int19h** [comment] 2023-01-17 21:00
That actually makes a lot of sense, thank you!

As noted earlier, we're treating it as a genuine bug, although it would have to be fixed on pydevd side. In the meantime, if you must use `pythonw`, I think the easiest workaround is to manually set `sys.stdout` to e.g. a dummy instance of `io.StringIO` or to `open(os.devnull, "w")`, so that the writes don't fail.

**Comment by xgnata** [comment] 2023-01-18 11:10
I'm fine with using python.exe.
It would be better to kill this bug on pydev side to prevent futher users confusion.
https://github.com/fabioz/PyDev.Debugger/issues/215
 @fabioz what do you think?

**Comment by judej** [comment] 2023-01-19 21:44
Closing in this repo since the work is in PyDev.Debugger.

**Closed by judej** 2023-01-19 21:44 UTC
Labels: bug
