### ISSUE TITLE
VS Code 1.48.2 looks for python38.zip

### ISSUE THREAD

**Issue by Sebastian-Negoescu** [microsoft/debugpy#390] opened 2020-08-26 14:04 UTC
Version: 1.48.2
Commit: a0479759d6e9ea56afa657e454193f72aef85bd0
Date: 2020-08-25T10:09:08.021Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

After today's update, VS Code on MacOS looks for python38.zip

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python38.zip'
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/genericpath.py", line 19, in exists
    os.stat(path)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,

**Comment by int19h** [comment] 2020-08-27 18:56
It notifies you of the exception that occurs inside library code, but since the exception is handled, you should be able to continue running the app if you F5. Exception reports aren't automatically crashes.

I'm curious as to why this gets reported, though. What are your exception settings? This would be by design if "Raised" is checked, but the default is to break only on "Unhandled".

**Comment by fabioz** [comment] 2020-10-22 13:33
Closing as it seems things are working as intended (since the flag to show any raised exception seems to be on and it should be possible to simply proceed with the execution).

**Closed by fabioz** 2020-10-22 13:33 UTC

**Comment by dingkwang** [comment] 2023-09-06 04:22
What is the solution?

**Comment by egeres** [comment] 2023-09-19 10:05
For my case the problem was that I had checked "Raised Excetions" within the "breakpoints" menu and it was stopping my execution. This is a bit annoying because so far I can't see a way to capture all the raised exceptions of "just my code". Currently my workaround consists of: Adding a breakpoint at the beginning of my code while "Raised exceptions" is disabled, then when python has loaded in debug mode I re-enable it back to see all the exceptions my code is raining
