### ISSUE TITLE
"repr was slow" warning is modal in Visual Studio

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/debugpy#981] opened 2022-07-06 18:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/HOW-TO-Disable-Pydevd-waring/10079495)._

---
\[regression\] \[worked-in:17.2.5\]  
Python Coding.  
When I try to inspect a var by hovering my cursor over the var name in the edit window (something like a breakpoint used). Previously, I got a nice text box with var info, but now, I also get an annoying window (tittle: Microsoft Visual Studio, content: pydevd warning:Computing repr of datas (list)was slow (took 0.17s) ).  
I must close it before returning to the edit window.  
Could you tell me how to disable it?  
I realy do not remember what I have done to cause this problem.

ps. I uploaded the screenshot via Additional Files.

---
#### Feedback Bot on 6/23/2022, 11:07 PM: 

(private comment, text removed)
#### Feedback Bot on 6/23/2022, 11:07 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by fabioz** [comment] 2022-07-13 11:15
It's possible to customize the timeout for the warning (so, you can put a big timeout to disable it).

This can be done through an environment variable:

Something as:

`"PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT" : "0.5"`

Would set the timeout to 0.5 seconds. The current value is 0.15 seconds (maybe we could up it a bit -- it was kept slow because this has a direct effect on the responsiveness of the debugger -- before that was implemented there were complains about the debugger not responding when the issue is really that computing a repr of some variable is slow and it's not something that the debugger can control).

As a note, I haven't seen that as a dialog with confirmation so far (in fact, I remember that it was shown as a pop-up in the lower right corner which would fade out after a while). Is this a new thing in VSCode?

**Comment by int19h** [comment] 2022-07-13 18:02
That's the way it's handled by VS as opposed to VSCode.

**Comment by fabioz** [comment] 2022-07-13 18:04
Oh, I hadn't realized this was on VS. Got it.

**Comment by MarkKotwicz** [comment] 2022-09-07 02:37
How do we add "PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT" : "0.5"?
I tried adding it as an environmental variable under the project properties but that didn't work.

**Comment by yushaodong** [comment] 2022-09-08 08:16
no solution here

**Comment by yushaodong** [comment] 2022-09-08 08:19
> 

The bug still exists

**Comment by fabioz** [comment] 2022-09-08 10:35
`"PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT" : "0.5"` needs to be added on the `env` in the launch configuration.

-- another option is adding it in your system environment so that you don't need to add it to each new launch -- note that in this case you need to restart VSCode for it to pick that environment variable.

**Comment by MarkKotwicz** [comment] 2022-09-09 22:30
I'm using Visual Studio Community so I'm not sure if the 'env' launch configuration is applicable.  Adding it to my system variables worked though. Thanks.

**Comment by TernencezzZ** [comment] 2022-11-03 06:53
> I have tried this.,but the bug still exists.

**Comment by judej** [comment] 2023-01-19 22:00
Closing issue in this repo since the work is in VS Debugger adapter host repo. An issue has been created there: https://github.com/microsoft/VSDebugAdapterHost/issues/24

**Closed by judej** 2023-01-19 22:00 UTC
Labels: bug, external
