### ISSUE TITLE
Python debug test unable to step into third party module

### ISSUE THREAD

**Issue by steve148** [microsoft/debugpy#1776] opened 2024-11-06 03:29 UTC
Type: <b>Bug</b>

# Behaviour

**Expected**
When running a python test in debug mode with justMyCode set to false, I should be able to step into and debug third party modules.

**Actual**
Since v1.92, third party modules are unable to be stepped into with VSCode.

## Steps to reproduce:

1. Clone the demo repo I created at https://github.com/steve148/vscode-test-debug-bug
2. Install the dependencies with poetry.
3. Set a break point at the call to the third party module.
4. Run the test in debug mode.
5. Try to step into the third party module.

# Diagnostic data
<details>

<summary><code>launch.json</code> configuration
</summary>

<p>

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Debug Tests",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "purpose": [
                "debug-test"
            ],
            "console": "integratedTerminal",
            "logToFile": true,
            "justMyCode": false
        }
    ]
}
```

</p>
</details>

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
2024-11-05 22:31:20.287 [warning] Dir "/Users/lennoxstevenson/dev/vscode-test-debug-bug/.pixi/envs" is not watchable (directory does not exist)
2024-11-05 22:31:20.287 [info] VS Code was launched from an activated environment: '.venv', selecting it as the interpreter for workspace.
2024-11-05 22:31:20.287 [info] Python interpreter path: ./.venv/bin/python
2024-11-05 22:31:21.711 [info] > pyenv which python
2024-11-05 22:31:21.711 [info] cwd: .
2024-11-05 22:31:21.735 [info] > conda info --json
2024-11-05 22:31:24.556 [info] Starting Pylance language server.
2024-11-05 22:31:25.671 [info] Discover tests for workspace name: vscode-test-debug-bug - uri: /Users/lennoxstevenson/dev/vscode-test-debug-bug
2024-11-05 22:31:25.683 [info] > . ./.venv/bin/activate && echo 'e8b39361-0157-4923-80e1-22d70d46dee6' && python ~/.vscode/extensions/ms-python.python-2024.18.0-darwin-arm64/python_files/printEnvVariables.py
2024-11-05 22:31:25.683 [info] shell: bash
2024-11-05 22:31:25.716 [info] > ./.venv/bin/python ~/.vscode/extensions/ms-python.python-2024.18.0-darwin-arm64/python_files/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear tests
2024-11-05 22:31:25.716 [info] cwd: .
2024-11-05 22:31:30.089 [info] Using configuration in launch.json
2024-11-05 22:31:30.840 [info] CreateEnv Trigger - Skipping for /Users/lennoxstevenson/dev/vscode-test-debug-bug
2024-11-05 22:31:32.684 [info] DAP Server launched with command: /Users/lennoxstevenson/dev/vscode-test-debug-bug/.venv/bin/python /Users/lennoxstevenson/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter --log-dir /Users/lennoxstevenson/.vscode/extensions/ms-python.python-2024.18.0-darwin-arm64
2024-11-05 22:31:32.855 [info] Send text to terminal: source /Users/lennoxstevenson/dev/vscode-test-debug-bug/.venv/bin/activate.fish
2024-11-05 22:31:38.576 [info] Using configuration in launch.json
2024-11-05 22:31:38.726 [info] DAP Server launched with command: /Users/lennoxstevenson/dev/vscode-test-debug-bug/.venv/bin/python /Users/lennoxstevenson/.vscode/extensions/ms-python.debugpy-2024.12.0-darwin-arm64/bundled/libs/debugpy/adapter --log-dir /Users/lennoxstevenson/.vscode/extensions/ms-python.python-2024.18.0-darwin-arm64

```

</p>
</details>

<details>

<summary>Output for <code>Python Debugger</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python Debugger</code>)
</summary>

<p>

```
2024-11-05 22:31:21.739 [info] Name: Python Debugger
2024-11-05 22:31:21.739 [info] Module: debugpy
```

</p>
</details>

Extension version: 2024.8.0
VS Code version: Code 1.95.1 (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.0.0
Modes:

-   Python version (& distribution if applicable, e.g. Anaconda): 3.12.7
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): VirtualEnvironment<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (2.91GB free)|
|Process Argv|. --crash-reporter-id ccefdccc-a241-4b18-a2ac-fb744e259231|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rchiodo** [comment] 2024-12-19 16:52
I believe this is a dupe of #1785 which will be fixed when we ship again.

**Closed by rchiodo** 2024-12-19 16:52 UTC
Labels: needs repro
