### ISSUE TITLE
Debugger - ValueError: source code string cannot contain null bytes

### ISSUE THREAD

**Issue by rbavery** [microsoft/debugpy#745] opened 2021-10-07 00:59 UTC
I'm still getting this issue on 1.60.2 vscode but can't comment because the issue has been locked and the ptsvd repo is archived: https://github.com/microsoft/vscode-python/issues/5151

I also don't have any `.pyc` files in my python extension folder so the proposed solution to remove all `.pyc` files does not work

```python
→ ls ~/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/     
 completion.py		      run-jedi-language-server.py
 install_debugpy.py	      shell_exec.py
 interpreterInfo.py	      sortImports.py
 lib			      symbolProvider.py
 normalizeSelection.py	      tensorboard_launcher.py
'Notebooks intro.ipynb'       testing_tools
 printEnvVariables.py	      testlauncher.py
 printEnvVariablesToFile.py   visualstudio_py_testlauncher.py
 pyproject.toml		      vscode_datascience_helpers
 refactor.py

```

I also don't think I have any extra extension versions that are getting mixed up, like this issue comment suggests https://github.com/microsoft/ptvsd/issues/1323#issuecomment-481058988

```
/home/rave/.vscode/extensions/ms-python.python-2021.9.1246542782 
/home/rave/.vscode/extensions/ms-python.vscode-pylance-2021.9.4
```
those are the only python extensions I have

**Comment by fabioz** [comment] 2021-10-07 17:43
@rbavery can you provide the actual traceback you have?

**Comment by rbavery** [comment] 2021-10-07 19:46
sure thing

```
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_3/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/rave/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/rave/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/rave/.vscode/extensions/ms-python.python-2021.9.1246542782/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_3/lib/python3.9/runpy.py", line 267, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_3/lib/python3.9/runpy.py", line 242, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
ValueError: source code string cannot contain null bytes
```

**Comment by int19h** [comment] 2021-10-13 21:53
Can you share your project, or a simplified repro of the issue?

**Comment by fabioz** [comment] 2022-04-01 19:52
@rbavery can you still reproduce this?

I see the traceback shows:

```
  File "/home/linuxbrew/.linuxbrew/Cellar/python@3.9/3.9.1_3/lib/python3.9/runpy.py", line 242, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
```

Can you change that line of code to do:

```
contents = f.read()
print(repr(contents))
print(repr(fname))
code = compile(contents, fname, 'exec')
```

To know what exactly is being compiled wrong there?

**Comment by kbaikov** [comment] 2022-04-04 12:09
@fabioz I have a similar error and added the lines you asked

Here is the partial output:
`b'\x7fELF\x02\x01\x01\x00\x00\x00\x'`  # more binary data...
and
`'/bin/python'`

**Comment by kbaikov** [comment] 2022-04-04 12:22
I had an exact same error, but turned out i had incorrectly constructed launch.json

E.g. "program": "${command:python.interpreterPath}" , which is obviously wrong.

**Comment by rbavery** [comment] 2022-04-04 15:57
> Can you share your project, or a simplified repro of the issue?

Sorry I cannot, the repo is private. It's been awhile so I'm not sure how to reproduce this now.

**Comment by fabioz** [comment] 2022-04-22 17:42
Closing since we can't reproduce (and in the case we can the `"program"` target wasn't really correct).

**Closed by fabioz** 2022-04-22 17:42 UTC
Labels: bug, waiting for response, needs investigation
