### ISSUE TITLE
missing dict member in Value Tooltip and Watch Window

### ISSUE THREAD

**Issue by rfernand2** [microsoft/debugpy#1159] opened 2022-12-18 01:20 UTC
Type: <b>Bug</b>

When a member of a dict is an instance of class type 'int', that member is not shown in a value tooltip or watch window of the dict.  If you change it to, for example, a string, it becomes visible again.  When viewed from the debug console, the member is always visible.

## Steps to reproduce:

1. create a hello world program with a dict containing 8 members (one of which whose value is class type 'int')
2. view dict in value tooltip or from watch window - it will be missing the type 'int' member name/value. 

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• enabled: false

```

</p>
</details>

Extension version: 2022.20.1
VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.94GB (46.22GB free)|
|Process Argv|--crash-reporter-id 94040d29-3599-46dd-b01d-04be10695823|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by rfernand2** [comment] 2022-12-20 19:39
Sorry for creating the duplicate #20406.  The popup that gathers the issue information stays open after you have used it, as if it didn't succeed.  I came across it the next day, thinking something had gone wrong, and I couldn't find my bug in vscode/python, so I tried reentering it.   When you transfer an issue, can you keep the original where it was entered (close if needed, but refer to new location).  Otherwise, the issue creator cannot easily follow the issue.

Since #20406 was closed as a duplicate of this issue, why was this issue closed?

**Comment by int19h** [comment] 2022-12-20 22:09
The issue has already been transferred to the debugger repository.

**Comment by rfernand2** [comment] 2022-12-20 23:07
Thanks @int19h.  Here's the link for reference:  https://github.com/microsoft/debugpy/issues/1159

**Comment by fabioz** [comment] 2022-12-29 17:20
The issue is that `class` variables are in its own group (under `class variables`), so, it's not really a bug (as a note, the same happens if keys start with `__` or if there's a function as the value, those are put in its own values) -- although maybe a misfeature in this case 😉 .

i.e.:

![image](https://user-images.githubusercontent.com/117621/209985529-0214c998-e277-4ce0-9541-e17583878fbb.png)

I guess there could be a way for making exceptions so that the keys/values from the dict aren't classified, but this isn't available right now.

**Closed** 2023-01-10 23:45 UTC
Labels: bug
