### ISSUE TITLE
This version of python seems to be incorrectly compiled

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#847] opened 2022-02-19 17:56 UTC
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.4.3
- OS and version: w10
- Python version (& distribution if applicable, e.g. Anaconda): `Python 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] on win321`
- Using VS Code or Visual Studio:

## Actual behavior
```
 e:; cd 'e:\test_project'; & 'E:\Python310\python.exe' 'e:\Microsoft\.vscode\extensions\ms-python.python-2022.0.1814523869\pythonFiles\lib\python\debugpy\launcher' '55984' '--' 'E:\test_project\django\manage.py' 'runserver' '127.0.0.1:8000' '--traceback'       
This version of python seems to be incorrectly compiled
(internal generated filenames are not absolute).
This may make the debugger miss breakpoints.
Related bug: http://bugs.python.org/issue1666807
```

## Expected  behavior
Just run Django in debug mode.

## Steps to reproduce:
1. After forced the P310 to run microsoft/vscode-python#18571
2. Have this stupid bug as actual behavior when trying debug on P310-venv and other with P38-venv https://github.com/microsoft/debugpy/issues/764#issuecomment-1024650918

I tried with create venv again and still this same.

**Comment by ManPython** [comment] 2022-02-19 18:08
After turn off all raise exeptions:
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "socketserver.py", line 720, in __init__
    self.handle()
  File "E:\Python310-venv\lib\site-packages\django\core\servers\basehttp.py", line 178, in handle
    self.handle_one_request()
  File "E:\Python310-venv\lib\site-packages\django\core\servers\basehttp.py", line 186, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053]
```
Next
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
    self.run()
  File "threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "socketserver.py", line 652, in process_request_thread
    self.handle_error(request, client_address)
  File "E:\Python310-venv\lib\site-packages\django\core\servers\basehttp.py", line 75, in handle_error
    logger.info("- Broken pipe from %s\n", client_address)
  File "logging\__init__.py", line 1434, in info
  File "logging\__init__.py", line 1577, in _log
  File "logging\__init__.py", line 1587, in handle
  File "logging\__init__.py", line 1649, in callHandlers
  File "logging\__init__.py", line 946, in handle
  File "logging\__init__.py", line 807, in filter
  File "E:\Python310-venv\lib\site-packages\django\utils\log.py", line 147, in filter
    if self.callback(record):
```

**Comment by int19h** [comment] 2022-02-23 18:58
This is a fairly old version of debugpy; can you try with the most recent one?

**Comment by fabioz** [comment] 2022-02-25 12:51
Note that there really seems to be an issue in the files being reported by Python.

For instance, the filenames being reported in that traceback are just relative paths such as `"logging\__init__.py"` and `"socketserver.py"` when it should actually be an absolute path in your filesystem.

I don't know why this is happening in your case (but it's definitely wrong) -- I hadn't seen that issue on recent versions of CPython, so, it may be a regression on CPython itself or in the system you're using for virtual environments.

You can try to erase all the `.pyc` files related to the stdlib (just having them be recreated **may** fix your issue).

Note that as this is a bug in the Python venv you're using or in CPython itself (those paths should definitely be absolute), there's not much that the debugger can do here except complain (it then tries to work around that in the code, so, in general the debugger should still work, but that message can't be silenced).

-- As there's nothing to be done in the debugger side I'm closing the issue.

p.s.: You can check that this is the case by running the command below in a shell (the path printed **must** be absolute, if it's not you have that issue in your Python installation).

```
import os.path
print(os.path.realpath.__code__.co_filename)
```

**Closed by fabioz** 2022-02-25 12:51 UTC
Labels: waiting for response

**Comment by ManPython** [comment] 2022-02-26 12:26
@fabioz 
I using this comand to ommit pyc and not have pyc to be sure around problem
`sys.dont_write_bytecode`


But..
```
import os.path
print(os.path.realpath.__code__.co_filename)
2
[E:\Python38\lib\ntpath.py]()
```
I should expect venv I think.. as

`E:\\PYTHON\\Python38-venv\\Scripts\\python.exe`
