### ISSUE TITLE
test_completions_scope fails on Python 3.9

### ISSUE THREAD

**Issue by int19h** [microsoft/debugpy#415] opened 2020-09-21 18:31 UTC
"someFunction" is reported as "class" on 3.9 (should be "function"):
```
E           assert [{\n    "label..."length": 4\n}] == [{'label': 'So...: 'function'}]
E             At index 1 diff: {\n    "label": "someFunction",\n    "type": "class",\n    "start": 0,\n    "length": 4\n} != {'label': 'someFunction', 'type': 'function', 'start': 0, 'length': 4}
E             Use -v to get the full diff
```

**Comment by fabioz** [comment] 2020-10-08 18:23
I'll take a look at this.

**Comment by fabioz** [comment] 2020-10-09 17:23
This seems to be fixed in the latest master already (I also checked that I can reproduce the issue with the version shipped with VSCode and it works in master).

**Closed by fabioz** 2020-10-09 17:23 UTC
Labels: bug
