### ISSUE TITLE
Attach to process takes a long time

### ISSUE THREAD

**Issue by yevgeni-zolotko** [microsoft/debugpy#1044] opened 2022-09-07 13:20 UTC
## Environment data

- debugpy version: 1.6.2
- OS and version: Microsoft Windows [Version 10.0.22000.856]
- Python version: Python 3.8.10
- Using VS Code or Visual Studio: VS Code 1.71.0

## Actual behavior

Attaching the debugger to a python process running simple script takes a long time (around 6 seconds on my machine). This is reproducible on several other Windows machines.

## Expected  behavior

Attaching to a python process is faster (ideally less than 1 second).

## Steps to reproduce:
1. Create the following script and save it to file called `script.py`:

```
input("Press Enter...")
print("Finished")
```

2. Run the command: `python script.py`
3. In VS Code with the Python extension installed, start debugging by selecting _Attach Using Process ID_ and choosing the `python` process started in the previous step.
4. In VS Code, notice the progress indicator being displayed for a long time (about 6 seconds on my machine) before the debugger is attached to the process and its features like breakpoints work

**Comment by fabioz** [comment] 2022-09-07 13:49
Closing (duplicate of https://github.com/microsoft/debugpy/issues/1003).

Please see if https://github.com/microsoft/debugpy/issues/1003#issuecomment-1205164148 fixes it for you (note: you need to set that environment variable in your system or in the shell that spawns VSCode).

**Comment by fabioz** [comment] 2022-09-07 15:12
Reopening (I missed that it was in a different OS).

**Comment by fabioz** [comment] 2022-09-07 15:17
I'm not sure how much this is something we can fix (6 seconds isn't that much time and unfortunately just importing libraries on Python is pretty slow).

Historically we had to pre-load everything due to Python 2.7 deadlocking in lazy imports in the debugger due to its lock around imports... maybe we could revisit this now that Python 2 support is dropped to import less things at startup.

**Comment by int19h** [comment] 2023-02-01 18:37
It looks like we can't do much about this, unfortunately.

**Closed by int19h** 2023-02-01 18:37 UTC
Labels: enhancement
