### ISSUE TITLE
when i run py in py env,the error occurs

### ISSUE THREAD

**Issue by mytk2012** [microsoft/debugpy#665] opened 2021-07-17 05:02 UTC
Traceback (most recent call last):
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case    
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find:  in D:\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case    
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find:  in D:\
**pydev debugger: critical: unable to get real case for file. Details:
filename: D:\
drive: D:\
parts: ['']**
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case    
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find:  in D:\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case    
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find:  in D:\
pydev debugger: critical: unable to get real case for file. Details:
**filename: d:\
drive: D:\
parts: ['']**
(please create a ticket in the tracker to address this).
Traceback (most recent call last):
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 221, in _get_path_with_real_case    
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find:  in D:\

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 226, in _get_path_with_real_case    
    return _resolve_listing(drive, iter(parts))
  File "c:\Users\17150\.vscode\extensions\ms-python.python-2021.5.926500501\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydevd_file_utils.py", line 193, in _resolve_listing
    resolve_lowercase, resolved))
FileNotFoundError: Unable to find:  in D:\

**Comment by fabioz** [comment] 2021-07-19 15:40
This seems to be a duplicate of:

https://github.com/microsoft/debugpy/issues/667

As I asked for logs on that one already, I'm closing this one as a dupe.

**Closed by fabioz** 2021-07-19 15:40 UTC
