### ISSUE TITLE
Warnings are not shown while evaluating expressions in the debug console

### ISSUE THREAD

**Issue by david-cortes** [microsoft/debugpy#774] opened 2021-10-31 23:53 UTC
## Environment data

- debugpy version: 1.5.0
- OS and version: debian sid
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.7, from anaconda
- Using VS Code or Visual Studio: vscode

## Steps to reproduce:
1. Put a breakpoint right after a function that would throw a warning.
2. Execute code that would reach the breakpoint and would get the warning issued.

## Actual behavior

Does not show the warning anywhere while debugging.

## Expected  behavior

Should show warnings in the terminal pane while debugging, in the same part where `stdout` is written to.

**Comment by fabioz** [comment] 2022-01-28 11:42
Turning on/off warnings is something that can change the behavior of applications. Some frameworks (such as `pytest`) do enable the warnings (and enabling warnings when testing does make sense), but I think the debugger should be agnostic here.

-- just because you're using the debugger doesn't mean you want the warnings... if you do want warnings, I think you should explicitly enable that when launching the debugger and not having the debugger automatically do that (so, I think this is out of the scope of the debugger).

Given that, I'm currently `-1` on this request... @int19h do you have different thoughts here or can I close the issue?

**Comment by david-cortes** [comment] 2022-01-28 16:11
> **Turning on/off warnings is something that can change the behavior of applications**. Some frameworks (such as `pytest`) do enable the warnings (and enabling warnings when testing does make sense), but I think the debugger should be agnostic here.
> 
> -- just because you're using the debugger doesn't mean you want the warnings... if you do want warnings, I think you should explicitly enable that when launching the debugger and not having the debugger automatically do that (so, I think this is out of the scope of the debugger).
> 
> Given that, I'm currently `-1` on this request... @int19h do you have different thoughts here or can I close the issue?

Indeed - that's why they are important for debugging purposes. The default in a python interpreter is to show all warnings, while disabling them requires user action - why would a debugger behave differently from the regular interpreter in that regard?

BTW, there's no button to turn warnings on or off in the debug panel.

**Comment by fabioz** [comment] 2022-01-28 16:23
> Indeed - that's why they are important for debugging purposes. The default in a python interpreter is to show all warnings, while disabling them requires user action - why would a debugger behave differently from the regular interpreter in that regard?
> 
> BTW, there's no button to turn warnings on or off in the debug panel.

Sorry, I don't follow here... you mean you usually get warnings but not when debugging? Can you give some code example to reproduce this?

**Comment by david-cortes** [comment] 2022-01-28 16:33
Tried again with the latest version of vscode and the debugger - now warnings are shown correctly in the non-interactive terminal, but are not printed when executed as a statement in the debugger console:
![py_warning](https://user-images.githubusercontent.com/11860098/151585173-56d8b8c3-8816-47d8-bd0f-81d632dc262a.png)

**Comment by fabioz** [comment] 2022-01-28 16:58
Thanks for the explanation... the warnings in this case were really silenced as a part of https://github.com/microsoft/debugpy/issues/190.

It seems maybe it got to far when it silenced warnings when evaluating user expressions from the debug console.

**Closed** 2022-04-23 10:43 UTC
Labels: enhancement
