### ISSUE TITLE
When debugging stops in a "Subprocess", code is navigated to a strange read-only version of the current file

### ISSUE THREAD

**Issue by munael** [microsoft/debugpy#718] opened 2021-09-02 21:43 UTC
## Environment data

-   VS Code version: 1.59.0-insider
-   Extension version (available under the Extensions sidebar): 2021.9.1191016588
-   OS and version: Win10 21H1
-   Python version (& distribution if applicable, e.g. Anaconda): 3.7.7
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: `pylance`

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Stepping through and general interactive debugging happens in the normal, editable version of each relevant file.

## Actual behaviour

A new, parallel, read-only view of the file is opened instead. Notably missing is the breadcrumps bar, breakpoints' red orbs (it still stops on them but they're not visualized), and most extension actions (e.g. language server hints).

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Be on a remote session (possibly relevant?)
2. I didn't write this code :(
	1. I added the following header to the main script:
	```py
	import debugpy
	debugpy.listen(5678)
	print('waiting for debugger...')
	debugpy.wait_for_client()
	debugpy.breakpoint()
	print('attached')
	```
	2. Accordingly, I use VSCode's `Remote Attach`, NOT `Attach to Process`. The process is still local (and the debug target is `localhost`).
3. But this's how it looks in the debugger (the highlighted is the issue):
![image](https://user-images.githubusercontent.com/5769148/131920078-f727f9c4-6a3f-4e3f-bed7-7af70eefb877.png)

## Logs

Nothing relevant. Only errors for `mypy`.

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by fabioz** [comment] 2021-09-03 10:34
If you're on a remote session, probably the files you have locally don't match the same structure you have in the server, in which case the debugger must get the contents of the file from the server (in which case it's read-only).

It's however possible to configure the path mappings so that it can find the file locally.

See: https://code.visualstudio.com/docs/python/debugging for more information on `pathMappings`.

If you still can't get it to work, please provide the debugger logs for your run as well as the location where the files are locally as well as remotely.

i.e.: 

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form `ms-python.python-2021.*.****`
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
{
    "name": "Python: Current File (Integrated Terminal)",
    "type": "python",
    "request": "launch",
    "program": "${file}",
    "console": "integratedTerminal",
    "logToFile": true
}
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by munael** [comment] 2021-09-04 17:11
> If you're on a remote session, probably the files you have locally don't match the same structure you have in the server, in which case the debugger must get the contents of the file from the server (in which case it's read-only).
> 
> [...]

Hi o/ I'll look into getting the debug logs. But please note that _all files concerned are on the remote machine_. The entire session is run through the SSH extension, so, to my understanding, _nothing_ should be used from local machine. Even the Python extension runs on the remote machine as part of the vscode remote server.

**Comment by munael** [comment] 2021-09-07 00:33
Just noticed... Should this be moved to https://github.com/microsoft/vscode-python/issues/ instead? Hm 🤔

**Comment by fabioz** [comment] 2021-09-07 00:35
Probably not (I'm still waiting for the logs to provide more insight on what's actually happening...)

**Comment by int19h** [comment] 2021-09-07 18:43
The call stack shows "Python: Remote Attach" however, which indicates the use of debugpy remoting (and thus potential path mapping issues still apply). It's independent of VSC remoting, so you can have both at play at the same time. So you have three machines here - one that's running the VSCode client, one that's running the VSCode server, and one that's running the debuggee.

**Comment by munael** [comment] 2021-09-08 10:58
@fabioz 
> Probably not (I'm still waiting for the logs to provide more insight on what's actually happening...)

Not sure where the extension files (and logs) are on a Linux remote.

@int19h 
> The call stack shows "Python: Remote Attach" however, which indicates the use of debugpy remoting (and thus potential path mapping issues still apply). It's independent of VSC remoting, so you can have both at play at the same time. So you have three machines here - one that's running the VSCode client, one that's running the VSCode server, and one that's running the debuggee.

I'm using VSCode's `Remote Attach` with the following code header:
```py
import debugpy
debugpy.listen(5678)
print('waiting for debugger...')
debugpy.wait_for_client()
debugpy.breakpoint()
print('attached')
```

I haven't been able to figure out a similar code block that allows me to use VSCode's `Attach to Process`. With the code above, Attach to Process _always_ hangs and cannot be killed. I have to reload the window.

**Comment by fabioz** [comment] 2021-09-23 12:56
The logs I'm interested in are the `pydevd` logs, so, you should be able to set environment variables such as:

`PYDEVD_DEBUG_FILE=<directory>/pydevd.log`
`PYDEVD_DEBUG=1`

Then, after the run with those environment variables set, provide all the `*.log` files generated in the `<directory>` you specified.

**Comment by int19h** [comment] 2021-09-23 21:43
For "Attach to Process", you shouldn't need to `import debugpy` etc at all in your process - the whole point of that feature is that it injects the debugger without requiring the process to cooperate.

But once injected, it works the same as regular remote, so I don't think it'd make a difference in this case.

**Comment by fabioz** [comment] 2021-12-10 14:29
@munael I couldn't reproduce this locally with the steps provided and there aren't really any logs to know what's happening in your target use-case, so, I'm closing this issue.

p.s.: please feel free to reopen when/if you're able to provide the logs.

**Closed by fabioz** 2021-12-10 14:29 UTC
Labels: waiting for response
