### ISSUE TITLE
debugger not finding venv's standard library location properly?

### ISSUE THREAD

**Issue by demospace** [microsoft/debugpy#358] opened 2020-08-09 21:53 UTC
## Environment data

- debugpy version: I'm uncertain. I had to install this manually as I'm using whatever comes with the MS python extension so the import and print command showed nothing in my venv until I installed debugpy into the venv which shows `1.0.0b12` -- though I don't think this is what you're looking for.
- OS and version: Win10
- Python version: Base Win x64 3.8.5
- Using VS Code or Visual Studio: VS Code

## Actual behavior

When debugging with justMyCode set to false, the path to standard library packages is incorrect which yields FileNotFoundError exceptions while debugging instead of a jump to the stdlib. It isn't clear to me where to set/correct this path. I'm using a virtualenv that works fine when not debugging. The virtualenv has a pyvenv.cfg with a properly set `home` variable: `home = C:\Users\USER\AppData\Local\Programs\Python\Python38`

The runpy.py call stack:
![image](https://user-images.githubusercontent.com/39886696/89742512-448c9180-da60-11ea-9282-798433b4063d.png)

Notice the highlighted path below is *not* where Python 3.8.5 is installed (it's in C:\Users\USER\AppData\Local\Programs\Python\Python38 as shown above)

![image](https://user-images.githubusercontent.com/39886696/89742510-3d658380-da60-11ea-9955-369311005a7a.png)

## Expected  behavior

The debugger should pickup the path to the standard library from the venv configuration.

Maybe I should note that I had an A/B test notification from the vscode python extension so maybe they introduced an incompatibility?

**Comment by int19h** [comment] 2020-08-10 07:26
Can you show more of the call stack and/or error traceback? I'm curious as to what was calling into `runpy` - normally you wouldn't call it with a path pointing into site-packages.

**Comment by miquelmarti** [comment] 2020-08-24 14:34
Similar problem as above:

```
Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: '/home/miquelmr/.local/lib/python3.8'
  File "/home/miquelmr/miniconda3/envs/multitask/lib/python3.8/posixpath.py", line 167, in islink
    st = os.lstat(path)
  File "/home/miquelmr/miniconda3/envs/multitask/lib/python3.8/posixpath.py", line 425, in _joinrealpath
    if not islink(newpath):
  File "/home/miquelmr/miniconda3/envs/multitask/lib/python3.8/posixpath.py", line 391, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/home/miquelmr/miniconda3/envs/multitask/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/miquelmr/miniconda3/envs/multitask/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
```

I have Python 3.8.2 in a conda environment, so why is runpy looking for python3.8 in .local/bin seems like a bug.

**Comment by int19h** [comment] 2020-08-25 16:53
The exception itself is fine - the code where it happens catches it immediately. I think the problem is that we're reporting it incorrectly.

Is there anything else in the stack trace, or is `_run_code` the last thing you see?

**Comment by demospace** [comment] 2020-08-25 18:07
This may have been due to either a bad click or a bad default that had breakpoints set for all `Raised Exceptions`
![image](https://user-images.githubusercontent.com/39886696/91210986-a6d9c900-e6d3-11ea-8ed5-a0670d946753.png)

Either that or this resolved for me in one of the recent updates to vscode + python extensions. 

I did go in and remove myself from the vscode-python AB testing so that could have been it as well. 

I can no longer reproduce this in my environment and didn't spend time trying to debug it (I just needed a working debugger).

**Comment by int19h** [comment] 2020-08-25 19:48
The default should be as on the screenshot. But it's persistent on a per-workspace basis, so it's easy to set it and forget that it's there later.

Since it no longer repros for you, I'm going to go ahead and close this issue - please let us know if it manifests again.

**Closed by int19h** 2020-08-25 19:48 UTC

**Comment by rmajasol** [comment] 2021-07-22 12:29
> This may have been due to either a bad click or a bad default that had breakpoints set for all `Raised Exceptions`
> ![image](https://user-images.githubusercontent.com/39886696/91211212-08019c80-e6d4-11ea-986e-ae6984e51442.png)
> 
> Either that or this resolved for me in one of the recent updates to vscode + python extensions.
> 
> I did go in and remove myself from the vscode-python AB testing so that could have been it as well.
> 
> I can no longer reproduce this in my environment and didn't spend time trying to debug it (I just needed a working debugger).

You saved my life haha. Thanks!

**Comment by Venkat2811** [comment] 2022-09-05 12:33
> This may have been due to either a bad click or a bad default that had breakpoints set for all `Raised Exceptions` ![image](https://user-images.githubusercontent.com/39886696/91211212-08019c80-e6d4-11ea-986e-ae6984e51442.png)
> 
> Either that or this resolved for me in one of the recent updates to vscode + python extensions.
> 
> I did go in and remove myself from the vscode-python AB testing so that could have been it as well.
> 
> I can no longer reproduce this in my environment and didn't spend time trying to debug it (I just needed a working debugger).

Thanks !
