### ISSUE TITLE
Debugging is hanging

### ISSUE THREAD

**Issue by ignvinay** [microsoft/debugpy#412] opened 2020-09-18 14:34 UTC
Issue Type: <b>Bug</b>

Hi,
The python debugger when stopped and trying to invoke again it does not respond. When checked in process, saw that previous task is not stopped and its in hanging state.

Extension version: 2020.8.109390
VS Code version: Code 1.49.1 (58bb7b2331731bf72587010e943852e13e6fd3cf, 2020-09-16T23:27:51.792Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (2.35GB free)|
|Process Argv|--folder-uri file:///d%3A/Audio/MFCC_DNN --crash-reporter-id d2697788-6d3e-4dce-ba4b-9b8236cd8c11|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by int19h** [comment] 2020-09-22 23:51
Can you provide some more details on this? What kind of app, which processes remain around etc.

If you can provide the logs (`"logToFile": true` in your launch.json, then look for `debugpy*.log` in the folder where extension is installed), that would be perfect.

**Comment by fabioz** [comment] 2020-10-09 17:25
Closing since logs weren't provided. @ignvinay, feel free to reopen if you're able to reproduce and provide the logs.

**Closed by fabioz** 2020-10-09 17:25 UTC
Labels: bug
