### ISSUE TITLE
Log points seem to double output

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/debugpy#197] opened 2019-07-10 22:16 UTC
@rchiodo(Rich Chiodo) commented on [Mon Jul 8 2019]

Add a logpoint into a python file with cells
Debug the cell

Logpoint prints twice.

Looks like pydevd is sending the output twice:
```
D00026.485: PYD --> {
                "type": "event",
                "event": "output",
                "body": {
                    "output": "Logging logger point\r\n",
                    "category": "stdout",
                    "source": {}
                },
                "seq": 34,
                "pydevd_cmd_id": 116
            }
D00026.485: (while handling ('CMD_WRITE_TO_CONSOLE', 34))
            IDE <-- {
                "type": "event",
                "seq": 18,
                "event": "output",
                "body": {
                    "output": "Logging logger point\r\n",
                    "category": "stdout",
                    "source": {}
                }
            }
D00026.485: PYD --> {
                "type": "event",
                "event": "output",
                "body": {
                    "output": "Logging logger point\r\n",
                    "category": "stdout",
                    "source": {}
                },
                "seq": 36,
                "pydevd_cmd_id": 116
            }
D00026.485: (while handling ('CMD_WRITE_TO_CONSOLE', 36))
            IDE <-- {
                "type": "event",
                "seq": 19,
                "event": "output",
                "body": {
                    "output": "Logging logger point\r\n",
                    "category": "stdout",
                    "source": {}
                }
            }
```

**Comment by int19h** [comment] 2020-05-04 21:14
Probably related to https://github.com/microsoft/debugpy/issues/133

**Comment by int19h** [comment] 2020-09-23 00:39
#133 is fixed now, so this should work as intended. Please re-open if it still repros for you.

**Closed by int19h** 2020-09-23 00:39 UTC
Labels: bug
