### ISSUE TITLE
Just my code not working in VS code

### ISSUE THREAD

**Issue by irm-codebase** [microsoft/debugpy#1674] opened 2024-08-01 19:01 UTC
Redirected from [#224487](https://github.com/microsoft/vscode/issues/224487)

Type: <b>Bug</b>

As the title says: when I set a launch.json file and try to debug my code (selecting "with launch.json", VScode returns:

`[Errno 2] No such file or directory: 'home/[myusername]/.local/lib`

This is making debugging code outside mine (justMyCode=false) impossible, and is very annoying. What's going on?

Note: I use conda, and I have correctly selected my interpreter to be conda.

VS Code version: Code 1.91.1 (f1e16e1e6214d7c44d078b1f0607b2388f29d729, 2024-07-09T22:08:12.169Z)
OS version: Linux x64 6.9.11-200.fc40.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-13700H (20 x 400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.25GB (8.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.23.1
catppuccin-vsc|Cat|3.15.0
catppuccin-vsc-icons|Cat|1.13.0
ruff|cha|2024.36.0
file-tree-to-text-generator|d-k|1.4.0
vscode-markdownlint|Dav|0.55.0
EditorConfig|Edi|0.16.4
remotehub|Git|0.62.0
vscode-drawio|hed|1.6.6
compareit|in4|0.0.2
mypy|mat|0.3.1
rainbow-csv|mec|3.12.0
git-graph|mhu|1.30.0
debugpy|ms-|2024.8.0
python|ms-|2024.13.2024073102
vscode-pylance|ms-|2024.7.1
jupyter|ms-|2024.6.0
jupyter-keymap|ms-|1.1.2
jupyter-renderers|ms-|1.0.19
vscode-jupyter-cell-tags|ms-|0.1.9
vscode-jupyter-slideshow|ms-|0.1.6
remote-ssh|ms-|0.112.0
remote-ssh-edit|ms-|0.86.0
azure-repos|ms-|0.38.0
remote-explorer|ms-|0.4.3
remote-repositories|ms-|0.40.0
autodocstring|njp|0.6.1
vscode-yaml|red|1.15.0
snakemake-lang|sna|0.1.8
code-spell-checker|str|3.0.1
code-spell-checker-british-english|str|1.4.10
even-better-toml|tam|0.19.2

</details>

**Comment by rchiodo** [comment] 2024-09-18 21:47
This works for me. I used this code here:

```python
import pytest

def test_justmycode():
    pytest.skip("test_justmycode is not implemented yet.")

test_justmycode()
```

Then I stuck a breakpoint in this file:

.venv\Lib\site-packages\_pytest\outcomes.py

The breakpoint hit when running with justMyCode=false.

Can you try that same repro? It might be a path mapping problem. The file you have with the 3rd party code is not the path that debugger is finding.

**Comment by irm-codebase** [comment] 2024-09-22 16:17
@rchiodo just to be clear on this: was your question directed at me? or at other maintainers tackling this issue?

**Comment by irm-codebase** [comment] 2024-09-22 16:39
I repeated your test case with the following in my `conda` project.

1. script

```python
import pytest

def test_justmycode():
    pytest.skip("test_justmycode is not implemented yet.")

test_justmycode()
```

2. settings

```json
{
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "debugpy.debugJustMyCode": false
}
```

3. breakpoint

![image](https://github.com/user-attachments/assets/8a1ccff9-c53e-4bb3-9457-7a588f2f9180)

4. run debugger

![image](https://github.com/user-attachments/assets/cb257cba-2b6a-4dfc-874b-40abea11b401)

5. fail

![image](https://github.com/user-attachments/assets/dce556f4-b216-4799-9f1b-0dd3929cf029)

**Comment by rchiodo** [comment] 2024-09-23 16:39
Okay it looks like it actually worked it's just the callstack isn't showing up. What's your version of VS code? There was a bug in VS code where they were hiding 'internal' stack frames (which these frames would be marked as).

This issue here:
https://github.com/microsoft/vscode/issues/214433

I'd try updating to the latest VS code and see if the problem reproduces. It seems to work for me on 1.94.0-insiders and 1.93.1 stable

This is the callstack I get:

![Image](https://github.com/user-attachments/assets/578aef65-8724-427c-bd28-e359a4c9fe8e)

**Comment by irm-codebase** [comment] 2024-10-23 08:51
@rchiodo apologies for the delay
I tried this in VSCode 1.94.2. Same error.

![Image](https://github.com/user-attachments/assets/7cab3bc4-bbfe-48a9-bcf1-da0f22fe91b8)

**Comment by rchiodo** [comment] 2024-10-23 15:56
I still suspect a VS code issue. We can double check that we're sending the stack frames but this is the same symptoms as the bug I mentioned above. 

If you turn this on:

```json
"logToFile": true
```

In your launch.json. That will generate logs in your `/home/<user>/.vscode/extensions/ms-python.debugpy-<version>/` folder. Those logs should contain the stack frame request and response. If they do, VS code isn't displaying it for some reason.

**Comment by irm-codebase** [comment] 2024-10-25 08:51
It might be, but I am not a VScode nor a debugpy dev... so interpreting this is a tad difficult for me.
Originally, my issue was 'bounced' from vscode to debugpy, and that issue has been locked so I cannot re-open it.
What would be your suggestion to move this forward? Creating a new issue on the VSCode side?

I think I generated the log file successfully. Here is what it has at the bottom (just as a way to see if I'm in the right file):

```json
1416 Client --> Adapter:
{
    "command": "stackTrace",
    "arguments": {
        "threadId": 1,
        "startFrame": 4,
        "levels": 19
    },
    "type": "request",
    "seq": 15
}
1420 Client <-- Adapter:
{
    "seq": 27,
    "type": "response",
    "request_seq": 15,
    "success": true,
    "command": "stackTrace",
    "body": {
        "stackFrames": [],
        "totalFrames": 4
    }
}
```

**Comment by rchiodo** [comment] 2024-10-25 15:54
The log makes it look like debugpy isn't returning the stack frames. Can you upload all of the other log files from that run? The pydevd one might give us a clue as to why there's no stack frames listed there.

**Comment by irm-codebase** [comment] 2024-10-28 14:06
Here it is!
[debugpy.pydevd.9272.log](https://github.com/user-attachments/files/17543622/debugpy.pydevd.9272.log)

**Comment by rchiodo** [comment] 2024-10-28 17:04
Hmm, doesn't make sense. It has a stack, but it doesn't return it. It returns it once but not the second time. Not sure why there's two threads shown either. 

I think we'd need the code to reproduce the problem. Can you share the code that's causing this?

**Comment by irm-codebase** [comment] 2024-10-28 17:35
It's the same code as the one you shared above. 
However, all code fails. In all projects in my workstation.
Every case I try returns this issue if  'debugpy.debugJustMyCode' is `False`.

Script:
```python
import pytest

def test_justmycode():
    pytest.skip("test_justmycode is not implemented yet.")

test_justmycode()
```

launch.json
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python Debugger: Current File",
            "type": "debugpy",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "logToFile": true
        }
    ]
}
```

vscode settings (general)
```json
{
    "workbench.colorTheme": "Catppuccin Mocha",
    "redhat.telemetry.enabled": false,
    "[python]": {
        "editor.defaultFormatter": "charliermarsh.ruff",
    },
    "git.autofetch": true,
    "cSpell.language": "en,en-GB",
    "cSpell.diagnosticLevel": "Hint",
    "jupyter.runStartupCommands": [
        "%load_ext autoreload",
        "%autoreload 2"
    ],
    "editor.fontFamily": "\"Fira Code\"",
    "editor.fontWeight": "normal",
    "editor.fontLigatures": true,
    "workbench.iconTheme": "catppuccin-mocha",
    "terminal.integrated.inheritEnv": false,
    "update.mode": "manual",
    "jupyter.askForKernelRestart": false,
    "jupyter.notebookFileRoot": "${workspaceFolder}",
    "jupyter.interactiveWindow.creationMode": "perFile",
    "window.restoreWindows": "none",
    "telemetry.telemetryLevel": "off",
    "ruff.nativeServer": true,
    "ruff.lint.ignore": [
        "PD004",
        "PD003"
    ],
    "mypy.debugLogging": true,
    "mypy.dmypyExecutable": "/home/ivanruizmanuel/miniforge3/bin/dmypy",
    "files.watcherExclude": {
        "**/.git/objects/**": true,
        "**/.git/subtree-cache/**": true,
        "**/node_modules/*/**": true,
        "**/.hg/store/**": true,
        "**/.snakemake/**": true
    },
    "search.exclude": {
        "**/node_modules": true,
        "**/bower_components": true,
        "**/*.code-search": true,
        "**/.snakemake": true
    },
    "markdownlint.config": {
        "MD007": {
            "indent": 4
        }
    },
    "ruff.configurationPreference": "filesystemFirst",
    "hediet.vscode-drawio.theme": "Kennedy"
}
```


vscode settings (project):
```json
{
    "python.testing.pytestArgs": [
        "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
    "debugpy.debugJustMyCode": false
}

```

**Closed** 2024-10-28 18:49 UTC
Labels: user responded, needs repro

**Comment by irm-codebase** [comment] 2024-10-31 08:47
It is as easy as that, huh? The problem is gone.
Thank you very much for the help @rchiodo , and sorry for taking your time!

Just for my understanding: basically, this is a bunch of 'harmless' internal Python exceptions that are hit before our test code runs, correct? Honestly I was assuming that this was a bug caused by debugpy or VSCode forgetting the active environment or something.
This makes way more sense.

Thanks again!

**Comment by rchiodo** [comment] 2024-10-31 16:27
> this is a bunch of 'harmless' internal Python exceptions that are hit before our test code runs

Yes, that's correct. Lots of other spots in the runtime or pytest can throw and handle exceptions before or even during your test running.
