### ISSUE TITLE
[BUG] - Single Quotes Escaped with \ On Linux

### ISSUE THREAD

**Issue by JavaScriptDude** [microsoft/debugpy#912] opened 2022-04-14 20:46 UTC
Sorry, bug reporting tool in VS Code is not working on my system. Can someone please changes this to a bug report.

# Behavior:
## Expected vs. Actual
When passing args to a Python script using VS Code python debugger, any single quotes within arguments get escaped. 

eg: "This ' is ' a ' test" becomes "This \' is \' a \' test"

This behavior does not occur on windows.

## Steps to reproduce:

Make a simple program:
```
import sys; print(sys.argv[1:])
```

Add launch.json with the args: "args": `["just ' a ' test '"]`

Run code  using vscode and your output will be: `["just \\' a \\' test \\'"]`

Run the code using python in cli: `python3 hello.py "just ' a ' test '"` and output is `["just ' a ' test '"]`

# Diagnostic data

-   Python version: 3.7.9
-   OS: Ubuntu 20.04.4 LTS
-   Type of virtual environment used: Pyenv
-   Value of the `python.languageServer` setting: Default

**Comment by int19h** [comment] 2022-06-01 18:06
If "argsExpansion" is not set, debugpy passes all arguments from "args" to the client and asks it to construct and run the appropriate command in the terminal; this is supposed to use the proper escaping for the current shell. If "argsExpansion" is "none", then debugpy passes all arguments via its own channel directly to `exec()`, bypassing the terminal and VSCode shell escaping. Thus, the latter always behaves the same on all platforms (and all clients), while the former varies from platform to platform and from shell to shell.

So this is most likely a bug in VSCode wrt escape handling in your shell. If the shell is more exotic, it might not be supported.

**Comment by int19h** [comment] 2022-06-01 18:08
I think this is most likely a dupe of https://github.com/microsoft/vscode/issues/125934 - note that it was fixed shortly after you filed this issue, so please try with the most recent VSCode version.

**Closed by int19h** 2022-06-01 18:08 UTC
Labels: bug, needs investigation
