### ISSUE TITLE
No output in output window when debug in Python 2.7 with "Windows Application" option checked.

### ISSUE THREAD

**Issue by linette-zyy** [microsoft/debugpy#57] opened 2020-02-27 10:18 UTC
**Steps to Reproduce**
1. Create Python Application project and type code
2. Right-click on the project and select Properties or press Alt+Enter to open Property page
3. Turn on the option "Windows Application" and change interpreter to Python2.7 in General tab and save
4. Start the debugger

**Expected behavior**
The code runs and can be debugged, and no terminal/console window appears.
![image](https://user-images.githubusercontent.com/59192491/75434810-11ac8080-598d-11ea-8199-fc36e396922f.png)

**Actural behavior**
No output in output window.
![image](https://user-images.githubusercontent.com/59192491/75435136-8f708c00-598d-11ea-80ba-533a67ccdc2e.png)

**Debug Host Log**
```
 1> DebugAdapterHost version: 16.6.40221.2 commit:b531e661bd58f91bfddf99f3bb337cf95e9139cd
 1> Starting 'C:\Python27\pythonw.exe' with arguments '"c:\program files (x86)\microsoft visual studio\2019\preview\common7\ide\extensions\microsoft\python\core\debugpy\adapter"'
 1> [DebugAdapter] --> C (initialize-1): {"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":null,"locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsHandshakeRequest":true},"seq":1}
 1> [DebugAdapter] <--   E (output): {"seq": 1, "type": "event", "event": "output", "body": {"category": "telemetry", "output": "ptvsd", "data": {"packageVersion": "1.0.0b1"}}}
 1> [DebugAdapter] <--   E (output): {"seq": 2, "type": "event", "event": "output", "body": {"category": "telemetry", "output": "debugpy", "data": {"packageVersion": "1.0.0b1"}}}
 1> [DebugAdapter] <--   R (initialize-1) [160 ms]: {"seq": 3, "type": "response", "request_seq": 1, "success": true, "command": "initialize", "body": {"supportsModulesRequest": true, "supportsConfigurationDoneRequest": true, "supportsDelayedStackTraceLoading": true, "supportsDebuggerProperties": true, "supportsHitConditionalBreakpoints": true, "supportsSetExpression": true, "supportsGotoTargetsRequest": true, "supportsSetVariable": true, "supportsLogPoints": true, "supportsCompletionsRequest": true, "exceptionBreakpointFilters": [{"filter": "raised", "default": false, "label": "Raised Exceptions"}, {"filter": "uncaught", "default": true, "label": "Uncaught Exceptions"}], "supportsExceptionInfoRequest": true, "supportsValueFormattingOptions": true, "supportsEvaluateForHovers": true, "supportsExceptionOptions": true, "supportsTerminateDebuggee": true, "supportsConditionalBreakpoints": true}}
 1> [DebugAdapter] --> C (launch-2): {"type":"request","command":"launch","arguments":{"noDebug":false,"cwd":"C:\\Users\\vyizh12\\source\\repos\\PythonApplication7\\PythonApplication7\\","python":["C:\\Python27\\pythonw.exe"],"console":"externalTerminal","program":["C:\\Users\\vyizh12\\source\\repos\\PythonApplication7\\PythonApplication7\\PythonApplication7.py"],"django":false,"stopOnEntry":true,"promptBeforeRunningWithBuildError":true,"redirectOutput":true,"waitOnAbnormalExit":true,"waitOnNormalExit":true,"breakOnSystemExitZero":false,"debugStdLib":false,"showReturnValue":true,"env":{"PROCESSOR_ARCHITEW6432":"AMD64","DriverData":"C:\\Windows\\System32\\Drivers\\DriverData","COMPUTERNAME":"vyizh12003","CommonProgramFiles(x86)":"C:\\Program Files (x86)\\Common Files","OneDrive":"C:\\Users\\vyizh12\\OneDrive","HOMEPATH":"\\Users\\vyizh12","VisualStudioEdition":"Microsoft Visual Studio Enterprise 2019","_PTVS_PID":"2704","ServiceHubLogSessionKey":"2CFCAEDC","PROCESSOR_REVISION":"5504","ThreadedWaitDialogDpiContext":"-4","PkgDefApplicationConfigFile":"C:\\Users\\vyizh12\\AppData\\Local\\Microsoft\\VisualStudio\\16.0_c48adc13\\devenv.exe.config","PATHEXT":".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC","TMP":"C:\\Users\\vyizh12\\AppData\\Local\\Temp","TEMP":"C:\\Users\\vyizh12\\AppData\\Local\\Temp","LOCALAPPDATA":"C:\\Users\\vyizh12\\AppData\\Local","PUBLIC":"C:\\Users\\Public","VSAPPIDNAME":"devenv.exe","CLIENTNAME":"DESKTOP-LF4LRSH","USERDOMAIN":"vyizh12003","ProgramFiles(x86)":"C:\\Program Files (x86)","Path":"C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Microsoft SQL Server\\130\\Tools\\Binn\\;C:\\Users\\vyizh12\\AppData\\Local\\Microsoft\\WindowsApps;","PROCESSOR_LEVEL":"6","PROCESSOR_IDENTIFIER":"Intel64 Family 6 Model 85 Stepping 4, GenuineIntel","PSModulePath":"C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules;C:\\Program Files\\Microsoft Monitoring Agent\\Agent\\PowerShell\\","NUMBER_OF_PROCESSORS":"4","FPS_BROWSER_USER_PROFILE_STRING":"Default","CommonProgramFiles":"C:\\Program Files (x86)\\Common Files","VisualStudioDir":"C:\\Users\\vyizh12\\Documents\\Visual Studio 2019","ProgramData":"C:\\ProgramData","ProgramW6432":"C:\\Program Files","ProgramFiles":"C:\\Program Files (x86)","VSSKUEDITION":"Enterprise","SystemRoot":"C:\\Windows","VSAPPIDDIR":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\Common7\\IDE\\","SESSIONNAME":"RDP-Tcp#2","VisualStudioVersion":"16.0","CommonProgramW6432":"C:\\Program Files\\Common Files","LOGONSERVER":"\\\\vyizh12003","USERPROFILE":"C:\\Users\\vyizh12","MSBuildLoadMicrosoftTargetsReadOnly":"true","VSLANG":"1033","USERDOMAIN_ROAMINGPROFILE":"vyizh12003","APPDATA":"C:\\Users\\vyizh12\\AppData\\Roaming","HOMEDRIVE":"C:","USERNAME":"vyizh12","PYTHONPATH":"C:\\Users\\vyizh12\\source\\repos\\PythonApplication7\\PythonApplication7\\","FPS_BROWSER_APP_PROFILE_STRING":"Internet Explorer","PROCESSOR_ARCHITECTURE":"x86","OS":"Windows_NT","ComSpec":"C:\\Windows\\system32\\cmd.exe","SystemDrive":"C:","windir":"C:\\Windows","ALLUSERSPROFILE":"C:\\ProgramData"},"rules":[{"path":"c:\\program files (x86)\\microsoft visual studio\\2019\\preview\\common7\\ide\\extensions\\microsoft\\python\\core\\","include":false}]},"seq":2}
 1> [DebugAdapter] <--   C (runInTerminal-4): {"seq": 4, "type": "request", "command": "runInTerminal", "arguments": {"kind": "external", "args": ["C:\\Python27\\pythonw.exe", "c:\\program files (x86)\\microsoft visual studio\\2019\\preview\\common7\\ide\\extensions\\microsoft\\python\\core\\debugpy\\launcher", "C:\\Users\\vyizh12\\source\\repos\\PythonApplication7\\PythonApplication7\\PythonApplication7.py"], "env": {"DEBUGPY_LAUNCHER_PORT": "50787"}, "title": "Python Debug Console"}}
 1> [DebugAdapter] --> R (runInTerminal-4): {"type":"response","request_seq":4,"success":true,"command":"runInTerminal","body":{"processId":1160},"seq":3}
 1> [DebugAdapter] <--   E (initialized): {"seq": 5, "type": "event", "event": "initialized"}
 1> [DebugAdapter] --> C (setDebuggerProperty-4): {"type":"request","command":"setDebuggerProperty","arguments":{"AllowOutOfProcessSymbols":1},"seq":4}
 1> [DebugAdapter] --> C (setDebuggerProperty-5): {"type":"request","command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":5}
 1> [DebugAdapter] --> C (setDebuggerProperty-6): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableFastEvaluate":1},"seq":6}
 1> [DebugAdapter] --> C (setDebuggerProperty-7): {"type":"request","command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":7}
 1> [DebugAdapter] --> C (setDebuggerProperty-8): {"type":"request","command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":1},"seq":8}
 1> [DebugAdapter] --> C (setDebuggerProperty-9): {"type":"request","command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":9}
 1> [DebugAdapter] --> C (setDebuggerProperty-10): {"type":"request","command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":1},"seq":10}
 1> [DebugAdapter] --> C (setDebuggerProperty-11): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableStepFiltering":true},"seq":11}
 1> [DebugAdapter] --> C (setExceptionBreakpoints-12): {"type":"request","command":"setExceptionBreakpoints","arguments":{"filters":[],"exceptionOptions":[{"breakMode":"userUnhandled","path":[{"names":["Python Exceptions"]}]},{"breakMode":"unhandled","path":[{"names":["Python Exceptions"]},{"names":["GeneratorExit","IndexError","StopIteration","AttributeError","KeyError"]}]}]},"seq":12}
 1> [DebugAdapter] <--   R (setDebuggerProperty-4) [20 ms]: {"seq": 6, "type": "response", "request_seq": 4, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-5) [18 ms]: {"seq": 7, "type": "response", "request_seq": 5, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-6) [18 ms]: {"seq": 8, "type": "response", "request_seq": 6, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-7) [18 ms]: {"seq": 9, "type": "response", "request_seq": 7, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-8) [18 ms]: {"seq": 10, "type": "response", "request_seq": 8, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-9) [18 ms]: {"seq": 11, "type": "response", "request_seq": 9, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-10) [19 ms]: {"seq": 12, "type": "response", "request_seq": 10, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-11) [21 ms]: {"seq": 13, "type": "response", "request_seq": 11, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setExceptionBreakpoints-12) [21 ms]: {"seq": 14, "type": "response", "request_seq": 12, "success": true, "command": "setExceptionBreakpoints"}
 1> [DebugAdapter] --> C (configurationDone-13): {"type":"request","command":"configurationDone","arguments":{},"seq":13}
 1> [DebugAdapter] <--   R (configurationDone-13) [5 ms]: {"seq": 15, "type": "response", "request_seq": 13, "success": true, "command": "configurationDone"}
 1> [DebugAdapter] <--   R (launch-2) [681 ms]: {"seq": 16, "type": "response", "request_seq": 2, "success": true, "command": "launch"}
 1> [DebugAdapter] <--   E (process): {"seq": 17, "type": "event", "event": "process", "body": {"pointerSize": 32, "startMethod": "launch", "isLocalProcess": true, "systemProcessId": 1668, "name": "C:\\Users\\vyizh12\\source\\repos\\PythonApplication7\\PythonApplication7\\PythonApplication7.py"}}
 1> [DebugAdapter] <--   E (thread): {"seq": 18, "type": "event", "event": "thread", "body": {"reason": "started", "threadId": 1}}
 1> [DebugAdapter] <--   E (stopped): {"seq": 19, "type": "event", "event": "stopped", "body": {"reason": "entry", "preserveFocusHint": false, "allThreadsStopped": true, "threadId": 1}}
 1> [DebugAdapter] --> C (threads-14): {"type":"request","command":"threads","arguments":{},"seq":14}
 1> [DebugAdapter] <--   R (threads-14) [7 ms]: {"seq": 20, "type": "response", "request_seq": 14, "success": true, "command": "threads", "body": {"threads": [{"id": 1, "name": "MainThread"}]}}
 1> [DebugAdapter] --> C (continue-15): {"type":"request","command":"continue","arguments":{"threadId":1},"seq":15}
 1> [DebugAdapter] <--   E (output): {"seq": 21, "type": "event", "event": "output", "body": {"category": "stdout", "output": "                                        "}}
 1> [DebugAdapter] <--   R (continue-15) [898 ms]: {"seq": 22, "type": "response", "request_seq": 15, "success": true, "command": "continue", "body": {"allThreadsContinued": true}}
 1> [DebugAdapter] <--   E (thread): {"seq": 23, "type": "event", "event": "thread", "body": {"reason": "exited", "threadId": 1}}
```

**VS version**
![image](https://user-images.githubusercontent.com/59192491/75435454-0148d580-598e-11ea-90fe-03ca3ed79a8b.png)

**Comment by int19h** [comment] 2020-02-28 23:48
Sorry, this was wrong. If "redirectOutput" is not set, then nothing is redirected. If it is set, then whatever is written to stdout/err is redirected - but, again, in this case there's no stdout/err.

**Comment by int19h** [comment] 2020-03-13 00:50
I'm going to close this one, since the output behavior is by design, and there's a separate issue for wait-on-exit.

**Closed by int19h** 2020-03-13 00:50 UTC
