### ISSUE TITLE
Debugger Hangs on check_output

### ISSUE THREAD

**Issue by 1John419** [microsoft/debugpy#1771] opened 2024-11-14 04:37 UTC
```
from subprocess import check_output

command = r'dir'
output = check_output(command, shell=True)
print(output)

```

This  hangs in the debugger in 2024.12.0. However, it runs as expected from the command line outside of vscode.

Works fine in 2024.10.0.

**Comment by rchiodo** [comment] 2024-12-11 17:46
I would hazard a guess this is a bug that was fixed in the latest version of debugpy where we changed how we debug 3.12 and 3.13 code. I can't reproduce the issue.

**Closed by rchiodo** 2024-12-11 17:46 UTC
Labels: needs repro

**Comment by 1John419** [comment] 2024-12-11 18:32
Sorry to report that this issue still exists in v2024.12.0...

**Comment by rchiodo** [comment] 2024-12-11 18:33
Sorry but that's not the latest version. You'd have to install the prerelease version.

**Comment by 1John419** [comment] 2024-12-11 18:37
OK, thanks for clarifying. Issue not observed in pre-release.
