### ISSUE TITLE
Debugger does not disconnect using Django autoreload

### ISSUE THREAD

**Issue by jordangullen** [microsoft/debugpy#651] opened 2021-06-30 05:38 UTC
## Environment data

- debugpy version: 1.3.0
- OS and version: macOS Big Sur 11.4
- Python version: Python 3.8.10
- Using VS Code or Visual Studio: VSCode
- Using Django with autoreload

## Actual behavior

Clicking the debugger disconnect button in vscode doesn't disconnect. It appears to hang.
Refreshing the connection works and breakpoints still continue to hit.

## Expected  behavior

Debugger should disconnect

## Steps to reproduce:
1. Setup basic django app and modify manage.py to include debugpy.listen for non "RUN_MAIN" (see stackoverflow [post](https://stackoverflow.com/a/62944426) for autoreload process details.)
2. Start Django app `python manage.py runserver`
3. Connect to debugger over port
4. Try to disconnect debugger

**Comment by int19h** [comment] 2021-08-17 21:16
I believe this is a dupe of https://github.com/microsoft/vscode/issues/130941

**Closed by int19h** 2021-08-17 21:16 UTC
