### ISSUE TITLE
Cannot set remote breakpoints in Visual Studio Community 2019 (Version 16.6.1)

### ISSUE THREAD

**Issue by mkashif14** [microsoft/debugpy#307] opened 2020-06-23 15:23 UTC
## Environment data

- **debugpy version**: 1.0.0b5 (on both the machines - local and remote)
- **Local OS and version**: Windows 10 (Version 2004)
- **Local Python version** (& distribution if applicable, e.g. Anaconda): CPython 3.7.5 (64-bit)
- **Using VS Code or Visual Studio:** VS Community 2019 (Version 16.6.1)
- **Remote OS and version:** Linux-4.9.0-6-amd64-x86_64-with-debian-9.4 x86_64
- **Remote Python version:** CPython 3.5.3 (64-bit)

## Actual behavior
I get the following error after I successfully attach to a remote process running on a Linux machine.
![image](https://user-images.githubusercontent.com/34096765/85421564-322ec500-b592-11ea-9a4c-76fdfac8553c.png)

I can, however, attach to the process, step through code, and stop at breakpoints set programmatically.

Could be a possible duplicate of this issue - https://github.com/microsoft/PTVS/issues/5801, but I'm using debugpy and that user was using ptvsd. My remote breakpoints are hit when I use ptvsd (version 2.2.0) with visual studio 2015. 

Here's the complete output/log from DebugAdapterHost:

` 1> DebugAdapterHost version: 16.6.40406.1 commit:b280b02371734e7430f86e716b974ee2c22d015a
 1> [DebugAdapter] --> C (initialize-1): {"type":"request","command":"initialize","arguments":{"pathFormat":"path","clientID":"visualstudio","clientName":"Visual Studio","adapterID":null,"locale":"en-US","linesStartAt1":true,"columnsStartAt1":true,"supportsVariableType":true,"supportsRunInTerminalRequest":true,"supportsMemoryReferences":true,"supportsProgressReporting":true,"supportsHandshakeRequest":true},"seq":1}
 1> [DebugAdapter] <--   E (output): {"seq": 1, "type": "event", "event": "output", "body": {"data": {"packageVersion": "1.0.0b5"}, "category": "telemetry", "output": "ptvsd"}}
 1> WARNING: Request 'initialize-1' has not received a response within 1000 ms!
 1> [DebugAdapter] <--   E (output): {"seq": 2, "type": "event", "event": "output", "body": {"data": {"packageVersion": "1.0.0b5"}, "category": "telemetry", "output": "debugpy"}}
 1> [DebugAdapter] <--   R (initialize-1) [1282 ms]: {"seq": 3, "type": "response", "request_seq": 1, "success": true, "command": "initialize", "body": {"supportsDebuggerProperties": true, "exceptionBreakpointFilters": [{"filter": "raised", "label": "Raised Exceptions", "default": false}, {"filter": "uncaught", "label": "Uncaught Exceptions", "default": true}], "supportsLogPoints": true, "supportsDelayedStackTraceLoading": true, "supportsSetVariable": true, "supportsSetExpression": true, "supportsModulesRequest": true, "supportsValueFormattingOptions": true, "supportsExceptionInfoRequest": true, "supportsEvaluateForHovers": true, "supportsGotoTargetsRequest": true, "supportsHitConditionalBreakpoints": true, "supportsExceptionOptions": true, "supportsConfigurationDoneRequest": true, "supportsTerminateDebuggee": true, "supportsConditionalBreakpoints": true, "supportsCompletionsRequest": true}}
 1> [DebugAdapter] --> C (attach-2): {"type":"request","command":"attach","arguments":{"host":"<remote_IP>","port":5678,"stopOnEntry":true,"promptBeforeRunningWithBuildError":true,"redirectOutput":true,"waitOnAbnormalExit":true,"waitOnNormalExit":true,"breakOnSystemExitZero":false,"debugStdLib":false,"showReturnValue":true,"rules":[{"path":"c:\\program files (x86)\\microsoft visual studio\\2019\\community\\common7\\ide\\extensions\\microsoft\\python\\core\\","include":false}]},"seq":2}
 1> [DebugAdapter] <--   E (debugpyWaitingForServer): {"seq": 4, "type": "event", "event": "debugpyWaitingForServer", "body": {"host": "127.0.0.1", "port": 39601}}
 1> WARNING: No handler registered for event of type 'debugpyWaitingForServer'!
 1> WARNING: Request 'attach-2' has not received a response within 1000 ms!
 1> [DebugAdapter] <--   E (initialized): {"seq": 5, "type": "event", "event": "initialized"}
 1> [DebugAdapter] --> C (debugpySystemInfo-3): {"type":"request","command":"debugpySystemInfo","arguments":{},"seq":3}
 1> [DebugAdapter] --> C (setDebuggerProperty-4): {"type":"request","command":"setDebuggerProperty","arguments":{"AllowOutOfProcessSymbols":1},"seq":4}
 1> [DebugAdapter] --> C (setDebuggerProperty-5): {"type":"request","command":"setDebuggerProperty","arguments":{"DisableJITOptimization":0},"seq":5}
 1> [DebugAdapter] --> C (setDebuggerProperty-6): {"type":"request","command":"setDebuggerProperty","arguments":{"EnableFastEvaluate":1},"seq":6}
 1> [DebugAdapter] --> C (setDebuggerProperty-7): {"type":"request","command":"setDebuggerProperty","arguments":{"InterpreterOptions":1},"seq":7}
 1> [DebugAdapter] --> C (setDebuggerProperty-8): {"type":"request","command":"setDebuggerProperty","arguments":{"JustMyCodeStepping":0},"seq":8}
 1> [DebugAdapter] --> C (setDebuggerProperty-9): {"type":"request","command":"setDebuggerProperty","arguments":{"StopOnExceptionCrossingManagedBoundary":0},"seq":9}
 1> [DebugAdapter] --> C (setDebuggerProperty-10): {"type":"request","command":"setDebuggerProperty","arguments":{"WarnIfNoUserCodeOnLaunch":0},"seq":10}
 1> [DebugAdapter] --> C (setBreakpoints-11): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\FirstPythonApplication.py","sources":[],"checksums":[]},"breakpoints":[{"line":2,"column":1}],"lines":[2]},"seq":11}
 1> [DebugAdapter] --> C (setBreakpoints-12): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2015.py","sources":[],"checksums":[]},"breakpoints":[{"line":26,"column":1},{"line":22,"column":1},{"line":20,"column":1},{"line":2,"column":1}],"lines":[26,22,20,2]},"seq":12}
 1> [DebugAdapter] --> C (setBreakpoints-13): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2019.py","sources":[],"checksums":[]},"breakpoints":[{"line":6,"column":1},{"line":39,"column":1}],"lines":[6,39]},"seq":13}
 1> [DebugAdapter] --> C (setExceptionBreakpoints-14): {"type":"request","command":"setExceptionBreakpoints","arguments":{"filters":[],"exceptionOptions":[{"breakMode":"userUnhandled","path":[{"names":["Python Exceptions"]}]},{"breakMode":"unhandled","path":[{"names":["Python Exceptions"]},{"names":["GeneratorExit","IndexError","StopIteration","AttributeError","KeyError"]}]}]},"seq":14}
 1> [DebugAdapter] <--   R (debugpySystemInfo-3) [643 ms]: {"seq": 6, "type": "response", "request_seq": 3, "success": true, "command": "debugpySystemInfo", "body": {"python": {"version": "3.5.3final0", "implementation": {"version": "3.5.3final0", "description": "CPython", "name": "cpython"}}, "platform": {"name": "linux"}, "debugpy": {"version": "1.0.0b5"}, "process": {"bitness": 64, "pid": 31778, "executable": "/usr/bin/python3", "ppid": 31629}, "pydevd": {"usingCython": true, "usingFrameEval": false}}}
 1> [DebugAdapter] <--   R (setDebuggerProperty-4) [985 ms]: {"seq": 7, "type": "response", "request_seq": 4, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-5) [982 ms]: {"seq": 8, "type": "response", "request_seq": 5, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-6) [982 ms]: {"seq": 9, "type": "response", "request_seq": 6, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-7) [982 ms]: {"seq": 10, "type": "response", "request_seq": 7, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-8) [982 ms]: {"seq": 11, "type": "response", "request_seq": 8, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-9) [982 ms]: {"seq": 12, "type": "response", "request_seq": 9, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setDebuggerProperty-10) [982 ms]: {"seq": 13, "type": "response", "request_seq": 10, "success": true, "command": "setDebuggerProperty"}
 1> [DebugAdapter] <--   R (setBreakpoints-11) [981 ms]: {"seq": 14, "type": "response", "request_seq": 11, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"line": 2, "message": "Breakpoint in file that does not exist.", "source": {"checksums": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\FirstPythonApplication.py", "sources": []}, "verified": false}]}}
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> [DebugAdapter] <--   R (setBreakpoints-12) [955 ms]: {"seq": 15, "type": "response", "request_seq": 12, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"line": 26, "message": "Breakpoint in file that does not exist.", "source": {"checksums": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2015.py", "sources": []}, "verified": false}, {"line": 22, "message": "Breakpoint in file that does not exist.", "source": {"checksums": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2015.py", "sources": []}, "verified": false}, {"line": 20, "message": "Breakpoint in file that does not exist.", "source": {"checksums": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2015.py", "sources": []}, "verified": false}, {"line": 2, "message": "Breakpoint in file that does not exist.", "source": {"checksums": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2015.py", "sources": []}, "verified": false}]}}
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> WARNING: Request 'setBreakpoints-13' has not received a response within 1000 ms!
 1> WARNING: Request 'setExceptionBreakpoints-14' has not received a response within 1000 ms!
 1> [DebugAdapter] <--   R (setBreakpoints-13) [1324 ms]: {"seq": 16, "type": "response", "request_seq": 13, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"line": 6, "message": "Breakpoint in file that does not exist.", "source": {"checksums": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2019.py", "sources": []}, "verified": false}, {"line": 39, "message": "Breakpoint in file that does not exist.", "source": {"checksums": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2019.py", "sources": []}, "verified": false}]}}
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> [DebugAdapter] <--   R (setExceptionBreakpoints-14) [1325 ms]: {"seq": 17, "type": "response", "request_seq": 14, "success": true, "command": "setExceptionBreakpoints"}
 1> [DebugAdapter] --> C (configurationDone-15): {"type":"request","command":"configurationDone","arguments":{},"seq":15}
 1> [DebugAdapter] <--   R (configurationDone-15) [557 ms]: {"seq": 18, "type": "response", "request_seq": 15, "success": true, "command": "configurationDone"}
 1> [DebugAdapter] <--   R (attach-2) [3537 ms]: {"seq": 19, "type": "response", "request_seq": 2, "success": true, "command": "attach"}
 1> [DebugAdapter] <--   E (process): {"seq": 20, "type": "event", "event": "process", "body": {"systemProcessId": 31778, "name": "guessing-game-vs2019.py", "isLocalProcess": true, "startMethod": "attach"}}
 1> [DebugAdapter] <--   E (thread): {"seq": 21, "type": "event", "event": "thread", "body": {"reason": "started", "threadId": 1}}
 1> [DebugAdapter] <--   E (stopped): {"seq": 22, "type": "event", "event": "stopped", "body": {"reason": "step", "preserveFocusHint": false, "threadId": 1, "allThreadsStopped": true}}
 1> [DebugAdapter] --> C (threads-16): {"type":"request","command":"threads","arguments":{},"seq":16}
 1> [DebugAdapter] <--   R (threads-16) [326 ms]: {"seq": 23, "type": "response", "request_seq": 16, "success": true, "command": "threads", "body": {"threads": [{"id": 1, "name": "MainThread"}]}}
 1> [DebugAdapter] --> C (stackTrace-17): {"type":"request","command":"stackTrace","arguments":{"threadId":1,"startFrame":0,"levels":1000,"format":{"parameters":true,"parameterTypes":true,"parameterNames":true,"line":true,"module":true,"includeAll":true}},"seq":17}
 1> [DebugAdapter] <--   R (stackTrace-17) [554 ms]: {"seq": 24, "type": "response", "request_seq": 17, "success": true, "command": "stackTrace", "body": {"totalFrames": 1, "stackFrames": [{"line": 31, "id": 2, "column": 1, "name": "__main__ : 31", "source": {"path": "/home/<linux_user>/python-dev-test/guessing-game-vs2019.py", "sourceReference": 0}}]}}
 1> [DebugAdapter] <--   E (module): {"seq": 25, "type": "event", "event": "module", "body": {"module": {"path": "/home/<linux_user>/python-dev-test/guessing-game-vs2019.py", "id": 0, "name": "__main__", "package": "None"}, "reason": "new"}}
 1> [DebugAdapter] --> C (evaluate-18): {"type":"request","command":"evaluate","arguments":{"context":"hover","expression":"name","frameId":2,"noSideEffects":true,"timeout":1500},"seq":18}
 1> [DebugAdapter] <--   R (evaluate-18) [760 ms]: {"seq": 26, "type": "response", "request_seq": 18, "success": false, "command": "evaluate", "message": "Exception occurred during evaluation."}
 1> [DebugAdapter] --> C (evaluate-19): {"type":"request","command":"evaluate","arguments":{"context":"hover","expression":"'Nope. The number I was thinking of was {0}'","frameId":2,"noSideEffects":true,"timeout":1500},"seq":19}
 1> [DebugAdapter] <--   R (evaluate-19) [623 ms]: {"seq": 27, "type": "response", "request_seq": 19, "success": true, "command": "evaluate", "body": {"type": "str", "presentationHint": {"attributes": ["rawString"]}, "variablesReference": 0, "result": "'Nope. The number I was thinking of was {0}'"}}
`

I even tried cleaning up the breakpoints and adding them after the process attaches successfully (as suggested here - https://github.com/microsoft/PTVS/issues/5089#issuecomment-465785583). Even then I get the same error. The DebugAdapter Host Log shows a **WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.** whenever I add a new breakpoint in the code while the debugger is attached and the program is waiting for input.
`[DebugAdapter] --> C (setBreakpoints-15): {"type":"request","command":"setBreakpoints","arguments":{"source":{"path":"d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2019.py","sources":[],"checksums":[]},"breakpoints":[{"line":35,"column":1},{"line":41,"column":1},{"line":46,"column":1}],"lines":[35,41,46]},"seq":15}
 1> [DebugAdapter] <--   R (setBreakpoints-15) [366 ms]: {"seq": 23, "type": "response", "request_seq": 15, "success": true, "command": "setBreakpoints", "body": {"breakpoints": [{"source": {"sources": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2019.py", "checksums": []}, "verified": false, "message": "Breakpoint in file that does not exist.", "line": 35}, {"source": {"sources": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2019.py", "checksums": []}, "verified": false, "message": "Breakpoint in file that does not exist.", "line": 41}, {"source": {"sources": [], "path": "d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\guessing-game-vs2019.py", "checksums": []}, "verified": false, "message": "Breakpoint in file that does not exist.", "line": 46}]}}
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.
 1> WARNING: Verified breakpoint missing 'id' field! Without an id, 'breakpoint' events cannot be used.`

## Expected  behavior

XXX

## Steps to reproduce:
1. XXX

**Comment by int19h** [comment] 2020-06-24 09:49
@huguesv Probably related to path mappings?

**Comment by fabioz** [comment] 2020-06-24 11:26
@mkashif14 it'd be nice if you can provide some logs for this case...

To do that, please set the following environment variables:

`PYDEVD_DEBUG_FILE=<path_to_some_file.log>` 
`PYDEVD_DEBUG=True`

And then do the run and provide the generated file(s) -- note that it should generate the log files with the `<pid>` in it.

**Comment by mkashif14** [comment] 2020-06-24 16:13
**Logs**
[DebugAdapterHost log.txt](https://github.com/microsoft/debugpy/files/4826610/DebugAdapterHost.log.txt)
[debugpy.adapter-26167.log](https://github.com/microsoft/debugpy/files/4826611/debugpy.adapter-26167.log)
[debugpy.server-26161.log](https://github.com/microsoft/debugpy/files/4826612/debugpy.server-26161.log)

**Source Code**
[gHelper_py.txt](https://github.com/microsoft/debugpy/files/4826617/gHelper_py.txt)
[guessing-game-vs2019_py.txt](https://github.com/microsoft/debugpy/files/4826618/guessing-game-vs2019_py.txt)

**Comment by fabioz** [comment] 2020-06-24 16:56
I don't see any `pathMapping` in the `attach` request, so, this is really expected to fail due to that.

I did a search on the PTVS repo and found: https://github.com/Microsoft/PTVS/issues/5055.

Given that this appears to be an issue in the client and not in `debugpy` itself, I'm closing the issue here (please keep track of that issue).

**Closed by fabioz** 2020-06-24 16:56 UTC
Labels: bug

**Comment by fabioz** [comment] 2020-06-25 11:01
As a note, while that integration is not done, you should be able to use the related `pydevd` environment variable to do that path mapping manually.

To do that, you have to set the environment variable:

`PATHS_FROM_ECLIPSE_TO_PYTHON` 

-- note: it's eclipse/pydev related because it was actually added before pydevd was integrated in VS/VSCode, but consider it as if it's a translation from the paths from VS -- which is the client -- to the server paths, where Python is running.

The environment variable is meant to be a json list of tuples with the entry on the client first and then the entry on the server. Note that this environment variable must be set on the server side.

i.e.: 
```
PATHS_FROM_ECLIPSE_TO_PYTHON=[["d:\\\\Dropbox\\\\Dev_Dotnet\\\\Visual Studio 2015\\\\FirstPythonApplication", "/my/path/to/FirstPythoApplication"]]
```

You can also set the environment variable `DEBUG_PYDEVD_PATHS_TRANSLATION=1` to have some messages printed on the paths being considered and translated in the server to help on getting the right translation.

**Comment by mkashif14** [comment] 2020-06-29 16:09
Thanks a lot @fabioz  for letting me know about the environment variables, I added them as suggested by you. In the first attempt, I gave the windows path exactly as you had given but looks like pydev debugger didn't like the four backward slashes and hence I changed the value of `PATHS_FROM_ECLIPSE_TO_PYTHON `variable as shown below

`export PATHS_FROM_ECLIPSE_TO_PYTHON='[["d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\", "/home/tb190414/python-dev-test/"]]'`

It then suggested revising path mappings for c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core. I went ahead and updated the variable as shown below
`export PATHS_FROM_ECLIPSE_TO_PYTHON='[["d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\", "/home/tb190414/python-dev-test/"],["c:\\program files (x86)\\microsoft visual studio\\2019\\community\\common7\\ide\\extensions\\microsoft\\python\\core\\", "/home/tb190414/.local/lib/python3.5/site-packages/"]]'`

Not sure if that's the correct mapping for  ....python\core folder. Kindly confirm what should be the mapping for the core folder.

Now if you look at the path that was sent to the server, you'll see the trailing slash in the UNIX path is reversed. The result remains the same if I omit the trailing slash
![image](https://user-images.githubusercontent.com/34096765/86028903-1f176b80-ba50-11ea-9501-d9bb379137c7.png)

If I add two trailing slashes, the result is different.
![image](https://user-images.githubusercontent.com/34096765/86029206-7c132180-ba50-11ea-9dc8-8b2e1a88a06e.png)

Let me know what should I do to properly pass the path mappings

**Comment by fabioz** [comment] 2020-06-29 16:36
The problem is that it thinks that the client OS is unix (when your client is actually windows).

This would usually be called from the client (when it also passes the path-mapping), and there's no environment variable for that, so, you have to change the source-code for that change.

So, you should be able to do:

```
import pydevd_file_utils
print(pydevd_file_utils.__file__)
```

Then, open that file and in `def set_ide_os(os):`, add a line forcing the `os` parameter to be always windows. i.e.:

```
os = 'WINDOWS'
```

**Comment by mkashif14** [comment] 2020-07-01 11:14
Awesome! Thanks a lot @fabioz, using your trick I was able to successfully attach to the remote process and my breakpoints are now being hit. I tested for both the approaches - via command line `- python -m debugpy `and by using` import debugpy`, and using the hack, the breakpoints are being hit
![image](https://user-images.githubusercontent.com/34096765/86237425-5d7c6a00-bbb9-11ea-8c62-e529de013b5b.png)

What I did observe was that the pydev debug statements` sent to server:` and `sent to client:` still show the wrong last slash. Although that's not stopping me from debugging, I thought it would be nice to bring it to your attention
![image](https://user-images.githubusercontent.com/34096765/86237734-f14e3600-bbb9-11ea-8dff-866c8dfe5c72.png)

**Comment by mkashif14** [comment] 2020-07-01 11:34
> It then suggested revising path mappings for c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\extensions\microsoft\python\core. I went ahead and updated the variable as shown below
> `export PATHS_FROM_ECLIPSE_TO_PYTHON='[["d:\\Dropbox\\Dev_Dotnet\\Visual Studio 2015\\FirstPythonApplication\\", "/home/tb190414/python-dev-test/"],["c:\\program files (x86)\\microsoft visual studio\\2019\\community\\common7\\ide\\extensions\\microsoft\\python\\core\\", "/home/tb190414/.local/lib/python3.5/site-packages/"]]'`
> 
> Not sure if that's the correct mapping for ....python\core folder. Kindly confirm what should be the mapping for the core folder.

@fabioz could you please confirm this as well? What UNIX path corresponds to the "...python\core" folder on Windows?

**Comment by fabioz** [comment] 2020-07-01 11:42
> @fabioz could you please confirm this as well? What UNIX path corresponds to the "...python\core" folder on Windows?

Those are client files and I believe you don't have them (so, you shouldn't need a mapping for it).

As for the slashes, they are fixed after that message is printed (so, it's just the debug message that has the slashes that way).

**Comment by mkashif14** [comment] 2020-07-01 13:09
Thanks once again! Much appreciate you for the assistance and guidance.

**Comment by mosbaker** [comment] 2020-07-15 06:55
Hi,
I went through these steps, changed the os variable as suggested, but still breakpoints cannot be set with same error as mentioned in the beginning of the thread. What else do i need to check?
Thanks,
Moshe

**Comment by int19h** [comment] 2020-07-15 07:50
@mosbaker Can you share what your `PATHS_FROM_ECLIPSE_TO_PYTHON` looks like, and what the local and remote paths are to the script where you're setting breakpoints in?

**Comment by mosbaker** [comment] 2020-07-15 10:44
PATHS_FROM_ECLIPSE_TO_PYTHON=[["c:\\temp\\a\\", "/home/pi/moshe_bluePy_bu/"]]
i copied the python script i'm remote debugging locally to "c:\temp\a" folder. The script is running on the RPi Linux machine at folder "home/pi/moshe_bluePy_bu"

**Comment by mosbaker** [comment] 2020-07-22 20:04
Hi,
Did you see my reply?

Moshe

On 15 Jul 2020 10:50, Pavel Minaev <notifications@github.com> wrote:

@mosbaker<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mosbaker&d=DwMCaQ&c=YlQJHsR4e2z6sq5iNUb1-8UzPbEw9OnHGjBjyVyvpyA&r=vwngM5eHy-cHvhNbIFIHCr0IbGVO2LMJ3oM6qjhM6qA&m=KXjLXcJLVzW0WnYqtxSPIOCYmpfhQ-4GthpyrbkZVVg&s=B4_5NRfbnU-otEMtchpWqaJSwwn-rnJCLB_urPaXw1o&e=> Can you share what your PATHS_FROM_ECLIPSE_TO_PYTHON looks like, and what the local and remote paths are to the script where you're setting breakpoints in?

**Comment by int19h** [comment] 2020-07-23 05:39
Note that these must be set on the *remote* machine, and you need to use shell syntax accordingly, with `export` and quoting/escaping, i.e.:
```sh
export PATHS_FROM_ECLIPSE_TO_PYTHON='[["c:\temp\a\", "/home/pi/moshe_bluePy_bu/"]]'
```

If it's still not working for you with the above, can you please file a separate issue (so that we don't have to track those comments on a different issue that's already resolved), and add debugpy logs there? To get the logs, you need to set another environment variable, again, on the remote machine:
```sh
export DEBUGPY_LOG_DIR="/home/pi/moshe_bluePy_bu/"
```
or a different directory - wherever you want the logs to be written. This should produce a bunch of files with names matching `debugpy*.log`. The one that would be most interesting is `debugpy.pydevd*.log`.

**Comment by mosbaker** [comment] 2020-07-23 06:56
Submitted:
https://github.com/microsoft/debugpy/issues/341

Thanks!


Moshe Baker
Corporate Platform Group
KLA-Tencor Israel
Phone: +972-4-6449498
Cell.:    +972-54-5319330
