### ISSUE TITLE
Debugger hangs on processing input()

### ISSUE THREAD

**Issue by criticalroll** [microsoft/debugpy#379] opened 2020-08-20 02:26 UTC
## Environment data

-   VS Code version: 1.48.0
-   Extension version (available under the Extensions sidebar): 2020.8.101144
-   OS and version: Ubuntu 20.04
-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.4
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: N/A
-   Relevant/affected Python-related VS Code extensions and their versions: N/A
-   Value of the `python.languageServer` setting: Microsoft

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue] <-- I tried this

## Expected behaviour

When using the debugger with "Python: Current File" configuration, the debugger handles processing input() properly and moves to the next breakpoint

## Actual behaviour

When using the debugger with "Python: Current File" configuration, the debugger hangs upon processing input() and does not move to the next breakpoint

## Workaround

Roll back to 2020.7.96456 version of python extension

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Set a break point to the last line and use the debugger with "Python: Current File" configuration for the following code:

```
#!/usr/bin/env python3

print("Hello!)
first_name = input("What is your first name?: ")
print(first_name)
```

## Logs

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Starting Pylance language server.
Python interpreter path: /usr/bin/python3.8
> pyenv root
> conda --version
> pyenv root
```

</p>
</details>

**Comment by karthiknadig** [comment] 2020-08-20 16:52
Duplicate of #370

**Closed** 2020-08-20 18:33 UTC
