### ISSUE TITLE
justMyCode: false but still can't set a breakpoint to my project installed with poetry from local pypi

### ISSUE THREAD

**Issue by ghuname** [microsoft/debugpy#831] opened 2022-02-02 13:46 UTC
We have written the needed
Issue Type: <b>Bug</b>

I used to work on project Y that is finished. The artifacts are pushed to our local pypi.

Now I am working on project X that as a prerequisite needs project Y.
With poetry add Y, I updated dependencies for project X and everything works well. Also in launch.json I have put justMyCode: false.

Now when I debug trace project X, when I come to line that calls something from project Y, I can't step into it. When I press "step into", the debugger moves me into the next line of project X.

As I have set justMyCode: false, it shouldn't act like this.
I believe that it should step into project's Y code and let me set breakpoints there.

From the other hand, I can ctrl+click to the project's Y method and that will leed me to the proper line of project's Y code, but if I try to set break point there, break point is gray and tooltip shows message: 
"justMyCode" option (default == true). Try setting "justMyCode": false in the debug configuration(e.g. launch.json)."

This is false positive report because justMyCode is set to false.

**Comment by ghuname** [comment] 2022-02-10 14:53
Is there anything new?

**Comment by karthiknadig** [comment] 2022-02-14 22:33
@ghuname I think this is working as expected. If you are in Project X, we treat everything that is not in project X dir as non-user code. If you want debugger to treat other dirs as user code then you can try this:
```
        {
            "name": "Launch: program",
            "type": "python",
            "request": "launch",
            "console": "integratedTerminal",
            "program": "${file}",
            "justMyCode": true,
            "rules": [{"path": "<path-to-projectY-root>", "include": true}] 
        },
```

/cc @fabioz does stepping respect the rules?

**Comment by fabioz** [comment] 2022-02-15 10:55
> /cc @fabioz does stepping respect the rules?

Yes, stepping should respect the rules.

**Comment by ghuname** [comment] 2022-02-15 20:40
At the moment I cannot reproduce the issue in my environment.
Please give to me few days in order to find a proper example.

**Comment by int19h** [comment] 2022-03-14 21:57
@ghuname Can you describe the specifics of your test case, and how it's different from others where the issue did not reproduce for you?

**Comment by fabioz** [comment] 2022-04-01 17:45
@ghuname even if you can't provide the actual sources, do you think you can share the related logging? (it's probably enough to find out the issue)

You can use environment variables to do that:

i.e.: To log to the directory `C:\logs` you can set:

```
PTVSD_LOG_DIR=C:\logs
PYDEVD_DEBUG=True
PYDEVD_DEBUG_FILE=C:\logs\pydevd.log
```

Ensure that the `C:\logs` directory exists (or specify a different directory you'd like). Note that this may generate several ptvsd-.log files. When the issue occurs, stop debugging and share the latest ptvsd-.log and pydevd.log files. Remove any personal information from the log files.

**Comment by fabioz** [comment] 2022-04-15 18:41
@ghuname closing since no additional info was provided. Feel free to provide the logs to reopen the issue.

**Closed by fabioz** 2022-04-15 18:41 UTC
Labels: waiting for response
