### ISSUE TITLE
Python Debugger not showing numpy array values after update 

### ISSUE THREAD

**Issue by jav-ed** [microsoft/debugpy#1418] opened 2023-11-06 11:01 UTC
The issue was already created by someone else in the vscode repo. There we were told to raise the issue in here. Thus, I am just copying and pasting the issue from: [https://github.com/microsoft/vscode/issues/196159](https://github.com/microsoft/vscode/issues/196159)

> Does this issue occur when all extensions are disabled?: Yes
> 
> * VS Code Version: 1.83.1
> * OS Version: Windows 11 22H2 build 22621.2428
> 
> Steps to Reproduce:
> 
> 1. Create a simple Python script that generates a numpy array, such as:
>    `import numpy as np
>    test = np.zeros((3, 3))`
> 2. Set a breakpoint below the above code and run debug.
> 3. Expand the 'test' variable in the locals section of the 'Debug and Run' window.
> 4. Observe that below 'function variables' now no longer shows each row of the first axis of the array as it did in older versions.
> 
> ![VSCode_1_83_1](https://user-images.githubusercontent.com/140783905/277100065-2a3032c3-c177-4e89-9989-bd528ab2b52d.jpg)
> 
> 6. If the new 'T' item that's below 'function variables' is expanded, this just loops the information from the root level.
> 
> ![VSCode_1_83_1_expand_loop](https://user-images.githubusercontent.com/140783905/277100077-f9ed8d7f-7244-4b00-a82c-f39dd6924fd0.jpg)
> 
> For reference, this is what it looked like with version 1.80.2:
> 
> ![VSCode_1_80_2](https://user-images.githubusercontent.com/140783905/277100101-905d6d76-c80a-4f5e-a8cc-7ee632fbe60e.jpg)

**Comment by jav-ed** [comment] 2023-11-17 12:54
Any update?

**Comment by graphic-goose** [comment] 2023-11-23 22:47
Is there any update on this? There's been several updates to VSCode since I originally reported the issue, apparently in the wrong section, and using the debugger for Numpy arrays is still unusable.

**Comment by Vladimir-Kryzhniy** [comment] 2023-11-25 20:28
hello! I'm having the same issue. 

My set-up:
VsCode Version: 1.84.2 (Universal)
MacOS: Monterey 12.6.7

Please fix this issue. Otherwise it's really hard to have an effective debugging session while working with big arrays.

**Comment by int19h** [comment] 2023-12-04 21:16
Dupe of https://github.com/microsoft/debugpy/issues/1408

**Closed by int19h** 2023-12-04 21:16 UTC
Labels: bug
