### ISSUE TITLE
Python Debugger not working

### ISSUE THREAD

**Issue by mathric** [microsoft/debugpy#1086] opened 2022-10-13 21:37 UTC
Type: <b>Bug</b>

After Clicking Python Debugger it start and terminated immediately without error message output to terminal. 
If there's a way other than add logToFile in launch.json to get more info about the error it'll also be helpful. 

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/20289754/195714822-af3ee475-82e3-4686-9bc3-b071ec390d11.png)

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/20289754/195714854-90ce6894-f14f-49c5-a2a4-2e160ba33c61.png)

### Log Content

```
0 Starting Session:
{
    "name": "Python: Current File",
    "type": "python",
    "request": "launch",
    "program": "c:\\Test\\.vscode\\launch.json",
    "console": "integratedTerminal",
    "justMyCode": false,
    "logToFile": true,
    "__configurationTarget": 6,
    "python": "c:\\Test\\venv\\Scripts\\python.exe",
    "debugAdapterPython": "c:\\Test\\venv\\Scripts\\python.exe",
    "debugLauncherPython": "c:\\Test\\venv\\Scripts\\python.exe",
    "cwd": "c:\\Test",
    "envFile": "c:\\Test/.env",
    "env": {
        "PYTHONIOENCODING": "UTF-8",
        "PYTHONUNBUFFERED": "1"
    },
    "stopOnEntry": false,
    "showReturnValue": true,
    "internalConsoleOptions": "neverOpen",
    "debugOptions": [
        "DebugStdLib",
        "ShowReturnValue",
        "FixFilePathCase"
    ],
    "workspaceFolder": "c:\\Test"
}
20 Client --> Adapter:
{
    "command": "initialize",
    "arguments": {
        "clientID": "vscode",
        "clientName": "Visual Studio Code",
        "adapterID": "python",
        "pathFormat": "path",
        "linesStartAt1": true,
        "columnsStartAt1": true,
        "supportsVariableType": true,
        "supportsVariablePaging": true,
        "supportsRunInTerminalRequest": true,
        "locale": "en-us",
        "supportsProgressReporting": true,
        "supportsInvalidatedEvent": true,
        "supportsMemoryReferences": true,
        "supportsArgsCanBeInterpretedByShell": true
    },
    "type": "request",
    "seq": 1
}
100 Error:
{}
100 Exit:
Exit-Code: 1
Signal: none

```

### Environment
-   Python version : 3.8.0
-   Type of virtual environment used: Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.16.0, also test on 2022.17.12791010, 2022.17.12861055, 2021.12.1559732655
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z), also test on 1.68.1
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (5.26GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 305a941d-5e9b-4b5a-ae0a-9465075dd197|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by fabioz** [comment] 2022-10-14 19:06
Closing given that the issue is with CPython 3.8.0.

**Closed by fabioz** 2022-10-14 19:06 UTC
