### ISSUE TITLE
Cannot import module from current working directory

### ISSUE THREAD

**Issue by david-cortes** [microsoft/debugpy#759] opened 2021-10-17 15:19 UTC
## Environment data

- debugpy version: 1.5.0
- OS and version: debian sid
- Python version (& distribution if applicable, e.g. Anaconda): 3.9.7, from anaconda
- Using VS Code or Visual Studio: VS code

## Actual behavior

If I am debugging a python file and try to import a python module from outside the project by changing to that directory with the os package, it will throw an error when importing it - e.g.:
```python
import os
os.chdir("/my/module/path")
import mymodule
```

## Expected  behavior

Should import the module.

**Comment by david-cortes** [comment] 2021-10-18 20:09
It's a regular import error:
```
Exception has occurred: ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: <module>)
No module named 'mymodule'
  File "/home/david/vscode_temp/aaa.py", line 3, in <module> (Current frame)
    import mymodule
````

```python
print(sys.path) #in the debugger prompt
```
```
['/home/david/vscode_temp', '/home/david/anaconda3/envs/py3/lib/python39.zip', '/home/david/anaconda3/envs/py3/lib/python3.9', '/home/david/anaconda3/envs/py3/lib/python3.9/lib-dynload', '/home/david/.local/lib/python3.9/site-packages', '/home/david/anaconda3/envs/py3/lib/python3.9/site-packages']
```

**Comment by int19h** [comment] 2021-10-19 00:05
Oh, I misunderstood the bug. This behavior is by design in Python (3.x) itself - the current directory is *not* on `sys.path` by default. The directory that contains the script/module that runs as __main__` is - that's the first entry in your `sys.path`.

To do what you want to do, you need to append the desired directory to `sys.path` instead (and possibly remove it after you've imported the module, if you don't want it to get in the way thereafter). Or, if this is specific to your filesystem layout and not the project, set `"env": {"PYTHONPATH": ...}`.

**Comment by david-cortes** [comment] 2021-10-19 00:17
> Oh, I misunderstood the bug. This behavior is by design in Python (3.x) itself - the current directory is _not_ on `sys.path` by default. The directory that contains the script/module that runs as `__main__` is - that's the first entry in your `sys.path`.
> 
> To do what you want to do, you need to append the desired directory to `sys.path` instead (and possibly remove it after you've imported the module, if you don't want it to get in the way thereafter). Or, if this is specific to your filesystem layout and not the project, set `"env": {"PYTHONPATH": ...}`.

But it works fine when not using the debug mode.

**Comment by int19h** [comment] 2021-10-19 00:46
Hm, are you sure you don't have `PYTHONPATH` defined as a system- or user-global environment variable? Comparing `sys.path` between the working and the non-working run might also give some clues.

FWIW, if I try to set up a simple repro, with one module doing a `chdir()` to a different folder, and then trying to import something from that module, it does *not* work for me with CPython without debugger in the picture.

**Comment by david-cortes** [comment] 2021-10-19 01:11
In regular mode:
```python
os.environ["PYTHONPATH"]
```
```
/home/david/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/pythonFiles:/home/david/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/pythonFiles/lib/python
```

In debug mode:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/david/anaconda3/envs/py3/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'PYTHONPATH'
```

**Comment by fabioz** [comment] 2022-01-28 12:46
I just tested it here and I can't reproduce the case where it works.

I know from the thread that it is working for you because somehow you have `''` (an empty string) in `sys.path`, but I tried many ways of launching in python 3.9 and in none could I reproduce this...

As a note I remember this happened in earlier versions of python, so, going backwards I was able to make it work with 3.6 when you do a launch with `python -m module_name` (which does add the empty string to `sys.path`), but I don't really know why it's being added for you in 3.9 (maybe some custom site customization?).

So, I'm closing since the debugger seems to be doing the right thing and the behavior of adding the empty string to the `sys.path` seems to be very specific on how you launch it and the python version you're using (so, if you really need `''` in the `sys.path`, you should probably add it manually to make sure it's there).

As a note, doing `os.chdir` while having a `''` entry in `sys.path` for this use-case is a bit strange (usually you'd add the path to `sys.path` and try to do the import -- and optionally remove that path from `sys.path` right afterwards...).

**Closed by fabioz** 2022-01-28 12:46 UTC

**Comment by david-cortes** [comment] 2022-01-28 15:59
> I just tested it here and I can't reproduce the case where it works.
> 
> I know from the thread that it is working for you because somehow you have `''` (an empty string) in `sys.path`, but I tried many ways of launching in python 3.9 and in none could I reproduce this...
> 
> As a note I remember this happened in earlier versions of python, so, going backwards I was able to make it work with 3.6 when you do a launch with `python -m module_name` (which does add the empty string to `sys.path`), but I don't really know why it's being added for you in 3.9 (maybe some custom site customization?).
> 
> So, I'm closing since the debugger seems to be doing the right thing and the behavior of adding the empty string to the `sys.path` seems to be very specific on how you launch it and the python version you're using (so, if you really need `''` in the `sys.path`, you should probably add it manually to make sure it's there).
> 
> As a note, doing `os.chdir` while having a `''` entry in `sys.path` for this use-case is a bit strange (usually you'd add the path to `sys.path` and try to do the import -- and optionally remove that path from `sys.path` right afterwards...).

That empty string in `sys.path` is BTW added there by default:
* When launching `/usr/bin/python3` from the `python` package installed from debian main repository, whether by executing the file directly or by using the command `python3`, and whether it is launched as a user or as root.
* When launching any IDE with a python interpreter, including vscode itself, whether it is using the system's python or an anaconda user installation.
* When launching `python` registered from anaconda, whether directly by executing the binary file or by the shorthand `python` that it prepares with its configuration in `.bashrc`.
* When launching an interactice `ipython`.
* When a python kernel is used in a jupyter notebook.

And this is all with default configurations from stock debian and official anaconda.

The **only** case in which it will not be added there is if using the python debugger from vscode. The regular `pdb` still works as expected, as does `ipdb`.
