### ISSUE TITLE
Exception Traceback not always printed on Debug Console running a script in embedded interpreter

### ISSUE THREAD

**Issue by antounas** [microsoft/debugpy#624] opened 2021-05-14 08:23 UTC
## Environment data

- debugpy version: 1.3.0
- OS and version: Windows 10
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.8.1
- Using VS Code or Visual Studio: VS Code 1.56.2

## Actual behavior

Running a script which throws an exception in the embedded interpreter of my application doesn't always print the exception traceback in the debug console of VS Code or only a part of it is printed. Running again the same script a few times will eventually print the remaining traceback and the new ones.

## Expected  behavior

The complete traceback should be printed in the debug console of VS Code each time.

## Steps to reproduce:
1. I am writing a VS Code extension which spawns my application with the embedded interpret and then I run the following script in my application to prepare it for debugging.

```
import debugpy
debugpy.configure(python=python_executable)
debugpy.listen(5678)
debugpy.wait_for_client()
```

2. Afterwards I use the following launch configuration to attach to it

```
        "configurations": [
            {
                "name": "Remote Debug",
                "type": "python",
                "request": "attach",
                "connect": {
                    "host": "localhost",
                    "port": 5678
                }
            }
        ]
```
3. Next I run a simple script in my application which will throw an exception, such as:
```
def foo():
    prin('Hello')

foo()
```
Most times the Traceback isn't printed at all in the debug console while others only the first two lines appear. Some times the traceback is printed. If I run the same script in my application again the previous traceback along with the new one is printed.

If I Toggle Developers Tools in VS Code I can see the whole Traceback each time.

I have also checked in the code of debugpy and the IORedirect write method gets all the lines of the Traceback even if they don't appear in the Debug Console.

I have also enabled logging in  debugpy and there I see only the traceback lines that reach the Debug console.

The same behavior occurs in Centos 7.8 as well with previous versions of VS Code, debugpy, and python extension for VS Code. Same software and embedded Python interpreter though.

**Comment by fabioz** [comment] 2021-05-27 12:46
Humm, I'm not sure the issue is actually on the debugger here...

You mentioned that the `IORedirect` does get those lines, but is it possible that your application is stopping the embedded Python before the messages related to the IO are sent?

The debugger itself has some checks to verify that all asynchronous messages are delivered prior to exiting (by having a non-daemon thread keep it alive while there are things to be written https://github.com/microsoft/debugpy/blob/main/src/debugpy/_vendored/pydevd/pydevd.py#L215), but if somehow the Python interpreter is stopped independently, then it's expected that messages aren't really delivered which could make the messages not appear (given that this is the only report we have so far related that, I believe it's very likely that this is the issue).

**Comment by fabioz** [comment] 2021-06-03 14:06
Closing since there isn't evidence to support that the error is on the debugger side... if you do have additional info to support that, please reopen the issue.

**Closed by fabioz** 2021-06-03 14:06 UTC

**Comment by antounas** [comment] 2021-06-04 07:00
I am sorry I didn't reply sooner. There were other glitches as well and I was trying to find if there is a connection between them.

So, it isn't just the traceback that is not always printed.

I also tried the following script

```
def test():
    print("Hello")
    print("Visual")
    print("Studio")
    print("World")
    #time.sleep(0.0000001)
```

And I see no prints in the debug console, unless I uncomment the time.sleep line.

Also If I add a breakpoint to a line, start debugging and hit the breakpoint if I press the play button the line stays highlighted as if debugging is in progress.

All those three problems disappeared when I added a time.sleep(0.0000001) at the beginning of IORedirector.flush() in pydevd_io.py

Another glitch is that if I have some breakpoints, debug the script, press play to finish it and afterwards I add another breakpoint and run again the script sometimes the new breakpoint isn't hit.

I don't know if you see any relation between all those things and if my time.sleep in flush() actually solves the problem or just hides it.

Let me know if you need additional information and whether should I open a new issue or you would like to re-open this one.
