### ISSUE TITLE
Django static files never finish loading (still)

### ISSUE THREAD

**Issue by ManPython** [microsoft/debugpy#291] opened 2020-06-13 11:03 UTC
## Environment data

- debugpy version: 1.0.0b11

VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 6.1.7601

## Actual behavior
https://github.com/microsoft/ptvsd/issues/1866 - technical debt
Project with django working from CMD not debug

## Expected  behavior
Repair finalny or sugest solution

## Steps to reproduce:
Run some Django app with modified css, html files

**Comment by ManPython** [comment] 2020-06-13 11:57
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ["/static","/static/admin","/static/rest_framework","static/django_registration" ],
        #'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            #mod
            'loaders': [
                'admin_tools.template_loaders.Loader',
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]
```
I made experiments like this with no positive result for VSC debypy
`'DIRS': ["static","static/admin","static/rest_framework","static/django_registration" ],`

**Comment by ManPython** [comment] 2020-06-13 13:23
Looks is related with DEBUG = True
https://github.com/wagtail/wagtail/issues/4254

**Comment by int19h** [comment] 2020-06-16 21:32
I'm unable to reproduce this even with `DEBUG=True`. Can you provide a self-contained repro project?

**Comment by ManPython** [comment] 2020-06-17 13:02
Hmm.. I'm using portable version of VSC. Maybe this is detail? For this portable are vars as:
```
--user-data-dir=
--extensions-dir=
```
..to my path
For example bellow some settings that are related with django.
```
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_DIR = os.path.join(BASE_DIR, "static")
PROJECT_DIR = os.path.dirname(__file__)
STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(STATIC_DIR,STATIC_URL)

'''

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
   #'django.contrib.staticfiles.finders.DefaultStorageFinder',
)
'''
 
def skip_static_requests(record):
    if record.args[0].startswith('GET /static/'):  # filter whatever you want
        return False
    return True


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        # use Django's built in CallbackFilter to point to your filter
        'skip_static_requests': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': skip_static_requests
        }
    }, 
```
If thins working by CMD on WIN, LNX minds code and django is ok, just somethin with VSC and debug is wrong. Any of project and custom static mods made like not exist for session from VSC.

**Comment by int19h** [comment] 2020-06-17 17:52
Can you repro it on a basic Django project created from scratch?

If yes, could you share said project w/all the relevant configs?

**Comment by ManPython** [comment] 2020-06-17 22:10
Yes, just must prepare some basic example. I'll try to do this and pack in .zip. Next day will do this.
Thats interesing about this cas wehre in other IDEs are similar problem not only for me and VSC. Looks like some problem with remote control of Django.

**Comment by ManPython** [comment] 2020-06-18 23:48
I think I made You missunderstand due to not provide DJ version? Right?
[django vsc 1.zip](https://github.com/microsoft/debugpy/files/4801668/django.vsc.1.zip)
pass/pass
Here is example project. I was not to much creative here. I changed `bg` admin from blue to green and added `Welcomes test VSC`.
On VSC dj2.2.6 not replacing nothing, on CMD changes are aplied.

Funny situation.. 
On simple small templates debuging doing breakpoint, on hudge not.
I start some experiments with models to reduce or add more and found strange errors with pathlib.py
and
runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)

I unistall DJ2.6 install Django==3.0.7 and this working.
Again install Django==2.2.6 and now css to green is replaced, and txt as `Welcomes test VSC` not.
I think is not debugpy problem, just related with templates.
Eg. when using
```
'loaders': [
                'django.template.loaders. - anything
```
Exception has occurred: ImproperlyConfigured
app_dirs must not be set when loaders is defined.
  File "e:\python36\lib\site-packages\django\template\engine.py", line 36, in __init__

Need more time to investigate this due to related problem.

**Comment by int19h** [comment] 2020-06-19 00:47
Yes, I was using Django 3.x when trying to repro. 

Since at this point you are saying that it's most likely not debugpy-related, I'm going to close the issue, as it's not actionable for debugpy. Please re-open if your investigation determines otherwise.

**Closed by int19h** 2020-06-19 00:47 UTC
Labels: bug

**Comment by ManPython** [comment] 2020-06-19 14:11
Well.. can't working with this due to this issue github.com/microsoft/ptvsd/issues/1483#issuecomment-646654059
