### ISSUE TITLE
debugger will crash when print protobuf data 

### ISSUE THREAD

**Issue by zhaifly** [microsoft/debugpy#405] opened 2020-09-04 02:31 UTC
## Environment data

-   VS Code version: latest
-   Extension version (available under the Extensions sidebar): 
-   OS and version: ubuntu 16.04
-   Python version (& distribution if applicable, e.g. Anaconda): anaconda 3.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Relevant/affected Python packages and their versions: None
-   Relevant/affected Python-related VS Code extensions and their versions: v2020.0.106424
-   Value of the `python.languageServer` setting: Microsoft

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

output the value like pdb

## Actual behaviour

crash

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. load onnx model and print it's weights

## Logs

```
Traceback (most recent call last):
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 982, in trace_dispatch
    self.do_wait_suspend(thread, frame, event, arg)
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py", line 155, in do_wait_suspend
    self._args[0].do_wait_suspend(*args, **kwargs)
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1846, in do_wait_suspend
    keep_suspended = self._do_wait_suspend(thread, frame, event, arg, suspend_type, from_this_thread, frames_tracker)
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1880, in _do_wait_suspend
    self.process_internal_commands()
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1586, in process_internal_commands
    int_cmd.do_it(self)
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 496, in do_it
    self.method(dbg, *self.args, **self.kwargs)
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 668, in internal_get_variable_json
    for child_var in variable.get_children_variables(fmt=fmt, scope=scope):
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_suspended_frames.py", line 166, in get_children_variables
    dct = resolver.get_dictionary(self.value)
  File "/home/feiyue/.vscode-server/extensions/ms-python.python-2020.8.106424/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_plugins/extensions/types/pydevd_plugin_numpy_types.py", line 80, in get_dictionary
    ret['[0:%s] ' % (len(obj))] = list(obj[0:MAX_ITEMS_TO_HANDLE])
IndexError: too many indices for array
```

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
None
```

</p>
</details>

**Comment by fabioz** [comment] 2020-09-05 12:15
This is a duplicate of https://github.com/microsoft/debugpy/issues/378

It's already fixed in:
https://github.com/microsoft/debugpy/commit/44b01c81657f21ed12632317e15bd368e6d516ab

You can add the try..except in your local version while it's not released (i.e.: https://github.com/microsoft/debugpy/commit/44b01c81657f21ed12632317e15bd368e6d516ab#diff-c16a5898988dcad2b426faf14a860b8dR81)

**Closed by fabioz** 2020-09-05 12:15 UTC
