### ISSUE TITLE
Undefined symbol: AttachDebuggerTracing error when debugging on remote host.

### ISSUE THREAD

**Issue by flaviogalon** [microsoft/debugpy#675] opened 2021-07-23 13:52 UTC
Since the last VS Code update (1.58.2 - Linux) the "AttributeError: /usr/bin/python3: undefined symbol: AttachDebuggerTracing" error started to appear when trying to debug on a remote RaspberryPi Compute Module 3B+ using VS Code "Remote - SHH" plugin.

## Environment data

- debugpy version: 1.4.0
- Local machine OS and version: Ubuntu 20.04.2 LTS (x86_64)
- Host machine OS and version: Raspbian GNU/Linux 10 (Armv7l - 32 bits)
- Host machine Python version: Python 3.7.3
- Using VS Code or Visual Studio: VS Code 1.58.2 + Remote - SHH v0.65.7 + ms-python v2021.7.1053846006

## Actual behavior

When debugger is started the following error occurs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 267, in run_file
    start_debugging(target)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 257, in start_debugging
    debugpy.connect(options.address, access_token=options.adapter_access_token)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/common/compat.py", line 208, in kwonly_f
    return f(*args, **kwargs)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/__init__.py", line 135, in connect
    return api.connect(address, access_token=access_token)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/server/api.py", line 143, in debug
    log.reraise_exception("{0}() failed:", func.__name__, level="info")
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/server/api.py", line 141, in debug
    return func(address, settrace_kwargs, **kwargs)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/server/api.py", line 276, in connect
    _settrace(host=host, port=port, client_access_token=access_token, **settrace_kwargs)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/../debugpy/server/api.py", line 47, in _settrace
    return pydevd.settrace(*args, **kwargs)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2712, in settrace
    notify_stdin=notify_stdin,
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 2819, in _locked_settrace
    py_db.enable_tracing(py_db.trace_dispatch, apply_to_all_threads=True)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 1039, in enable_tracing
    pydevd_tracing.SetTrace(thread_trace_func)
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_tracing.py", line 83, in SetTrace
    if set_trace_to_threads(tracing_func, thread_idents=[thread.get_ident()], create_dummy_thread=False) == 0:
  File "/home/pi/.vscode-server/extensions/ms-python.python-2021.7.1053846006/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd_tracing.py", line 349, in set_trace_to_threads
    result = lib.AttachDebuggerTracing(
  File "/usr/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/bin/python3: undefined symbol: AttachDebuggerTracing
```

Launch.json:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python",
            "type": "python",
            "python.pythonPath" : "${workspaceFolder}",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "program": "${workspaceFolder}/src/System/main.py",
            "console": "integratedTerminal",
            "sudo": true, 
            "env": {
                "PYTHONPATH":"${PYTHONPATH}:/home/xxx/xxx/",
            }         
        }
    ]
}
```

## Workaround
Adding the following line in launch.json solved the issue:
```
           ...
            "env": {
                ...
                "PYDEVD_LOAD_NATIVE_LIB": "0"
            } 
            ...
```

Maybe related to #646?

**Comment by fabioz** [comment] 2021-07-23 14:02
This is a duplicate of https://github.com/microsoft/debugpy/issues/669 (it's already fixed in `master`).

Please see: https://github.com/microsoft/debugpy/issues/669#issuecomment-885095382 for workarounds.

**Closed by fabioz** 2021-07-23 14:02 UTC
