### ISSUE TITLE
Debugging Doesn't Work If File Is On Virtual/Network Drive

### ISSUE THREAD

**Issue by bshoshany** [microsoft/debugpy#361] opened 2020-08-11 15:21 UTC
Issue Type: <b>Bug</b>

I recently started using [Cryptomator](https://github.com/cryptomator/cryptomator) to encrypt my files locally before they are uploaded to the cloud (so if someone somehow gains access to my could storage, they still won't be able to access the actual files). This works by storing the files inside a "vault" mounted on some drive letter (e.g. V:). If I understand correctly, that drive is considered a network drive by the OS. The files on that vault are then automatically encrypted and saved in the folder used by the cloud service.

I noticed that if a Python program is located anywhere on this virtual drive V:, then VS Code cannot debug it. I set breakpoints, but the execution never actually breaks on those breakpoints; it simply runs the whole program from beginning to end without breaking.

Steps to reproduce:
1. Using VS Code, open any Python program stored on the local disk. (The content of the program itself doesn't seem to matter. For concreteness let's go with "print(2+2)".)
2. Set a breakpoint with F9 and press F5. **The execution will break at that point.**
3. Close VS Code.
4. Copy that same program to a folder on the Cryptomator vault (drive V:) and open it using VS Code.
2. Set a breakpoint with F9 and press F5. **Now the execution will NOT break at that point.**

Note: I also tried debugging a C++ program in the same folder, and had no issues; this problem seems to be specific to Python.

Python version: 3.8.5 64-bit
Extension version: 2020.7.96456
VS Code version: Code 1.47.3 (91899dcef7b8110878ea59626991a18c8a6a1b3e, 2020-07-23T13:12:49.994Z)
OS version: Windows_NT x64 10.0.19041

**Comment by int19h** [comment] 2020-08-11 17:51
@fabioz, is this fundamentally the same as #200, or was there something else special about network drives?

**Comment by fabioz** [comment] 2020-08-11 18:06
I'm not sure if it's the same.

@bshoshany at that issue the solution was doing:

`fsutil.exe file setCaseSensitiveInfo "</path/to/dir>" disable`

can you check if that works in your use case?

**Comment by fabioz** [comment] 2020-08-11 18:08
If it doesn't work, can you provide the debugger logs to diagnose the issue?

i.e.:

* Open VS Code
* Select the command Extensions: Open Extensions Folder
* Locate the Python extension directory, typically of the form ms-python.python-2020.*.****
* In that directory ensure you do not have any debug*.log files, if you do, please delete them
* Go back into VS Code and modify your launch.json to add the setting "logToFile": true, see below:

```
"version": "0.2.0",
"configurations": [
    {
        "name": "Python: Current File (Integrated Terminal)",
        "type": "python",
        "request": "launch",
        "program": "${file}",
        "stopOnEntry": true,
        "console": "integratedTerminal",
        "logToFile": true
    },
```

* Start debugging
* When done, go back into the extension directory and upload the debug*.log files into this GitHub issue.

**Comment by bshoshany** [comment] 2020-08-11 20:12
> `fsutil.exe file setCaseSensitiveInfo "</path/to/dir>" disable`

When I try this, I get "A local NTFS volume is required for this operation." The virtual drive is created via [Dokany](https://github.com/dokan-dev/dokany) and (to my understanding) it does not use the NTFS file system. It seems like the file system Dokany uses is in fact **case sensitive**, because I tried now and managed to create two files with the same name up to case. In fact, now I also noticed that when I try to debug the Python file, another tab opens in VS Code for the same file except with all lowercase letters.

Here are the log files.

[debugger.vscode_6fe56e50-73e0-401b-870c-38279049bc31.log](https://github.com/microsoft/debugpy/files/5059259/debugger.vscode_6fe56e50-73e0-401b-870c-38279049bc31.log)
[debugpy.adapter-11268.log](https://github.com/microsoft/debugpy/files/5059260/debugpy.adapter-11268.log)
[debugpy.launcher-11448.log](https://github.com/microsoft/debugpy/files/5059261/debugpy.launcher-11448.log)
[debugpy.pydevd.15056.log](https://github.com/microsoft/debugpy/files/5059262/debugpy.pydevd.15056.log)
[debugpy.server-15056.log](https://github.com/microsoft/debugpy/files/5059263/debugpy.server-15056.log)

**Comment by bshoshany** [comment] 2020-08-12 15:17
So at this point I'm pretty sure the problem is simply that VS Code knows there's a breakpoint in the file `Test.py`, but somewhere in the process the letters all become lowercase, and since the file `test.py` is considered to be a separate file, VS Code does not know that there should be a breakpoint in that file.

I'm also almost certain the problem is specifically with the Python extension, rather than VS Code itself, since debugging works with the C++ extension without any issues.

Can we simply add an option (either in VS Code itself or in the Python extension) to ignore case in file names (and paths), and/or to treat a file system as case sensitive even though it's running on Windows? That seems like it would be the easiest solution!

**Comment by fabioz** [comment] 2020-08-12 16:31
Can you do the following:

Run the following in the debugger:

```
import pydevd_file_utils
print(pydevd_file_utils.__file__)
```

Then, open the file printed and change the section that does:

```
if IS_WINDOWS:
    normcase = _normcase_windows
```

to:

```
if IS_WINDOWS:
    normcase = _normcase_linux
```

i.e.: https://github.com/microsoft/debugpy/blob/master/src/debugpy/_vendored/pydevd/pydevd_file_utils.py#L282

and see if it fixes your case.

**Comment by bshoshany** [comment] 2020-08-12 16:47
Yes! That fixes the problem. Breakpoints now work as intended.

I wonder if instead of just checking which OS is being used, the debugger could check if the specific file system being used is case-sensitive or not? Alternatively, it might be easier to add an option for the user to manually specify whether the file system is case-sensitive.

**Comment by int19h** [comment] 2020-08-12 16:51
That's basically what #200 is about. But it's not quite so trivial, because individual *folders* can be case-sensitive (and their subfolders can, in turn, be case-insensitive) - fixing it properly means that the debugger can no longer case-normalize paths as a whole, but needs to do so separately for every path step, so there are perf implications, as well.

**Comment by int19h** [comment] 2020-08-12 16:51
Closing as duplicate of #200 - we'll track any further work on this there.

**Closed by int19h** 2020-08-12 16:51 UTC
