### ISSUE TITLE
Python debugger stopped working for no apparent reason

### ISSUE THREAD

**Issue by itzsimpl** [microsoft/debugpy#630] opened 2021-05-14 23:05 UTC
## Environment data

-   VS Code version: 1.57.0-insider
-   Extension version (available under the Extensions sidebar): 2021.5.842923320
-   OS and version: MacOS BigSur 11.3.1 and Ubuntu 20.04
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): venv
-   Relevant/affected Python-related VS Code extensions and their versions: Remote-SSH 0.64.4
-   Value of the `python.languageServer` setting: Pylance

## Expected behaviour

Starting a debug session

## Steps to reproduce:

When starting the session, the integrated Terminal crashes with the message "/bin/zsh: can't open input file:", see 
https://user-images.githubusercontent.com/4784070/118339339-da39dd80-b518-11eb-9b2d-9c022ed3d67e.mov

On a Remote-SSH session to a Ubuntu 20.04 server, the terminal crashes with "/bin/bash: : No such file or directory" 
<img width="977" alt="image" src="https://user-images.githubusercontent.com/4784070/118339579-8976b480-b519-11eb-936c-ec298e57b070.png">

The terminal otherwise works fine, I just cannot start a debug session. I have killed the remote server and reinstalled VSCode, nothing helps.

**Comment by fabioz** [comment] 2021-05-27 12:26
Well, I'm closing this on `debugpy` since there doesn't seem to be anything to be done here (as the issue is on VSCode itself).

The report from https://github.com/microsoft/vscode/issues/124116 mentions that the current insiders build already has a fix (so, the next VSCode release should have that fixed...).

The workaround until then is using: `"console": "internalConsole"` in your debug configuration.

**Closed by fabioz** 2021-05-27 12:26 UTC
