### ISSUE TITLE
python debugging stuck

### ISSUE THREAD

**Issue by kzhui125** [microsoft/debugpy#107] opened 2020-04-08 09:09 UTC
## Environment data

-   VS Code version: 1.43.2
-   Extension version : 2020.3.71659
-   OS and version: macOS 10.15.4
-   Python version : 3.7.5
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): XXX
-   Relevant/affected Python packages and their versions: XXX
-   Relevant/affected Python-related VS Code extensions and their versions: XXX
-   Jedi or Language Server? : Jedi Enabled
-   Value of the `python.languageServer` setting: Microsoft

I meet this issue frequently. No response pressing continue / Step over / Step into / Step Out.

Pressing stop will stop debugging, pressing restart will stop debugging too, but don't restart.

I see the error in development tool console:

<img width="1667" alt="1" src="https://user-images.githubusercontent.com/11925432/78766271-a5756180-79bb-11ea-96ae-7046c8e9e62a.png">

**Comment by int19h** [comment] 2020-04-08 18:54
Since repro steps involve creating watch expressions with errors, this is almost certainly a dupe of https://github.com/microsoft/vscode-python/issues/10776.

However, this problem should have been fixed in debugpy 1.0.0b4. Can you please try doing this at the beginning of your repro sample:
```py
import debugpy
print(debugpy.__version__)
```
and check what it gives you?

**Comment by int19h** [comment] 2020-04-08 19:13
Actually, I stand corrected - that bug is *not* fixed in b5, and this is what you're in fact hitting. I'm going to use the other issue to track resolution, since it has more comments and subscribers.

**Closed by int19h** 2020-04-08 19:13 UTC
