### ISSUE TITLE
Debugging broken on MacOS Catalina

### ISSUE THREAD

**Issue by conkerkh** [microsoft/debugpy#366] opened 2020-08-14 13:09 UTC
## Environment data

-   VS Code version: 2020.8.101144
-   Extension version (available under the Extensions sidebar): 2020.8.101144
-   OS and version: MacOS 10.15.6
-   Python version (& distribution if applicable, e.g. Anaconda): ANY
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Relevant/affected Python packages and their versions: ALL
-   Relevant/affected Python-related VS Code extensions and their versions: -
-   Value of the `python.languageServer` setting: XXX

[**NOTE**: If you suspect that your issue is related to the Microsoft Python Language Server (`python.languageServer: 'Microsoft'`), please download our new language server [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) from the VS Code marketplace to see if that fixes your issue]

## Expected behaviour

Debugging start and I'm able to step through pause etc.

## Actual behaviour

After starting debugging debugger just hangs there, when debugging is stopped timeout appears in bottom right.

## Steps to reproduce:

Start any debug session of python

**Comment by karthiknadig** [comment] 2020-08-17 16:38
@conkerkh Can you please share some repro code? Also, try enabling debugger logs, see here for instructions: https://github.com/microsoft/debugpy/wiki/Enable-debugger-logs

**Comment by conkerkh** [comment] 2020-08-17 20:14
@karthiknadig
 to be honest this simple code can reproduce mentioned problem, it seems to be related to "input()"

```
if __name__ == "__main__":
    while(True):
        s = input()
        print(s)
```

**Comment by karthiknadig** [comment] 2020-08-17 20:48
@conkerkh This occurs because of `input()`. Try adding `"redirectOutput": true` to your launch.json debug configuration, see https://github.com/microsoft/debugpy/issues/296#issuecomment-660285084. This was changed recently to allow better control of IO redirection.

**Comment by int19h** [comment] 2020-08-18 02:58
This is a dupe of #370

**Closed by int19h** 2020-08-18 02:58 UTC
