### ISSUE TITLE
 Launching VSCode debugpy takes significantly longer to attach to process after update to 1.6.2

### ISSUE THREAD

**Issue by mwpark2014-d** [microsoft/debugpy#1003] opened 2022-08-03 23:06 UTC
Before creating a new issue, please check the [FAQ](https://github.com/microsoft/debugpy/wiki/FAQ) to see if your question is answered there.

## Environment data

- debugpy version: 1.6.2
- OS and version: Ubuntu 18.04.6 LTS
- Python version (& distribution if applicable, e.g. Anaconda): Python 3.7.5
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Attaching the debugger takes significantly longer (22 minutes) to start up my app.

## Expected  behavior

Around 17 seconds build time with the same code. 

## Steps to reproduce:
1. Update vscode-python version from 8.1 to 10.0, which updates debugpy to 1.6.2
2. Run and debug my app (gunicorn running flask) through VS code. `launch.json` settings and app code are the same
3. App takes significantly longer to build imported packages, specifically `python-jose` version 3.0.1

Can provide more info upon request

**Comment by fabioz** [comment] 2022-08-04 12:05
One change in the attach is related to the shared libraries scanned at attach time with `gdb` which is probably the culprit here.

Previously we specified the libraries needed to get `dlopen` to work, but depending on the Linux distribution it'd fail from time to time, so, it was decided not to specify those before and just let it analyze all shared libraries (but that can make the attach much slower depending on your setup -- on some cases it's barely noticeable but in some it really can be much slower -- still, I hadn't seen a report for a 22 minute attach up until now... I guess we should have a way of notifying after some timeout how the user can specify the shared libraries to scan).

Anyways, the way to fix this for you is setting an environment variable saying which are the shared libraries that must be scanned.

You can do this by setting the following environment variable:

`PYDEVD_GDB_SCAN_SHARED_LIBRARIES=libdl, libltdl, libc, libfreebl3`

Please let me know if doing that fixes it for you.

**Comment by fabioz** [comment] 2022-08-04 12:09
Actually, rereading I'm not sure this is actually it... does this happen in an attach to situation or just running your app (and the issue is that running your use case is slower)?

If it's the case that it's just slower to run, do you think you could provide some code to showcase what's slower in the current version vs the previous version?

**Comment by mwpark2014-d** [comment] 2022-08-05 05:17
Thanks for the speedy response. I believe this is an attach to situation. I have a `launch.json` file that launches `~/.virtualenvs/my_app/bin/gunicorn`. 

Here is the output when running the configuration:
`/usr/bin/env /home/.virtualenvs/my_app/bin/python /home/discord/.vscode-server/extensions/ms-python.python-2022.10.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 38127 -- ~/.virtualenvs/my_app/bin/gunicorn --worker-class=gevent --bind=0.0.0.0:5004 --reload --timeout=0 my_app:create_app\(\)`

The slowdown is before the app starts executing code. If I set a breakpoint, I can see that it stalls when importing`python-jose`, which depends on a bunch of auth libraries. 

I tried setting `PYDEVD_GDB_SCAN_SHARED_LIBRARIES=libdl, libltdl, libc, libfreebl3` as an env variable in my `launch.json` file, but that didn't seem to work

**Comment by fabioz** [comment] 2022-08-05 10:24
If you set `PYDEVD_GDB_SCAN_SHARED_LIBRARIES=libdl, libltdl, libc, libfreebl3` in your shell and then start VSCode from that shell so that it's inherited, does it work?

**Comment by mwpark2014-d** [comment] 2022-08-05 19:45
I tried `export PYDEVD_GDB_SCAN_SHARED_LIBRARIES="libdl, libltdl, libc, libfreebl3"` in my python debug console but that didn't work

**Comment by fabioz** [comment] 2022-08-11 18:39
> I tried `export PYDEVD_GDB_SCAN_SHARED_LIBRARIES="libdl, libltdl, libc, libfreebl3"` in my python debug console but that didn't work

You actually need to do that in the shell that starts VSCode itself...

**Comment by yevgeni-zolotko** [comment] 2022-09-07 14:06
Since the #1044 is closed as duplicate, I will write here.

On Windows, I tried setting the `PYDEVD_GDB_SCAN_SHARED_LIBRARIES` for VS Code (and checked it is set in its PowerShell Terminal pane), but it didn't help. Guessing from the library names, (`libdl` etc) this may be specific to Unix? And is there a similar solution for Windows?

**Comment by fabioz** [comment] 2022-09-07 15:13
> Since the #1044 is closed as duplicate, I will write here.
> 
> On Windows, I tried setting the `PYDEVD_GDB_SCAN_SHARED_LIBRARIES` for VS Code (and checked it is set in its PowerShell Terminal pane), but it didn't help. Guessing from the library names, (`libdl` etc) this may be specific to Unix? And is there a similar solution for Windows?

Sorry, I missed that this was a in a different OS (reopening that issue).

**Comment by int19h** [comment] 2022-10-07 18:33
We don't propagate events from the server until after we send the "attach" response. 
https://github.com/microsoft/debugpy/blob/646d921dc12644e87dcdc2f84aa53cae6c2e45e3/src/debugpy/adapter/clients.py#L579-L582
We could special-case "output" by propagating them as soon as client connects. That would change their order wrt all other events that might happen during initialization, but I think it should be safe for output.

**Comment by fabioz** [comment] 2022-10-07 18:45
In this particular case, we are pre-connection.

i.e.: we want to show the output of the process spawned for the attach (which is currently put in the logs at: https://github.com/microsoft/debugpy/blob/v1.6.3/src/debugpy/adapter/servers.py#L555).

**Comment by int19h** [comment] 2022-10-07 18:51
Ah, I see now. That method is called from the "attach" request handler, so there's a client connection to which output could be propagated. However, we probably also don't want to propagate everything - IIRC, some of it is diagnostic, and we really just want the errors/warnings. Maybe use stdout and stderr to separate these? Currently this only captures stdout, but it really should capture both.

**Comment by fabioz** [comment] 2022-10-07 19:00
Yes, you're right that some of it may be too much info... I think separating stdout/stderr can make sense to show only errors -- right now it prints everything to stdout.

Although I must say that if there's some kind of progress UI maybe it'd be nice to show the stdout too so that the user can get a sense of what's happening -- and if an error actually happens showing the stdout can also help in tracking down what may be the actual problem.

**Comment by fabioz** [comment] 2022-10-07 19:15
I'll take a look at sending those as output events.

**Closed** 2022-10-17 10:05 UTC
Labels: bug
